### ISSUE TITLE
Missing Flutter Web implementation

### ISSUE THREAD

**Issue by andreagr** [HMS-Core/hms-flutter-plugin#10]

**Comment by aktug** [comment]
Hi @andreagr,
HMS Flutter plugins don't support Web for now.

**Comment by sarope** [comment]
The iOS implementation is also missing, so when you try to build on xCode, everything breaks. Is there a way around this?

**Comment by sarope** [comment]
> The iOS implementation is also missing, so when you try to build on xCode, everything breaks. Is there a way around this? (So I can still import the plugin and build as normal in xCode)

This seems to be working properly as expected now

**Comment by joaobiriba** [comment]
The web implementation is useful IMHO. Is it planned or can we leave this Issue open and someone can develop it eventually?
