### ISSUE TITLE
huawei_hmsavailability 插件bug

### ISSUE THREAD

**Issue by tygm** [HMS-Core/hms-flutter-plugin#105]
**Description**
直接运行自带demo，在非华为手机上，弹出提示安装hms core对话框，点击安装，然后没任何反应

**Expected behavior**
正常安装hms core

**Current behavior**
点安装没反应

**Screenshots**

**Logs**
没报错日志，

**Environment**
 - Platform: flutter
 - Kit: huawei_hmsavailability 
 - Kit Version 最新版本
 - OS Version android 11
 - Android Studio version (if applicable) 
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) 

**Other** 
Add any other context about the problem here

**Comment by ozkulbeng** [comment]
Hi @tygm 
In order to get the response of the dialog box, AppGallery must be installed in your phone. That "Install" button redirects you to AppGallery to download HMS Core. So you should install AppGallery first manually.

Have a nice day.

**Comment by NeverAskMe** [comment]
Hi, I'm also facing the same problem with Account kit.

**Comment by sinan-aktepe** [comment]
Hi @NeverAskMe 
If **AppGallery** is installed on device, the account kit APIs request for HMS Core Apk installation and redirects to the AppGallery. If you think that the issue is irrelevant to this use case, you can provide logs or open a new issue.
