### ISSUE TITLE
ml机器学习插件语音转文字错误

### ISSUE THREAD

**Issue by tygm** [HMS-Core/hms-flutter-plugin#106]
**Description**
华为机器没问题
非华为机器（oppo），不管装不装hms core，在调用语音转文字的时候，总是提示“服务不可用”，并有log报错。如下。根据官网错误码信息，11203是网络问题，但实际上网络没问题（确定）

**Expected behavior**
正常进行语音转文字

**Current behavior**
不正常，如上

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
I/MLASR_EmuiUtil(29607): Get Manufacturer: OPPO
E/MLASR_AsrEngine(29607): not HuaWei phone and not Emui
E/AsrProcessor(29607): onError code : 11203, message : 3016, not HuaWei phone and not Emui
E/flutter (29607): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(AsrMethodHandler, not HuaWei phone and not Emui, 112033016, null)

**Environment**
 - Platform: [e.g. React-Native/Cordova/Flutter/Xamarin]
 - Kit: [e.g. Push/Map/Ads/Account/IAP]
 - Kit Version [e.g. 5.0.3]
 - OS Version [e.g. Android 11]
 - Android Studio version (if applicable) [e.g. 4.1]
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) 

**Other**
Add any other context about the problem here

**Comment by sinan-aktepe** [comment]
Hi @tygm ,

**Comment by sinan-aktepe** [comment]
Hi @tygm , We have spotted the issue and it'll be fixed on our next release. For now, you can use this workaround to get **asr** service working:

- Go to **build.gradle** file of the **huawei_ml** plugin and upgrade the **asr** service to latest version, which is **3.0.0.301**
   ```gradle
   // implementation 'com.huawei.hms:ml-computer-voice-asr-plugin:2.0.5.300'
   implementation 'com.huawei.hms:ml-computer-voice-asr-plugin:3.0.0.301'
   ````

After applying the changes, the service should work as expected.
