### ISSUE TITLE
Issue with creating a purchase with Huawei IAP

### ISSUE THREAD

**Issue by BombeyR** [HMS-Core/hms-flutter-plugin#108]
Hello,
I tried using Huawei IAP for flutter. when I initiate a product purchase it opens an intent saying "Activating In-app purchases". later says "exiting In-app purchases" and the intent returns null. I have no idea how to proceed.

here is the code I used.

```
PurchaseIntentReq request = PurchaseIntentReq(
        priceType: IapClient.IN_APP_NONCONSUMABLE, productId: "no_ads");

    request.developerPayload = "Test";

    //Call the createPurchaseIntent API.

    PurchaseResultInfo result = await IapClient.createPurchaseIntent(request);

```

**Comment by sinan-aktepe** [comment]
Hi @BombeyR 
In AppGallery Connect, the product you've created with the id of **no_ads** is most likely **deactivated**. To proceed the purchase, products should be in **active** status.

**Comment by BombeyR** [comment]
Hello, I tried I have verified the product ID.

![tempsnip](https://user-images.githubusercontent.com/32114445/131700208-fc3a8f59-21da-49f1-b573-d6873f95ffe7.png)

still the same behavior

**Comment by sinan-aktepe** [comment]
Hi, please check following steps:

- Make sure you didn't miss these configurations. Also check if **you've accepted all agreements** in AGC.
   https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/config-agc-0000001050033072

- Check whether IAP Service supports **your country/region**.
   https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/huawei-iap-coverage-0000001050438753

- Then make sure your **agconnect-services.json** file is up to date.

If everything is in place, share the **HMS version of device** and **logs**.

The result codes for IAP Service:
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/hms-iap-results-0000001062893770
