### ISSUE TITLE
hms-flutter-plugin depends on fresco 2.2.0 on android which isn't available anywhere

### ISSUE THREAD

**Issue by enveraltin** [HMS-Core/hms-flutter-plugin#109]
Hi,

As you can see `com.facebook.fresco` version `2.2.0` is not available on any public maven repositories. This breaks our builds. As a temporary fix we applied the following in `android/app/build.gradle`:

```
dependencies {
    // ...
    compile("com.facebook.fresco:fresco:2.2.0") {
        exclude group: 'com.facebook.fresco', module: 'fresco'
    }
    compile("com.facebook.fresco:fresco:2.5.0")
}
```

I also checked the code here and didn't see any references to fresco in any java files. Perhaps simply drop the dependency if it's not used?

Cheers.

**Comment by sinan-aktepe** [comment]
Hi @enveraltin 

Fresco is used for **ProductVisionSearch** service of the ML SDK.

We've tried to reproduce the issue but nothing went wrong during the build with **Fresco 2.2.0**

This is the **build.gradle** file of our demo:
```gradle
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://developer.huawei.com/repo/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.0'
        classpath 'com.huawei.agconnect:agcp:1.4.2.301'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {url 'https://developer.huawei.com/repo/'}
    }
}
```

If yours is different, can you try to build your app with configurations above and inform us about the progress?

**Comment by enveraltin** [comment]
@sinan-aktepe Thank you for your response.

We migrated from (soon to be shut down) JCenter to Maven Central, so we simply replaced `jcenter()` with `mavenCentral()` in our gradle scripts. IMHO, you should do the same. Feel free to see it for yourself, you'll see the gradle failing to find `com.facebook.fresco:fresco:2.2.0`. You can check what Maven Central has on https://mvnrepository.com to validate the issue.

I feel like you have a couple options here:

* Remove fresco dependency from `hms-flutter-plugin` where it's not used. Feel free to keep it in your other modules if you please, but at least do the switch to `mavenCentral()` and upgrade it to something like `2.5.0` and do some testing in other modules -- this is possibly the best idea.
* Upgrade fresco to 2.5.0 if jcenter has it.
* Host fresco 2.2.0 files on developer.huawei.com repo -- this is possibly the ugliest.

As a side note, I'd have published all the binary and open source dependencies of this plugin to `mavenCentral()` and converted your Maven repo at `developer.huawei.com` to a maven central mirror, I understand this is more of a political decision than a technical one.

While we are at it, this flutter plugin depends on a couple jar files hosted on developer.huawei.com repo. I tried to take a peek at by disassembling the java bytecode of those and I don't really like what they do with JNI from a security/privacy perspective. We are taking some crazy extra measures to avoid shipping those to users without HMS Core (ie, people who install our app from Google Play Store), which costs us a bit and it's clunky. Do you plan to release the source code for those bits as well?

Cheers,

**Comment by sinan-aktepe** [comment]
@enveraltin We usually update our plugins along with the 3rd party dependencies that are used in them. So **Fresco** will be up to date on next release.

About JNI, our flutter plugin is basically a wrapper around the native ML SDK. We don't do plugin specific changes on our releases. For your questions about the native SDK and more, you can [submit a ticket online](https://developer.huawei.com/consumer/en/support/feedback/#/).
