### ISSUE TITLE
集成此统计插件后，在首次启动前会获取用户应用列表信息，违反了隐私政策，有设置可以阻止这个吗？

### ISSUE THREAD

**Issue by weboey** [HMS-Core/hms-flutter-plugin#110]
![mh2](https://user-images.githubusercontent.com/14002656/132674350-ac3e27e7-575d-42b6-8893-b61ac72ab1a6.png)

**Comment by furkansarihan** [comment]
@weboey This plugin is a wrapper of Huawei Analytics SDK. This issue resolves with Huawei Analytics SDK version 5.3.0.300. We will address this issue in our next major release, please keep an eye on [our pub.dev repository](https://pub.dev/publishers/developer.huawei.com/packages) for any updates.
