### ISSUE TITLE
How to change notification icon

### ISSUE THREAD

**Issue by reverseapp** [HMS-Core/hms-flutter-plugin#111]
On Android, if we don't pass icons with transparency we see our icon as blank grey color. I can't find on documentation how to change the icon to the custom one. And, If there a method to change color of notification icon would be great!

Looks like ![this](https://i.imgur.com/153QsWf.jpg)

Should Look like ![this](https://i.imgur.com/KmOrPPI.jpg)

**Environment**
 - Platform: Flutter
 - Kit: huawei_push: ^5.1.1+301
 - OS Version Android 10
 - Your Location/Region Turkmenistan

**Comment by atavci** [comment]
Hello, This issue is not related to Flutter Push Plugin instead it is related to Android Notification Properties. It can caused by the size or the transparency of the image you use. The icon you use on the status bar should be transparent as stated in the Android Notifications Documentation:

> “Update or remove assets that involve color. The system ignores all non-alpha channels in action icons and in the main notification icon. You should assume that these icons will be alpha-only. The system draws notification icons in white and action icons in dark gray.”

You can find similar questions on StackOverflow:
https://stackoverflow.com/questions/45318614/why-is-my-smallicon-for-notifications-always-greyed-out
https://stackoverflow.com/questions/69074021/notification-icon-on-android-shown-as-a-white-square?noredirect=1&lq=1

**Comment by reverseapp** [comment]
@atavci Thank you for quick response.
On Firebase Cloud messaging we can configure default notification icon like:
`
<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@mipmap/ic_stat_logopush" />
    `
Is there anything similar on Flutter Huawei Push kit?

**Comment by atavci** [comment]
Flutter Huawei Push Kit depends on the native Huawei Push Kit SDK which handles the push notifications that sent from the cloud. 

To customize the push notification icon you can add your icon to your `android/app/res/drawable` folder and add the following meta tag inside the application tag of your AndroidManifest.xml file

```
<meta-data
      android:name="com.huawei.messaging.default_notification_icon"
      android:resource="@drawable/ic_notification" />
``` 

You can find more details [here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/android-smalll-icon-0000001050040134).

**Comment by reverseapp** [comment]
Oh great. Thank you.
Icon has changed for the notification messages, but did not changed for data messages, i show them like:
`
hms.Push.localNotification({
                      hms.HMSLocalNotificationAttr.TITLE: "Bismillah",
                      hms.HMSLocalNotificationAttr.MESSAGE: message.data,
                      hms.HMSLocalNotificationAttr.SMALL_ICON:
                          'notification_icon',
                      hms.HMSLocalNotificationAttr.IMPORTANCE:
                          hms.Importance.MAX,
                    });
`
I see grey rectangle instead of icon and can't change it.
Thank you.

**Comment by atavci** [comment]
Local notifications use a different notification channel so you have to specify your icon in the request map:

```
Map<String, dynamic> defaultNotification = {
    HMSLocalNotificationAttr.TITLE: 'Notification Title',
    HMSLocalNotificationAttr.MESSAGE: 'Notification Message',
    // The notification small icon should be put under `android/app/res/mipmap` directory.
    HMSLocalNotificationAttr.SMALL_ICON: 'ic_notification',
    HMSLocalNotificationAttr.BIG_TEXT: 'This is a bigText',
    HMSLocalNotificationAttr.SUB_TEXT: 'This is a subText',
    // 
    // .... Other Parameters
    //
};

  Map<String, dynamic> notification =
      Map<String, dynamic>.from(defaultNotification);
```

Best. 👍

**Comment by reverseapp** [comment]
@atavci Allah razi olsun
