### ISSUE TITLE
building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by lvsecoto** [HMS-Core/hms-flutter-plugin#114]
Xcode's output:
↳
    AGConnectCredential-bvichmfkhurchoaglolalknstzlw
    ld: in /Users/xxx/StudioProjects/xxx/ios/Pods/HiAnalytics/HiAnalytics.framework/HiAnalytics(HAAESCipher-89b5d98db6816dc41288f376cdc237e65e8837d4832bb546c52093c5eb00878d.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/xxx/StudioProjects/xxx/ios/Pods/HiAnalytics/HiAnalytics.framework/HiAnalytics' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    AGConnectCredential-bvichmfkhurchoaglolalknstzlw

**Comment by rahmicanisin** [comment]
Please upgrade to the latest CocoaPods (at least 1.10.2).

![image](https://user-images.githubusercontent.com/45042659/134858098-ba0978c1-6d2c-42fd-9f9e-47c866d94a20.png)

Xcode → Target Project → Build Setting → Excluded Architectures → *"arm64"

Xcode → Pod Target → Build Setting → Excluded Architectures → *"arm64"
