### ISSUE TITLE
Does the Huawei AR Engine have a guide on how to create custom facemesh texture like ArCore?

### ISSUE THREAD

**Issue by HaoZhang-umich** [HMS-Core/hms-flutter-plugin#116]
I am trying to create a face mesh texture for ar engine, but I cannot find a guide on it.
Can you show me some instructions like what google provided for arcore?
[Creating custom textures and 3D models for Augmented Faces ](https://developers.google.com/ar/develop/c/augmented-faces/creating-assets)
Even a face mesh texture would be helpful.

**Comment by atavci** [comment]
Hello,

Unfortunately for the time being there is  no official guide released, but you can keep an eye on [Huawei Developers ](https://developer.huawei.com/consumer/en/doc/development/graphics-Guides/introduction-0000001050130900) for the latest updates. Once the native document is published it will be also released on the [AR Engine Flutter Plugin Development Guide](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001058897997).

Best.
