### ISSUE TITLE
[huawei_account] login loading in android show a random android default banner

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#118]
**Description**
when i tried after upgrading this plugin to last update with flutter 2.5.1 stable 
`
 huawei_account: ^5.2.0+301
`
i got  a banner with android logo and my app name on the top of the login screen while login in using Huawei account 
it appear for 1 - 5 seconds , first i guessed it just will be in debug mode only but it appeared also on release mode .

**Expected behavior**
to show circler progress indicator without this kind of random widgets
 
**Current behavior**
showing random widgets while logging in or register process 

**Screenshots**

![243149497_555358792397335_4249791430687631068_n](https://user-images.githubusercontent.com/74349843/135060001-30114190-f30b-46cd-9a7b-aeeeab71d46e.png)

**Environment**
 - Platform: Flutter
 - Kit: Account
 - Kit Version 5.2.0+301
 - OS Version  Android 10
 - Platform version 2.5.1

**Comment by sinan-aktepe** [comment]
Hi @mustafa-707 ,

We've tried to reproduce the issue but there are no unusual ui behaviours so far. Can you share following information please:

- Test device brand & HMS Core version of device
- Plugins/packages installed in pubspec.yaml file.

**Comment by mustafa-707** [comment]
my device is Huawei Nova 7i 
with core version : 11.4.1.304


my project yaml
```
  cupertino_icons: ^1.0.3
  carousel_slider: ^4.0.0
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  flutter_slidable: ^0.6.0
  flutter_typeahead: ^3.2.1
  auto_size_text: ^2.1.0
  flutter_animator: ^3.1.2
  #Tools & State-Managment
  provider: ^6.0.0 #provider: ^6.0.0 # for chewie 1.2.2
  shared_preferences: ^2.0.8
  # Firebase & Google
  firebase_crashlytics: ^2.2.1
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_messaging: ^10.0.7
  google_mobile_ads: ^0.13.5
  in_app_purchase: ^0.5.2
  in_app_review: ^2.0.3
  # Social login
  flutter_facebook_auth: ^3.5.0
  google_sign_in: ^4.5.9
  twitter_login: ^4.0.1
  huawei_account: ^5.2.0+301
  sign_in_with_apple: ^3.0.0
  # Huawei
  huawei_location: ^5.1.0+303
  huawei_iap: ^6.0.0+300
  huawei_push: ^5.1.1+301
  # Images,videos
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  video_player: ^2.2.4
  youtube_player_flutter: ^8.0.0
  photo_view: ^0.12.0
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  chewie: ^1.2.2
  flutter_inappwebview: ^5.3.2
  wechat_assets_picker: ^6.2.0
  # Maps
  geolocator: ^7.6.2
  flutter_map: ^0.12.0
  # Web,Api
  http: ^0.13.3
  webview_flutter: ^2.0.14
  flutter_widget_from_html: ^0.7.0
  url_launcher: ^6.0.11
  flutter_webview_plugin: ^0.4.0
  html_unescape: ^2.0.0
  overlay_support: ^1.2.1
  # Third-party Tools
  flutter_local_notifications: ^8.2.0
  timezone: ^0.8.0
  flurry: ^0.0.7
  sentry_flutter: ^6.0.1
  app_tracking_transparency: ^2.0.1
  uni_links: ^0.5.1
  # Utiles
  local_auth: ^1.1.8
  tutorial_coach_mark: ^1.1.1
  flutter_app_badger: ^1.3.0
  visibility_detector: ^0.2.0
  intl: ^0.17.0
  package_info: ^2.0.2
  device_info: ^2.0.2
  page_view_indicators: ^2.0.0
  share_plus: ^2.1.4
  flutter_share: ^2.0.0
  camera: ^0.5.8+17
  path_provider: ^2.0.5
  path: ^1.8.0
  inview_notifier_list: ^2.0.0
  permission_handler: ^8.1.6
  simple_tooltip: ^1.0.0
  store_redirect: ^2.0.0
  flutter_hms_gms_availability: ^2.0.0
  photo_manager: ^1.3.4
  connectivity: ^3.0.6

```

**Comment by sinan-aktepe** [comment]
Hi, with a project this big, it's hard to find the cause of this issue. We want you to run your app only with **huawei_account** to see if the problem is caused by our plugin or not.

Or you can send us **pubspec.yaml** file of the minimal reproducible form of this project.

**Comment by mustafa-707** [comment]
actually i tried the same code with flutter 1.66.2 and flutter 2.2.3 and all good 

the problem just happened when i upgrade to flutter 2.5.0 and flutter 2.5.1
