### ISSUE TITLE
[huawei_account] result login information in AuthAccount ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [HMS-Core/hms-flutter-plugin#138]
**Description**
i get only : 
[ accessToken , openId , displayName , accountFlag: 0 , authorizedScopes: [openid, profile, email] , gender:-1  , carrierId: 0 ];

**Expected behavior**
What you expected to happen？
 [ email , avatarUri , authorizationCode , idToken ]  
any of it != null ;

**Current behavior**
What actually happened？
 [ email , avatarUri , authorizationCode , idToken , unionId , serviceCountryCode , givenName , familyName , account ]  
 all of this are null  .

*
**Environment**
 - Platform: [Flutter]
 - Kit: [huawei_account]
 - Kit Version [6.1.0+302]
 - OS Version [Android 11]
- Platform version (Channel stable, 2.2.2)
- Your Location/Region  : Egypt
**Other**
 what Id Can i use as user ID in my dataBase ?

**Comment by sinan-aktepe** [comment]
Hi @Joseph-Nathan,

You need to create a helper object and set the information you need to obtain from user.
```dart
    final helper = AccountAuthParamsHelper();
    helper
      ..setProfile()
      ..setAccessToken();

    final res = await AccountAuthService.signIn(helper);
```

You can read the detailed explanation here https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/acc-auth-param-helper-0000001050768431

**Comment by Joseph-Nathan** [comment]
Hi @sinan-aktepe  
of course i create a helper object and set the information you need to obtain from user.
and i try also to set all information m it does not work , 
i get AuthAccount like this :
`{accessToken: xxxxxxxxxxxx  , account: null, accountFlag: 0, authorizationCode: null, authorizedScopes: [openid, profile, email], avatarUri: , displayName: Jooo, email: , familyName: , gender: -1, givenName: , idToken: , openId:  xxxxxxxxxxxx , serviceCountryCode: null, unionId: , carrierId: 0}`

helper 
`huaweiAuth..setProfile()..setAccessToken()
      ..setUid()..setEmail()..setCarrierId()..setId()..setIdToken();
    AuthAccount _account ;
    try {
      _account = await AccountAuthService.signIn(huaweiAuth);
........}
`

when i  cancelAuthorization() and reSignIn after Authorize and log in ,
i got screen tell that 
`Unable to access server , please try again`
and when i pop up this screen i got that Exception :
PlatformException(AccAuthService, 2002: , 2002, null)

**Comment by sinan-aktepe** [comment]
Hi @Joseph-Nathan,

We've tested the plugin on an android 10-11 devices and there were no issues. As you can see here, we can obtain the information we've requested for.
![ac1](https://user-images.githubusercontent.com/52041225/140887710-5a6ccedf-0ae5-4732-8618-9619c6517793.PNG)

Please check your app configurations and make sure the HMS installed on the device is up to date.
Also check whether your region is supported or not from here https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/supported-regions-0000001050048968.

If the issue persists, please share the logs.
