### ISSUE TITLE
background handler doesn't work when app is killed

### ISSUE THREAD

**Issue by nmdv24** [HMS-Core/hms-flutter-plugin#139]
when app is killed, push kit can't handle

Huawei p30 
push kit v 5.3.0+304

**Comment by atavci** [comment]
Hello,

In order to handle background messages you need to configure your project according to this document: [Receiving Data Messages When Your App Runs in Background or App Process Is Killed](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/receiving-data-messages-at-killed-state-0000001058199547).

Best.

**Comment by nmdv24** [comment]
I configured, Then Background message 

> Hello,
> 
> In order to handle background messages you need to configure your project according to this document: [Receiving Data Messages When Your App Runs in Background or App Process Is Killed](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/receiving-data-messages-at-killed-state-0000001058199547).
> 
> Best.

I configured this. Then message handled when app runs in background but when app is killed, it is not working

**Comment by atavci** [comment]
Hello again,

Can you provide the following information in order us to find the root cause of this issue:
- Flutter Doctor output
- Flutter embedding version of your project (v1 or v2)
- Code sample that you are using to handle background messages.

As a side note please also check the [example project of the push kit plugin](https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-push/example) to compare with your own project and see if there are any configurations missing or is there any major difference in the code. Note that the example project of the plugin uses the v1 flutter embedding and its configuration is done accordingly.

Best.

**Comment by nmdv24** [comment]
> Hello again,
> 
> Can you provide the following information in order us to find the root cause of this issue:
> 
> * Flutter Doctor output
> * Flutter embedding version of your project (v1 or v2)
> * Code sample that you are using to handle background messages.
> 
> As a side note please also check the [example project of the push kit plugin](https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-push/example) to compare with your own project and see if there are any configurations missing or is there any major difference in the code. Note that the example project of the plugin uses the v1 flutter embedding and its configuration is done accordingly.
> 
> Best.
1.
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-MN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)

2.
Embedding version is v2


3.
await Push.registerBackgroundMessageHandler(PushHandler.hmsBackgroundHandler);


in PushHandler
static hmsBackgroundHandler(hms.RemoteMessage message) {
   print('here');
}

**Comment by nmdv24** [comment]
> > Hello again,
> > Can you provide the following information in order us to find the root cause of this issue:
> > 
> > * Flutter Doctor output
> > * Flutter embedding version of your project (v1 or v2)
> > * Code sample that you are using to handle background messages.
> > 
> > As a side note please also check the [example project of the push kit plugin](https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-push/example) to compare with your own project and see if there are any configurations missing or is there any major difference in the code. Note that the example project of the plugin uses the v1 flutter embedding and its configuration is done accordingly.
> > Best.
> 
> 
> [✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-MN) [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0) [✓] Xcode - develop for iOS and macOS [✓] Chrome - develop for the web [✓] Android Studio (version 2020.3) [✓] VS Code (version 1.59.0) [✓] Connected device (2 available)
> 
> 
> Embedding version is v2
> 
> 
> await Push.registerBackgroundMessageHandler(PushHandler.hmsBackgroundHandler);
> 
> in PushHandler static hmsBackgroundHandler(hms.RemoteMessage message) { print('notification'); Push.localNotification({ HMSLocalNotificationAttr.TITLE: 'DataMessage Received', HMSLocalNotificationAttr.MESSAGE: 'test' }); }


given error when app is killed sometime


 FATAL EXCEPTION: main
E/AndroidRuntime(13612): Process: mn.callpro.onlime, PID: 13612
E/AndroidRuntime(13612): java.lang.NullPointerException
E/AndroidRuntime(13612):        at java.util.Objects.requireNonNull(Objects.java:203)
E/AndroidRuntime(13612):        at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner.c(Unknown Source:9)
E/AndroidRuntime(13612):        at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner.d(Unknown Source:0)
E/AndroidRuntime(13612):        at com.huawei.hms.flutter.push.backgroundmessaging.c.run(Unknown Source:8)
E/AndroidRuntime(13612):        at android.os.Handler.handleCallback(Handler.java:888)
E/AndroidRuntime(13612):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(13612):        at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(13612):        at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(13612):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13612):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(13612):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by recastrodiaz** [comment]
@nmdv24 what was the fix for this? I'm seeing similar errors on 1 app.

**Comment by nmdv24** [comment]
> @nmdv24 what was the fix for this? I'm seeing similar errors on 1 app.

i changed issue detail #140
