### ISSUE TITLE
release包ocr识别失败，debug包正常

### ISSUE THREAD

**Issue by tygm** [HMS-Core/hms-flutter-plugin#14]
手机型号：华为mate8
现象：f5调试或者flutter build apk --debug打的包可以正常识别ocr。但release打包总识别失败，求解
版本信息：
huawei_ml: 2.0.1+300
classpath 'com.huawei.agconnect:agcp:1.3.1.300'

**Comment by tygm** [comment]
排查出来了，是混淆的原因，，现在又发现只能在华为机器上运行正常，其他品牌手机ocr返回空，按照官方说法，ocr依赖hms core，如果没有安装，那么调用ocr会提示安装，但在其他手机上运行并没有提示安装hms core，求解

**Comment by aktug** [comment]
Can you follow these steps https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrate-plugin-0000001052151811
