### ISSUE TITLE
Background data handler when app is killed

### ISSUE THREAD

**Issue by nmdv24** [HMS-Core/hms-flutter-plugin#140]
I want to handle data message without notification When App is killed. 

await Push.registerBackgroundMessageHandler(PushHandler.hmsBackgroundHandler);

it is not working when app is killed without notification

**Comment by atavci** [comment]
Hello,

Do you see the following log after you call the registerBackgroundMessageHandler?

![image](https://user-images.githubusercontent.com/29902904/141280925-b8776fa2-d3e1-4cc2-a672-897893af3ae7.png)

This indicates that the Flutter Background Isolate is registered and ready to receive background messages.

**Comment by nmdv24** [comment]
No only return log after updated to huawei_push 5.3.0+304  
I/flutter ( 9316): rawHandle 1480698356244802974
I/flutter ( 9316): rawCallback -6006078875478554094

**Comment by nmdv24** [comment]
> Hello,
> 
> Do you see the following log after you call the registerBackgroundMessageHandler?
> 
> ![image](https://user-images.githubusercontent.com/29902904/141280925-b8776fa2-d3e1-4cc2-a672-897893af3ae7.png)
> 
> This indicates that the Flutter Background Isolate is registered and ready to receive background messages.


yeah

I/flutter (13047): rawHandle 1480698356244802974
I/flutter (13047): rawCallback -6006078875478554094
I/HMSSDK_HMSBIInitializer(13047): Builder->biInitFlag :false
D/HMSLogger(13047): singleEventMap -> {apiName=setAutoInitEnabled, package=mn.callpro.onlime, cpAppVersion=1.1.25, version=5.3.0.304, platform=Flutter, result=0, costTime=9, service=Cross-Platform, kit=Push, appid=104497665, model=HWMAR, networkType=WIFI, callTime=1636626800932}
I/HmsFlutterPush(13047): BackgroundMessageHandler registered ✔

**Comment by atavci** [comment]
Do you have the following permissions in your AndroidManifest.xml file of your project ?

![image](https://user-images.githubusercontent.com/29902904/141293109-4cc4e41f-f70e-4983-865e-edfeeefa02ba.png)

The following receiver should also configured in the same AndroidManifest.xml file:

![image](https://user-images.githubusercontent.com/29902904/141293285-401f8b62-a0e2-4eb2-8d20-a8854f448380.png)

Please check if these configurations are set. If the error still persist we can investigate it further 👍

**Comment by nmdv24** [comment]
> Do you have the following permissions in your AndroidManifest.xml file of your project ?
> 
> ![image](https://user-images.githubusercontent.com/29902904/141293109-4cc4e41f-f70e-4983-865e-edfeeefa02ba.png)
> 
> The following receiver should also be configured in the same AndroidManifest.xml file:
> 
> ![image](https://user-images.githubusercontent.com/29902904/141293285-401f8b62-a0e2-4eb2-8d20-a8854f448380.png)
> 
> Please check if these configurations are set. If the error still persist we can investigate it further 👍


Still given error
I/FlutterBackgroundRunner(22468): #startBgIsolate
E/AndroidRuntime(22468): FATAL EXCEPTION: main
E/AndroidRuntime(22468): Process: mn.callpro.onlime, PID: 22468
E/AndroidRuntime(22468): java.lang.NullPointerException
E/AndroidRuntime(22468):        at java.util.Objects.requireNonNull(Objects.java:203)
E/AndroidRuntime(22468):        at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner.c(Unknown Source:9)
E/AndroidRuntime(22468):        at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner.d(Unknown Source:0)
E/AndroidRuntime(22468):        at com.huawei.hms.flutter.push.backgroundmessaging.c.run(Unknown Source:8)
E/AndroidRuntime(22468):        at android.os.Handler.handleCallback(Handler.java:888)
E/AndroidRuntime(22468):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(22468):        at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(22468):        at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(22468):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22468):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(22468):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by atavci** [comment]
Hello again,

We have located that the issue is caused by the re-initialization of the background isolate with a null context.

For a quick-fix you can add the line below to the FlutterHmsMessageService.java file on the 132nd line.

`PluginContext.initialize(applicationContext);`

![image](https://user-images.githubusercontent.com/29902904/141429951-5ebefc19-4743-4719-8bb2-b3887136251c.png)

We are sorry if any inconvenience occurred and thank you for pointing out this issue, we will be looking forward to provide a fix on our next update for the Flutter Push Kit Plugin. 

Best.

**Comment by nmdv24** [comment]
> Hello again,
> 
> We have located that the issue is caused by the re-initialization of the background isolate with a null context.
> 
> For a quick-fix you can add the line below to the FlutterHmsMessageService.java file on the 132nd line.
> 
> `PluginContext.initialize(applicationContext);`
> 
> ![image](https://user-images.githubusercontent.com/29902904/141429951-5ebefc19-4743-4719-8bb2-b3887136251c.png)
> 
> We are sorry if any inconvenience occurred and thank you for pointing out this issue, we will be looking forward to provide a fix on our next update for the Flutter Push Kit Plugin.
> 
> Best.

It worked. Thank you for quick support.

**Comment by atavci** [comment]
**Update**
The problem is fixed on the [6.1.0+300](https://pub.dev/packages/huawei_push/versions/6.1.0+300) version of Huawei Push Kit Plugin for Flutter.

**Comment by aktug** [comment]
Thank you so much @atavci
