### ISSUE TITLE
[huawei_ads] Splash ads can't be safeArea

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#143]
**Description**
I tried to test the splash ad using 
`
huawei_ads 13.4.45+308 
`
and it looks can't be customize to be `SafeArea` from the top , which the android status bar makes the pressing on skip button harder 

also some time it hold on `skip 0`  without auto dismissing the ad  . 

my test device is : huawei nova 7i 

many thanks

**Comment by furkansarihan** [comment]
Hi @mustafa-707,

1. You can use `topMargin` with `loadAd` function to set custom top margin for SplashAd.

```
SplashAd splashAd = createSplashAd();
splashAd.loadAd(
    topMargin: 24.0,
    adSlotId: ...,
    orientation: SplashAdOrientation.portrait,
    adParam: AdParam(),
);
```
2. Splash Ads dismissed from Huawei Ads Kit SDK, internally. This Flutter plugin is a wrapper around Native SDK. You can [submit ticket online](https://developer.huawei.com/consumer/en/support/feedback/) to get help about Native SDK.
