### ISSUE TITLE
[huawei_account]  more info about Exception {code: AccAuthService, message: 2005: , details: 2005}

### ISSUE THREAD

**Issue by Joseph-Nathan** [HMS-Core/hms-flutter-plugin#145]
some users get that Exception :
{code: AccAuthService, message: 2005: , details: 2005}

Result Code Constant :
INVALID_IMPORT_USER_DATA

Error Message :
The content of the file to be imported is abnormal and cannot be converted into a user list. 

can you guide me to know what's the problem ?

**Comment by sinan-aktepe** [comment]
Hi @Joseph-Nathan,

We've tried to reproduce the issue you've mentioned but there were no exceptions during test. The code **2005** actually indicates a network error during authorization. You can see the error codes [here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/account-apk-cn-common-error-codes-0000001050048616)

Please check your HMS configurations and make sure the test device has a good network connection. If the issue persists, let us know.

**Comment by Joseph-Nathan** [comment]
@sinan-aktepe  thanks.
the device has recently create Huawei account in the same minute , after 3-5 minute it's work fine ,
thanks bro.
