### ISSUE TITLE
 MissingPluginException(No implementation found for method listen on channel com.huawei.hms.flutter.ads/interstitial/event/849654803)

### ISSUE THREAD

**Issue by juanlabrador** [HMS-Core/hms-flutter-plugin#146]
**Description**
Hi, i start to receive this error when open the app

 MissingPluginException(No implementation found for method listen on channel com.huawei.hms.flutter.ads/interstitial/event/849654803)

I add the splashAd and show correctly, when call main screen, crashed.

**Logs**
I/flutter (13015): EVENT SPLASH: SplashAdLoadEvent.loaded
I/flutter (13015): EVENT SPLASH: SplashAdLoadEvent.dismissed
I/flutter (13015): MissingPluginException(No implementation found for method listen on channel com.huawei.hms.flutter.ads/interstitial/event/849654803)
I/flutter (13015): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
I/flutter (13015): <asynchronous suspension>
I/flutter (13015): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506)
I/flutter (13015): <asynchronous suspension>
I/flutter (13015): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
F/flutter (13015): [FATAL:flutter/fml/message_loop.cc(78)] Check failed: loop != nullptr. MessageLoop::EnsureInitializedForCurrentThread was not called on this thread prior to message loop use.

**Environment**
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale es-419)
    • Flutter version 2.8.0 at /Users/juanlabrador/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/juanlabrador/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • JNY LX2 (mobile) • 94HUT20217000273 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

**Comment by basit192** [comment]
I am facing the same issue with same logs. it is crashing everytime

**Comment by huseyinerenguler** [comment]
Hi @juanlabrador @basit192 

We noticed that this issue only exists after **Flutter 2.8** version. Flutter team made a lot of changes with version 2.8 and this issue occurred due to a situation in the EventChannel structure. 

While the Ads plugin was being developed and tested, the latest version of Flutter was 2.2.3. According to our recent tests, it works in **Flutter 2.5.3 and below**.

We will provide an update which addresses this issue in our next major release. **Please keep an eye on [pub.dev](https://pub.dev/packages/huawei_ads).**

More info:
[Huawei Ads Kit Flutter Plugin](https://pub.dev/packages/huawei_ads)
[Flutter SDK releases](https://docs.flutter.dev/development/tools/sdk/releases)
[What’s New in Flutter 2.8](https://medium.com/flutter/whats-new-in-flutter-2-8-d085b763d181)
