### ISSUE TITLE
_onTokenEvent function do not print the token

### ISSUE THREAD

**Issue by datvimaru50** [HMS-Core/hms-flutter-plugin#148]
**Description**
I follow the the example code of the plugin [huawei_push](https://pub.dev/packages/huawei_push/example). When I push the button to get token, the console print empty string, not the token I want. Although the plugin automatically log the token together with other information, but I want to extract the token only to save to server

**Expected behavior**
`void _onTokenEvent(String event) {
    _token = event;
    showResult("TokenEvent", _token);
  }`
I want the _token to be printed out like this: [TokenEvent] fdkjf5545kkt4546205nhjgkgfggExample_token

**Current behavior**
The log just print:  [TokenEvent]

**Environment**
 - Platform: [Flutter]
 - Kit: [Push]
 - Kit Version [5.3.0]
 - OS Version [Huawei INE-LX2r, Android 9, CPU Hisilicon Kirin 710]
 - Android Studio version (4.2]
 - Your Location/Region (Việt Nam)

**Comment by ozkulbeng** [comment]
Hello @datvimaru50 
After completing the configurations in AppGallery Connect and integrating the Push Kit correctly, you can run the Flutter Push Demo and obtain the token without any problem.
Please make sure you followed the steps in the documentation on Huawei Developers website.
- [Configuring app information in AppGallery Connect](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/config-agc-0000001050178043)
- [Integrating Flutter Push Plugin](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrate-plugin-0000001050418527)

If the problem persists, please do not hesitate to write to us.
Have a nice day!
