### ISSUE TITLE
[huawei_push] Localized push notification support

### ISSUE THREAD

**Issue by fatihergin** [HMS-Core/hms-flutter-plugin#151]
Does Huawei Push Kit's Flutter plugin support localized push notification?

Native platforms are able to handle localization with specified keys like: `title_loc_key`, `body_loc_key` for Android (GCM), and `title-loc-key` and `title-loc-args` for iOS. 

Can HMS Flutter plugin do this **at Flutter level**(e.g. .arb support) without modifying native localization files (`res/strings.xml` for Android, `Localizable.strings` for iOS)

If it's not supported yet, is it in TO-DO list? Or is it not possible due to sth. like a technical restriction?

**Comment by huseyinerenguler** [comment]
Hi @fatihergin 

As you mentioned, the requested feature is not supported yet, but we may consider your suggestion in our future releases. Thank you for your interest in [Huawei Flutter Plugins](https://pub.dev/publishers/developer.huawei.com/packages). 

Please keep an eye on [pub.dev](https://pub.dev/packages/huawei_push) for our next releases.
