### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel I/flutter (10618): com.huawei.flutter.push/token)

### ISSUE THREAD

**Issue by 956569686** [HMS-Core/hms-flutter-plugin#16]
The following MissingPluginException was thrown:
I/flutter (10618): MissingPluginException(No implementation found for method listen on channel
I/flutter (10618): com.huawei.flutter.push/token)
I/flutter (10618): 
I/flutter (10618): When the exception was thrown, this was the stack:
I/flutter (10618): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
I/flutter (10618): <asynchronous suspension>
I/flutter (10618): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
I/flutter (10618): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:542:29)
I/flutter (10618): #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:528:64)

**Comment by aktug** [comment]
Duplicate of #9
