### ISSUE TITLE
requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE

### ISSUE THREAD

**Issue by azhansy** [HMS-Core/hms-flutter-plugin#168]
add:
- used huawei_push: ^6.1.0+300
- update android targetSdkVersion 32  must be present
----------------------------------
**Description**
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
**Logs**   
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at com.huawei.hms.api.b.getErrPendingIntent(HuaweiApiAvailabilityImpl.java:10)
        at com.huawei.hms.common.internal.BaseHmsClient.resolution(BaseHmsClient.java:3)
        at com.huawei.hms.common.internal.BaseHmsClient.checkAvailabilityAndConnect(BaseHmsClient.java:34)
        at com.huawei.hms.common.internal.BaseHmsClient.connect(BaseHmsClient.java:1)
        at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager.connect(HuaweiApiManager.java:21)
        at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager.sendRequest(HuaweiApiManager.java:24)
        at com.huawei.hms.common.internal.HuaweiApiManager.connectAndSendRequest(HuaweiApiManager.java:8)
        at com.huawei.hms.common.internal.HuaweiApiManager.handleMessage(HuaweiApiManager.java:7)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Environment**
 - Platform: Flutter 2.10.1

**Comment by coolleizhu** [comment]
Where do you met this problem? Which plugin are you using, which interface you used?

**Comment by azhansy** [comment]
> Where do you met this problem? Which plugin are you using, which interface you used?

so sorry,
i used plugin: 
[huawei_push: ^6.1.0+300]
when i update my project that update android targetSdkVersion 32, the problem appeared.

**Comment by coolleizhu** [comment]
I tried the push demo and set the targetSdkVersion 32, compileSdkVersion 32.
But it seems working on my device.

Can you tell me which device you used and how you trigger this error?

**Comment by carloserazo47** [comment]
Hi @coolleizhu, please you have to use a device or emulator with Android 12 (SDK 31) or above to reproduce it.
https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

**Comment by huseyinerenguler** [comment]
Hi @azhansy 

Latest version of [huawei_push](https://pub.dev/packages/huawei_push) was released on April 1st. With this version, we fixed some issues for adapting to Android 12. 

According to our recent tests, the issue appears to be resolved. Please test again with the [current version](https://pub.dev/packages/huawei_push/versions). 
If the issue persists, contact us here.

**Comment by azhansy** [comment]
> 

I refer to the latest native sdk and it has been solved, thanks.

**Comment by grapewheel** [comment]
@huseyinerenguler  Hi, this issue occur when using the huawei location flutter plugin 6.4.0+300 too~

**Comment by EArminjon** [comment]
huawei_location: ^6.11.0+301
```dart
FusedLocationProviderClient().requestLocationUpdates(LocationRequest())
```
```
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): Failed to handle method call
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): java.lang.IllegalArgumentException: com.rexel.RexelSE.uat: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:428)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:731)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:718)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.huawei.hms.flutter.location.handlers.FusedLocationMethodHandler.buildLocationIntent(FusedLocationMethodHandler.java:291)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.huawei.hms.flutter.location.handlers.FusedLocationMethodHandler.requestLocationUpdates(FusedLocationMethodHandler.java:138)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.huawei.hms.flutter.location.handlers.FusedLocationMethodHandler.onMethodCall(FusedLocationMethodHandler.java:321)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```


                                        )
