### ISSUE TITLE
INSTALL button in app gallery is disabled ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [HMS-Core/hms-flutter-plugin#169]
**Description**
INSTALL button in app gallery is disabled

**Expected behavior**
INSTALL button in app gallery is work

**Screenshots**
![WhatsApp Image 2022-02-12 at 10 52 54 PM](https://user-images.githubusercontent.com/60202661/154854188-fdec5d85-11bc-4a44-9098-a0ed32c16433.jpeg)

**Environment**
 - Platform: [Flutter]

 - OS Version [e.g. Android 11]
 - Android Studio version (if applicable) [e.g. 4.1]
 - Platform version (2.2.2)
 - Your Location/Region (Egypt) 
 - Device (P40)

**Comment by Xuejiao-Shi** [comment]
hi @Joseph-Nathan Could you please leave your appId? Let me check the info to see the problem.

**Comment by Joseph-Nathan** [comment]
@Xuejiao-Shi  thanks for replay ,
App ID  : 104898859

**Comment by Joseph-Nathan** [comment]
@Xuejiao-Shi  any news !?

**Comment by Xuejiao-Shi** [comment]
@Joseph-Nathan Sorry for the delay, About this issue you are advised to submit a ticket: https://developer.huawei.com/consumer/en/support/feedback/#/
