### ISSUE TITLE
[huawei_iap] Missing else case

### ISSUE THREAD

**Issue by z870248707** [HMS-Core/hms-flutter-plugin#172]
https://github.com/HMS-Core/hms-flutter-plugin/blob/7c4c1e833bffa85101212642c02998898cc9fb67/flutter-hms-iap/android/src/main/java/com/huawei/hms/flutter/iap/listeners/IsEnvReadyFailureListener.java#L45

Should handle the else case and call `mResult.error`.

**Comment by sinemsevilmis** [comment]
Hi @z870248707 ,

We solved this issue with [huawei_iap 6.4.0+301](https://pub.dev/packages/huawei_iap).

Thank you for your interest in our plugins.
