### ISSUE TITLE
Huawei Location plugin - Android 12 support

### ISSUE THREAD

**Issue by carloserazo47** [HMS-Core/hms-flutter-plugin#174]
**Describe the bug**
When building an app using [hms-flutter-location](https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-location) on Android 12 (targetSdkVersion SDK 31) there's a runtime crash because the PendingIntent needs to have a flag for its (im)mutability.

**Expected behavior**
App targeting and compiling SDK 31 or above working.

**Tested on:**
Android, API Level 31, Google Pixel 3a

**Official documentation**
https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

_Please you could also check this PR I made for reference:_
https://github.com/HMS-Core/hms-flutter-plugin/pull/173

**Comment by ozkulbeng** [comment]
Hello @carloserazo47
Huawei Flutter Location plugin is a wrapper around Native SDK and unfortunately, Huawei Location Kit SDK does not support Android 12 yet. For any questions related to Native SDKs please [submit a ticket online](https://developer.huawei.com/consumer/en/support/feedback/).
