### ISSUE TITLE
PlatformException(6003, 6003: , null, null) Error

### ISSUE THREAD

**Issue by uugurbas** [HMS-Core/hms-flutter-plugin#176]
I have tried many things but couldn't find a solution for hours. Here are the settings for my app:
- I tested it on a cloud debugging device with hms
- sha256 key of the appbundle is the same as the key on the project settings page and on the key on the "Upload certificate" section of the app signing tab of my app page. (There is another key that is "App signing certificate", I also entered that key on the project settings sha256 key and downloaded and used the agconnect json file but it didn't work either)
- My product is created and active on product management page.
- Package name on the my app page and on the android manifest page are the same
- agconnect.json file is downloaded on the app folder
- Pubspec.yaml: huawei_iap: ^6.2.0+300
- Buildgradle:
    repositories {
        google()
        mavenCentral()
       maven {url 'https://developer.huawei.com/repo/'}
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.huawei.agconnect:agcp:1.5.2.300'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}
- App level buildgradle:
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.huawei.agconnect'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId deleted on purpose
        minSdkVersion 23
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }
    buildTypes {
        release {
            shrinkResources true
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
        debug {
            signingConfig signingConfigs.release
            debuggable true
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:28.4.2')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'com.google.android.gms:play-services-auth:20.0.1'
    implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
    implementation 'com.huawei.hms:iap:6.3.0.300'

- proguard file:
-ignorewarnings
-keepattributes "Annotation"
-keepattributes Exceptions
-keepattributes InnerClasses
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable
-keep class com.hianalytics.android.**{*;}
-keep class com.huawei.updatesdk.**{*;}
-keep class com.huawei.hms.**{*;}

I think I am confused with the certificate keys on the app signing page. But I used either of them on the project settings page and downloaded and used agconnect.json file but it didn't work.
gradlew signingReport command gives the same sha256 key as the "Upload certificate" on the app signing page.

I constantly getting the error: PlatformException(6003, 6003: , null, null)
Where is the problem?
Thanks

**Comment by Joseph-Nathan** [comment]
me too ,
```{code: AccAuthService, message: 6003: , details: 6003}```
any solution !?

**Comment by sinemsevilmis** [comment]
Hi @uugurbas and @Joseph-Nathan,
