### ISSUE TITLE
onNotificationOpenedApp callback issue

### ISSUE THREAD

**Issue by sunnykinger** [HMS-Core/hms-flutter-plugin#177]
I am testing Pushkit on Pixel phone. I have already installed HMS Core apk and notification show up on system tray. The issue which I am facing is that when I tap on the notification, I do not get callback inside onNotificationOpenedApp and no result using getInitialNotification(). Please help me out.

```
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Future<void> initNotificationListener() async {
    Push.onNotificationOpenedApp.listen((remoteMessage) {
      print("onNotificationOpenedApp: " + remoteMessage.toMap().toString());
    },onError: (e){
      print('error' + ' '+ e.toString());
    });
  }

  void getInitialNotification() async {
    dynamic initialNotification = await Push.getInitialNotification();
    print("getInitialNotification: " + initialNotification.toString());
  }

  @override
  void initState() {
    initNotificationListener();
    getInitialNotification();
    getIntent();
    super.initState();
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }

  void getIntent() async{
    Push.getIntentStream.listen((event) {
      print(event.toString());
    });
  }
}
```

**Comment by huseyinerenguler** [comment]
Hi @sunnykinger 

First of all, **Push.onNotificationOpenedApp**'s return type is Stream<**dynamic**>. 

So, ...**toMap()**... part will throw an error because remoteMessage's type is dynamic;
```
print("onNotificationOpenedApp: " + remoteMessage.toMap().toString());
```
You should write something like this;
```
print("onNotificationOpenedApp: " + remoteMessage.toString());
```
or
```
if (remoteMessage is RemoteMessage) {
    print("onNotificationOpenedApp: " + remoteMessage.toMap().toString());
}
```

If this will not solve your issue, contact us here.

**Comment by sunnykinger** [comment]
> Hi @sunnykinger
> 
> First of all, **Push.onNotificationOpenedApp**'s return type is Stream<**dynamic**>.
> 
> So, ...**toMap()**... part will throw an error because remoteMessage's type is dynamic;
> 
> ```
> print("onNotificationOpenedApp: " + remoteMessage.toMap().toString());
> ```
> 
> You should write something like this;
> 
> ```
> print("onNotificationOpenedApp: " + remoteMessage.toString());
> ```
> 
> or
> 
> ```
> if (remoteMessage is RemoteMessage) {
>     print("onNotificationOpenedApp: " + remoteMessage.toMap().toString());
> }
> ```
> 
> If this will not solve your issue, contact us here.

This thing can cause problem in print, but the real problem is that it is not getting any callback inside onNotificationOpenedApp

In the logs I just noticed this message

`W/FlutterJNI(22162): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.huawei.flutter.push/token. Response ID: 11`

**Comment by sunnykinger** [comment]
I just tried with flutter-hms-push example from this plugin's repository and same issue is there. Notification appears on notification tray, but when I tap on it, callback is not received in onNotificationOpenedApp or getInitialNotification.
I did received callback on getInitialIntent but the intent string was null whereas I sent some data from console as intent uri. 

if you want I can share the project with you and you can replace the agconnect-services file and check.

**Comment by sinemsevilmis** [comment]
Hi @sunnykinger,

I sent notification from console and than pressed the notification to open the app. I have successfully got the result as shown below.

![1](https://user-images.githubusercontent.com/74876610/179976756-e2cd1235-1309-488d-914e-f5e2231a7bed.PNG)

![2](https://user-images.githubusercontent.com/74876610/179977008-5f7f4730-76f2-46d1-a5d9-b079833674d4.PNG)

Please share the project for us to reproduce your issue.

**Comment by ozkulbeng** [comment]
A new version of Ads and Ads Prime

**Comment by innovatoraakash** [comment]
> Hi @sunnykinger,
> 
> I sent notification from console and than pressed the notification to open the app. I have successfully got the result as shown below.
> 
> ![1](https://user-images.githubusercontent.com/74876610/179976756-e2cd1235-1309-488d-914e-f5e2231a7bed.PNG)
> 
> ![2](https://user-images.githubusercontent.com/74876610/179977008-5f7f4730-76f2-46d1-a5d9-b079833674d4.PNG)
> 
> Please share the project for us to reproduce your issue.


I got this response too but how can I get the values of remote message here? All the values are null.
