### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value E/flutter ( 8274): #0      Push.registerBackgroundMessageHandler

### ISSUE THREAD

**Issue by maulanauls** [HMS-Core/hms-flutter-plugin#179]
**Description**
Cannot registerBackgroundHandler in flutter

**Expected behavior**
Just init registerBackgroundHandler just showing error 

**Current behavior**
After running debug [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8274): #0      Push.registerBackgroundMessageHandler

**Screenshots**
E/flutter ( 8274): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8274): #0      Push.registerBackgroundMessageHandler (package:huawei_push/src/cli/push.dart:503:52)
E/flutter ( 8274): #1      MyAppState.initPlatformState (package:uae_spa_management/main.dart:281:48)
E/flutter ( 8274): <asynchronous suspension>

**Logs**
E/flutter ( 8274): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8274): #0      Push.registerBackgroundMessageHandler (package:huawei_push/src/cli/push.dart:503:52)
E/flutter ( 8274): #1      MyAppState.initPlatformState (package:uae_spa_management/main.dart:281:48)
E/flutter ( 8274): <asynchronous suspension>

**Environment**
 - Platform: [Flutter]
 - Kit: [Push]
 - Kit Version [6.3.0+302]
 - OS Version [Huawei Android 12]
 - Android Studio version (if applicable) [4.1]

**Other**
Just initiable for huawei background handler got error like this 

bool backgroundMessageHandler = await Push.registerBackgroundMessageHandler(
      backgroundMessageCallback,
    );
    debugPrint(
      'backgroundMessageHandler registered: $backgroundMessageHandler',
    );

E/flutter ( 8274): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8274): #0      Push.registerBackgroundMessageHandler (package:huawei_push/src/cli/push.dart:503:52)
E/flutter ( 8274): #1      MyAppState.initPlatformState (package:uae_spa_management/main.dart:281:48)
E/flutter ( 8274): <asynchronous suspension>

**Comment by sinemsevilmis** [comment]
Hi @maulanauls

I tried to reproduce your issue and ran our Push kit demo, I have successfully got the result as shown below. I suggest you to try our demo app and if the error still persists, to explore the issue in detail and reproduce your issue, please share a sample code block of your project.

![3](https://user-images.githubusercontent.com/74876610/179992851-dad092a1-7b80-4c60-ba3d-85a695e056ce.PNG)

Thank you for your interest in our plugins.
