### ISSUE TITLE
[huawei_ads] NullPointerException when exiting app

### ISSUE THREAD

**Issue by deakjahn** [HMS-Core/hms-flutter-plugin#18]
When leaving an app that uses the `huawei_ads` package, the following logcat entries appear:

```
E/AndroidRuntime(31463): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
E/AndroidRuntime(31463): 	at com.huawei.hms.flutter.ads.HmsAdsPlugin.resetAdHandlers(HmsAdsPlugin.java:158)
E/AndroidRuntime(31463): 	at com.huawei.hms.flutter.ads.HmsAdsPlugin.onDetachedFromEngine(HmsAdsPlugin.java:413)
E/AndroidRuntime(31463): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/AndroidRuntime(31463): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:260)
E/AndroidRuntime(31463): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:268)
E/AndroidRuntime(31463): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:112)
E/AndroidRuntime(31463): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:360)
E/AndroidRuntime(31463): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:522)
E/AndroidRuntime(31463): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:578)
E/AndroidRuntime(31463): 	at android.app.Activity.performDestroy(Activity.java:8349)
E/AndroidRuntime(31463): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1355)
E/AndroidRuntime(31463): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5668)
```

The error is relatively benign, there is no visible problem apart from these entries.

The solution looks rather simple: add null checks before calling these lines: https://github.com/HMS-Core/hms-flutter-plugin/blob/8b329a4fb1d6a29686fee25741d336ab90eab9ab/flutter-hms-ads/android/src/main/java/com/huawei/hms/flutter/ads/HmsAdsPlugin.java#L158

**Comment by deakjahn** [comment]
This makes the error go away:

    private void setAdHandlers() {
        if (splashMethodChannel != null) splashMethodChannel.setMethodCallHandler(splashMethodHandler);
        if (bannerMethodChannel != null) bannerMethodChannel.setMethodCallHandler(bannerMethodHandler);
        if (rewardMethodChannel != null) rewardMethodChannel.setMethodCallHandler(rewardMethodHandler);
        if (interstitialMethodChannel != null) interstitialMethodChannel.setMethodCallHandler(interstitialMethodHandler);
        if (referrerMethodChannel != null) referrerMethodChannel.setMethodCallHandler(installReferrerMethodHandler);
        if (consentMethodChannel != null) consentMethodChannel.setMethodCallHandler(consentMethodHandler);
        if (consentEventChannel != null) consentEventChannel.setStreamHandler(consentStreamHandler);
    }

    private void resetAdHandlers() {
        if (splashMethodChannel != null) splashMethodChannel.setMethodCallHandler(null);
        if (bannerMethodChannel != null) bannerMethodChannel.setMethodCallHandler(null);
        if (rewardMethodChannel != null) rewardMethodChannel.setMethodCallHandler(null);
        if (interstitialMethodChannel != null) interstitialMethodChannel.setMethodCallHandler(null);
        if (referrerMethodChannel != null) referrerMethodChannel.setMethodCallHandler(null);
        if (consentMethodChannel != null) consentMethodChannel.setMethodCallHandler(null);
        if (consentEventChannel != null) consentEventChannel.setStreamHandler(null);
    }

**Comment by cagdasmer** [comment]
Hello @deakjahn , thank you for reporting this issue.

This is in fact caused by **onDetachedFromActivity** & **onDetachedFromEngine** methods running back to back when leaving an app. The second time **resetAdHandlers** is called, the method tries to set the method call handlers to null for the method channels which were set to null in the first call.

We'll address this issue in our next version. In the meantime, you can apply the solution you shared to prevent the error from occuring again.

**Comment by deakjahn** [comment]
Thanks, I close it then.
