### ISSUE TITLE
Providing Client ID / Secret & API Key programmatically

### ISSUE THREAD

**Issue by deckerst** [HMS-Core/hms-flutter-plugin#180]
To protect credentials, it is advised to download `agconnect-services.json` without including keys, and then provide them via `AGConnectOptionsBuilder`:
> Before downloading the JSON file, you can select Do not include key, so that your keys will not be included in the configuration file. In this case, you need to call the APIs of the AppGallery Connect SDK for manual configuration.

There is [documentation to do so with the AppGallery Connect SDK](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-get-started-android-0000001058210705#section7775132744813=) but I don't see how to achieve this in my project where I simply use the `huawei_map` plugin in Flutter. Is there any API available from the plugin?

**Comment by sinemsevilmis** [comment]
Hi @deckerst,

We added this method with the latest version of [huawei_map](https://pub.dev/packages/huawei_map). 

You can find the method in the link below : 
[](url)https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/huaweimap-initializer-0000001345467525#section1290132731520

Thank you for your interest in our plugins.
