### ISSUE TITLE
[huawei_ads] Feature: ad as widget

### ISSUE THREAD

**Issue by deakjahn** [HMS-Core/hms-flutter-plugin#19]
The Google solution you replicated actually has two approaches: `firebase_admob` provides an overlay where the ads appear, covering up the app screen, fixed to a position somewhere. However, there is an unofficial [`admob_flutter`](https://pub.dev/packages/admob_flutter) package that uses a native view to put the ad inside the widget tree. It goes without saying that, even if you were right in wanting to replicate the original Google behavior completely in the first place, this second approach is way more dev-friendly, providing us with a better way to incorporate ads, not covering up other parts of our UI and making sure the app layout can adapt to the ads present or not.

Do you have any plan, idea or solution to go this way with HMS as well? Even maybe to the point of endorsing said plugin to include HMS as well, or creating a parallel one doing the same?

**Comment by cagdasmer** [comment]
Hello @deakjahn 
One of our main goals when developing these plugins, is to allow the developers who have been using GMS so far, to easily transition to HMS. That is why in our initial version we have chosen this approach.

Even though there is no specific timeline planned for it, we are considering the native view approach for the other ad types in our future releases.

**Comment by deakjahn** [comment]
Actually, I decided I needed it badly enough so I cloned admob_flutter for myself and started to adapt it to HMS. I'll see what comes out of it (I expect it to compile without errors in about 15 minutes now). When done, I'm more than willing to offer it up to the developer of that plugin or anybody else. :-)

**Comment by deakjahn** [comment]
I'm glad to report it already works, tests ads are coming in. Both in the plugin example and my actual app. I already contacted the plugin developer and we'll see how to proceed.

**Comment by aktug** [comment]
That's great @deakjahn 👍
