### ISSUE TITLE
Do you now support iOS? or still don't ?

### ISSUE THREAD

**Issue by Cootla** [HMS-Core/hms-flutter-plugin#192]
**Description**
Description of what the issue is about

**Expected behavior**
What you expected to happen？

**Current behavior**
What actually happened？

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: [e.g. React-Native/Cordova/Flutter/Xamarin]
 - Kit: [e.g. Push/Map/Ads/Account/IAP]
 - Kit Version [e.g. 5.0.3]
 - OS Version [e.g. Android 11]
 - Android Studio version (if applicable) [e.g. 4.1]
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) 

**Other**
Add any other context about the problem here

**Comment by ozkulbeng** [comment]
Hello @Cootla 
In all of HMS cross platform plugins, only Huawei Analytics kit supports iOS. Unfortunately, there is no plan for iOS support. If there is a plan to release in the future, it will be described in the documents.
