### ISSUE TITLE
试图在我的应用程序上实现huawei-ml-body liveness detection时出现错误

### ISSUE THREAD

**Issue by sohsaid** [HMS-Core/hms-flutter-plugin#194]
**Description**
我试图在我的flutter应用程序上实现 huawei-ml-body liveness detection。
到目前为止，我在安卓设备上工作正常。
但当试图在iOS上运行时，它出现了以下问题。

Unhandled Exception: MissingPluginException(No implementation found for method liveness#startDetect on channel huawei.hms.flutter.ml.body.liveness)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      MLLivenessCapture.startDetect (package:huawei_ml_body/src/service/ml_liveness_capture.dart:54:45)
<asynchronous suspension>
#2      _FaceScanState._startRecognition (package:yesso/Screens/auth_screens/profile_info/face_scan.dart:81:40)
<asynchronous suspension>
#3      _FaceScanState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:yesso/Screens/auth_screens/profile_info/face_scan.dart:247:37)
<asynchronous suspension>
2022-06-10 00:36:49.129836-0700 Runner[1258:14444] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
2022-06-10 00:38:28.868954-0700 Runner[1258:14148] [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

**Expected behavior**
3个月以来，我一直在努力使它在iOS设备上运行，但没有办法。

请问有没有办法在iOS设备上运行 huawei-ml-body liveness detection？
有谁能帮助我，给我以下的步骤？

**Environment**
 - Platform: [Flutter]
 - Flutter version [2.10.0]
 - Device: [iPhone 12]
 - Android Studio version [2021.2.1.14-mac]
 - macOS monterey [12.3]
 - Xcode version [13.2]

**Comment by Xuejiao-Shi** [comment]
We did not provide the body liveness detection feature on iOS.
Currently, the iOS version provides the [following functions](https://i.stack.imgur.com/2Upoh.jpg).
For details, kindly check to [this docs](https://developer.huawei.com/consumer/en/doc/development/hiai-Guides/overview-ios-sdk-0000001058762458).

**Comment by sohsaid** [comment]
Thanks, 
Please, when is the body liveness detection feature on iOS will be release  ?

**Comment by Xuejiao-Shi** [comment]
Currently, there is no plan for that, but I have reported this requirement to the product team. If there is a plan to release in the future, it will be described in the documents.
