### ISSUE TITLE
Not sending notification title and body to dart

### ISSUE THREAD

**Issue by yinsee** [HMS-Core/hms-flutter-plugin#2]
The method_channel does not return Push Message's title and body (in my use case, i want to popup the message when app is active) 

The current implementation returns remoteMessage.getData()

```
  @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);
        if (remoteMessage.getData().length() > 0) {
            Utils.sendIntent(PushIntent.DATA_MESSAGE_INTENT_ACTION, PushIntent.DATA_MESSAGE, remoteMessage.getData());
            Log.d(TAG, "Message data received:" + remoteMessage.getData());
        }
   }
```

Require
- Additional / Update the current method channel to return remoteMessage.getNotification() which contains the message 'title', 'body' etc

**Comment by aktug** [comment]
Hi @yinsee ;
Our plugin updates follow the Native SDK updates. In the next version, some new features and improvements will be implemented.

**Comment by yinsee** [comment]
thank you @aktug do u have expected timeline for this?

**Comment by aktug** [comment]
at the end of August
