### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jeancarlos2020** [HMS-Core/hms-flutter-plugin#20]
W/FlutterJNI(23743): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: lyokone/locationstream.

build\huawei_location\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.huawei.hms.flutter.location" to force usage (may lead to runtime failures)

**Comment by rahmicanisin** [comment]
which android sdk version do you use? @jeancarlos2020

**Comment by fuatbakkal** [comment]
@jeancarlos2020 hello. I need to get some information from you to solve this issue.

1. What is your minSdkVersion value in `android/app/build.gradle` file?
![image](https://user-images.githubusercontent.com/12209635/94772760-0017d500-03c3-11eb-8c1a-22f4a6ef3fbe.png)

2. In both `android/app/src/main/AndroidManifest.xml` and `android/app/src/debug/AndroidManifest.xml` files. Are there any XML element exists with `android:minSdkVersion="19"` value? Example below:
	```xml
	<uses-sdk android:minSdkVersion="16"
	          android:targetSdkVersion="28"
	          android:maxSdkVersion="28" />
	```
