### ISSUE TITLE
Huawei Analytics iOS Bug

### ISSUE THREAD

**Issue by gizemgizg** [HMS-Core/hms-flutter-plugin#214]
**Description**
Hello, while it works normally on Huawei device, my app doesn't work on iOS device. It crashes after opening.

**Expected behavior**
What you expected to happen？

**Current behavior**
What actually happened？

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
Error connecting to the service protocol: failed to connect to http://127.0.0.1:58681/y6-7L2IIMn0=/

**Environment**
 - Platform: flutter
 - Kit: Analytics
 - Kit Version huawei_analytics: ^6.5.0+300
 - OS Version [e.g. Android 11]
 - Android Studio version (if applicable) [e.g. 4.1]
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) 

**Other**

**Comment by Xuejiao-Shi** [comment]
Sorry for the late reply. Could you please share the full log obtained when the issues occurred ?

**Comment by huseyinerenguler** [comment]
Hello @gizemgizg 

New version of Huawei Analytics has been released, and it fixes some iOS issues. We tested the latest version of [huawei_analytics](https://pub.dev/packages/huawei_analytics/versions) and it seems your issue has also been solved in this version.

You can learn more from [pub.dev](https://pub.dev/packages/huawei_analytics/) and [our documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050171091). Please do not hesitate to reopen the issue if your problem still persists.
