### ISSUE TITLE
[Huawei Analytics iOS Bug] 

### ISSUE THREAD

**Issue by zhangruiyu** [HMS-Core/hms-flutter-plugin#216]
**Description**
Ios can never be initialized successfully
Ios has no getInstance method at all, so you should determine if Android is calling it
( await _channel.invokeMethod('getInstance', {'routePolicy': routePolicy}); )

**Screenshots**
![image](https://user-images.githubusercontent.com/10591822/180911434-0c1b0e76-595a-4ef6-b136-51081ebf0d40.png)

**Comment by zhangruiyu** [comment]
huawei_analytics: ^6.5.0+300

**Comment by Xuejiao-Shi** [comment]
您好，为了更好的定位这个问题，请提供一份全量日志和初始化代码截图

**Comment by zhangruiyu** [comment]
> 您好，为了更好的定位这个问题，请提供一份全量日志和初始化代码截图

额 你跑example就是啊  ios native端根本没getInstance这个方法

**Comment by byron1655** [comment]
我也碰到了同样的问题
flutter: 3.3.0
huawei_analytics: ^6.5.0+300
ios: 13
以前没有问题，这次升级hms后，一直报异常

**Comment by zhangruiyu** [comment]
> 我也碰到了同样的问题
> flutter: 3.3.0
> huawei_analytics: ^6.5.0+300
> ios: 13
> 以前没有问题，这次升级hms后，一直报异常

反馈了，也没啥用，他们好像改一次，最起码3个月，用华为的applink，有问题，去年反馈的，今年都没改🙂

**Comment by zhangruiyu** [comment]
> 您好，为了更好的定位这个问题，请提供一份全量日志和初始化代码截图

有任何进展？这么简单个事就没人解决？

**Comment by Xuejiao-Shi** [comment]
@zhangruiyu @byron1655 开发者您好，感谢您提供此次报障线索，我们已成功复现此问题，开发团队已在修复中，预计将在本月底发布新版本修复，请关注我们文档对此的更新说明，感谢您的支持和理解。

**Comment by xuxiapu** [comment]
@zhangruiyu @byron1655 开发者您好，我们已修复该问题，请您验收。

**Comment by huseyinerenguler** [comment]
Hello @zhangruiyu 

New version of Huawei Analytics has been released, and it fixes some iOS issues. We tested the latest version of [huawei_analytics](https://pub.dev/packages/huawei_analytics/versions) and it seems your issue has also been solved in this version.

You can learn more from [pub.dev](https://pub.dev/packages/huawei_analytics/) and [our documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050171091). Please do not hesitate to reopen the issue if your problem still persists.
