### ISSUE TITLE
ml kit language when using the application crashes/close

### ISSUE THREAD

**Issue by vqh2602** [HMS-Core/hms-flutter-plugin#217]
**Description**
ml kit language when using the application crashes/close

**Expected behavior**
What you expected to happen？=> return translation

**Current behavior**
What actually happened？=> crash app

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
====================================================================================================
I/ResponseHandler(23515): setup for call: asyncTranslate
I/HMSSDK_HiAnalyticsUtils(23515): Enable Log
I/FormalHASDK(23515): 
I/FormalHASDK(23515): ======================================= 
I/FormalHASDK(23515): FormalHASDK_2.2.0.313
I/FormalHASDK(23515): =======================================
I/HMSSDK_HMSBIInitializer(23515): Builder->biInitFlag :false
D/HMSLogger(23515): HMS Plugin Dotting is Enabled!
I/MLApplication(23515): initialize one para
I/AgConnectInfo(23515): AGConnectServicesConfig: com.huawei.agconnect.config.impl.c@2789f91context: android.app.Application@90d0b29
I/AgConnectInfo(23515): AGConnectServicesConfig: com.huawei.agconnect.config.impl.c@2789f91region: SG
I/AgConnectInfo(23515): AGConnectServicesConfig: com.huawei.agconnect.config.impl.c@2789f91packageName: com.vqh2602.beetranslate.beetranslatehms
I/AgConnectInfo(23515): AGConnectServicesConfig: com.huawei.agconnect.config.impl.c@2789f91packageName: com.vqh2602.beetranslate.beetranslatehms
I/AgConnectInfo(23515): AGConnectServicesConfig: com.huawei.agconnect.config.impl.c@2789f91apiKey: apiKey is secret
I/AgConnectInfo(23515): signature is not null 
I/AgConnectInfo(23515): AGConnectServicesConfig: com.huawei.agconnect.config.impl.c@2789f91certFingerprint: certFingerprint is secret
I/MLApplication(23515): initialize two para
I/MLRemoteTranslator(23515): MLRemoteTranslator init ok, app=_DEFAULT_
I/NetworkKit_CountryCodeBean(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|getVendorCountryCode|41|countryCode by ro.hw.country is: UNKNOWN
I/NetworkKit_CountryCodeBean(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|getSimCountryCode|76|countryCode by SimCountryIso is: 
I/NetworkKit_CountryCodeBean(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|getRegionSettingCountryCode|33|countryCode by system's region setting is: VN
I/NetworkKit_CountryCodeBean(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|getLocaleCountryCode|73|other Android 9.0 upper， get countryCode form Locale.getDefault().getCountry()
I/NetworkKit_CountryCodeBean(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|init|49|get issue_country code from LOCALE_INFO
I/NetworkKit_c(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.c|<init>|85|GrsClient Instance is init, GRS SDK version: 5.0.10.302, GrsBaseInfoParam: app_name=null, reg_country=null, ser_country=VN, issue_country=null
I/NetworkKit_c(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.e.c|a|25|ContextHolder.getAppContext() from GRS is:null
I/NetworkKit_c(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.e.c|a|25|ContextHolder.getAppContext() from GRS is:null
I/NetworkKit_LocalManagerProxy(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.b|a|55|appConfigName isnull
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_hianalytics.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_location.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_logserver.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_mapservice.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_mlkit.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_mlkitservice.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_opendevicesdk.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_opensdkService.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|b|220|service use default countryOrAreaGroup
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_tileserver.json, sucess.
I/NetworkKit_AbstractLocalManager(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.f.a|a|79|load SDK_CONFIG_FILE: grs_sdk_global_route_config_tsms.json, sucess.
I/NetworkKit_GrsRequestInfo(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.g.k.c|e|74|post service list is:{"services":["com.huawei.cloud.mlkitservice","com.huawei.tsms","com.huawei.hms.opendevicesdk","com.huawei.cloud.hianalytics.aspg","com.huawei.cloud.opensdkhianalytics","com.huawei.hms.location","com.huawei.cloud.logservice","com.huawei.cloud.mlkithianalytics","com.huawei.cloud.hianalytics","com.huawei.configserver","com.huawei.maps.app.route"]}
I/NetworkKit_c(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.c$a|call|291|postList is:{*s*r*i*e*"*[*c*m*h*a*e*.*l*u*.*l*i*s*r*i*e*,*c*m*h*a*e*.*s*s*,*c*m*h*a*e*.*m*.*p*n*e*i*e*d*"*"*o*.*u*w*i*c*o*d*h*a*a*y*i*s*a*p*"*"*o*.*u*w*i*c*o*d*o*e*s*k*i*n*l*t*c*"*"*o*.*u*w*i*h*s*l*c*t*o*"*"*o*.*u*w*i*c*o*d*l*g*e*v*c*"*"*o*.*u*w*i*c*o*d*m*k*t*i*n*l*t*c*"*"*o*.*u*w*i*c*o*d*h*a*a*y*i*s*,*c*m*h*a*e*.*o*f*g*e*v*r*,*c*m*h*a*e*.*a*s*a*p*r*u*e*]*
I/NetworkKit_c(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.c$a|call|321|currentServices:{*s*r*i*e*"*[*c*m*h*a*e*.*l*u*.*l*i*s*r*i*e*,*c*m*h*a*e*.*s*s*,*c*m*h*a*e*.*m*.*p*n*e*i*e*d*"*"*o*.*u*w*i*c*o*d*h*a*a*y*i*s*a*p*"*"*o*.*u*w*i*c*o*d*o*e*s*k*i*n*l*t*c*"*"*o*.*u*w*i*h*s*l*c*t*o*"*"*o*.*u*w*i*c*o*d*l*g*e*v*c*"*"*o*.*u*w*i*c*o*d*m*k*t*i*n*l*t*c*"*"*o*.*u*w*i*c*o*d*h*a*a*y*i*s*,*c*m*h*a*e*.*o*f*g*e*v*r*,*c*m*h*a*e*.*a*s*a*p*r*u*e*]*
I/NetworkKit_PLSharedPreferences(23515): pool-3-thread-2 -->NetworkKit_GRS_GrsClient-Init_0|PLSharedPreferences.java|com.huawei.hms.framework.common.PLSharedPreferences|getAll|234|sp size 3
I/NetworkKit_e(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.h.e|a|30|isSpExpire false.
I/NetworkKit_LocalManagerProxy(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.f.b|a|14|appGrs is not null and clear services.
I/NetworkKit_a(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.a|a|41|get unexpired cache localUrl: m*-*p*-*r*.*i*d*a*k*l*u*.*o*
I/NetworkKit_LocalManagerProxy(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.f.b|a|14|appGrs is not null and clear services.
I/NetworkKit_e(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.h.e|a|30|isSpExpire false.
I/NetworkKit_LocalManagerProxy(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.f.b|a|14|appGrs is not null and clear services.
I/NetworkKit_a(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.a|a|41|get unexpired cache localUrl: m*-*p*-*r*.*i*d*a*k*l*u*.*n
I/NetworkKit_LocalManagerProxy(23515): pool-3-thread-2|null|com.huawei.hms.framework.network.grs.f.b|a|14|appGrs is not null and clear services.
I/GRS     (23515): GrsClient grs url is: https://ml-api-dra.ai.dbankcloud.com/
I/GRS     (23515): GrsClient grs url is: https://ml-api-dra.ai.dbankcloud.cn/
E/CountryCodeBean(23515): getVendorCountry=UNKNOWN
E/CountryCodeBean(23515): getSimCountryCode by not enableNetwork, countryCode=
E/CountryCodeBean(23515): getLocaleCountryCode=UNKNOWN
E/CountryCodeBean(23515): getLocaleCountryCode from system language is not reliable.
I/MLApplication(23515): get ky flag: false
E/AndroidRuntime(23515): FATAL EXCEPTION: pool-3-thread-2
E/AndroidRuntime(23515): Process: com.vqh2602.beetranslate.beetranslatehms, PID: 23515
E/AndroidRuntime(23515): java.lang.Error: please set your app apiKey
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.common.MLApplication.getApiKey(MLApplication.java:412)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.common.MLApplication.getAuthorizationToken(MLApplication.java:381)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.p.j.a(RestClientContext.java:12)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.p.l$b.<init>(RestClientRequestHeaders.java:16)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.p.l$b.<init>(RestClientRequestHeaders.java:1)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.cloud.MLRemoteTranslator.c(MLRemoteTranslator.java:14)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.cloud.MLRemoteTranslator.a(MLRemoteTranslator.java:19)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.cloud.MLRemoteTranslator.a(MLRemoteTranslator.java:1)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.cloud.MLRemoteTranslator$a.call(MLRemoteTranslator.java:2)
E/AndroidRuntime(23515): 	at com.huawei.hms.mlsdk.translate.cloud.MLRemoteTranslator$a.call(MLRemoteTranslator.java:1)
E/AndroidRuntime(23515): 	at com.huawei.hmf.tasks.a.j$1.run(Unknown Source:4)
E/AndroidRuntime(23515): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(23515): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(23515): 	at java.lang.Thread.run(Thread.java:764)
I/Process (23515): Sending signal. PID: 23515 SIG: 9
Lost connection to device.

**Environment**
 - Platform: [Flutter]
 - Kit: ML Kit
 - Kit Version:[3.2.0+301]
 - OS Version [Android 10]
 - Android Studio version (if applicable) [4.1]
 - Platform version (>=2.16.1 <3.0.0)

**Other**
when I run the example code. The app is closed immediately
**Code**
// Create an MLRemoteTranslator object.
  MLRemoteTranslator translator =MLRemoteTranslator();

// Create an MLTranslateSetting object to configure translation.
  final setting =MLTranslateSetting.remote(
      sourceText: "How are you",
      sourceLangCode: "en",
      targetLangCode: "ru"
  );

// Get the translation result asynchronously.
  String? result = await translator.asyncTranslate(setting);

**Comment by Xuejiao-Shi** [comment]
> E/AndroidRuntime(23515): java.lang.Error: please set your app apiKey

The log shows that you have not set the apiKey. For details, see check [this link](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/faq-0000001052151253#section285421445712) to set the apiKey.
