### ISSUE TITLE
BannerAds not support on ScrollView

### ISSUE THREAD

**Issue by BeshoyAdelHemaya** [HMS-Core/hms-flutter-plugin#22]
We need BannerAd to be widget like NativeAds to be able to add it inside ScrollView.

**Comment by cagdasmer** [comment]
@BeshoyAdelHemaya Hello,
Even though the when of it is not specified yet, we are considering to include it in our future releases.
Thank you for your feedback.

**Comment by BeshoyAdelHemaya** [comment]
@cagdasmer Thank you for your quick response. It will be great if you do it on the future and feedback me because we already have two Flutter Apps on AppGallery and we need to integrate Ads Kit as soon as possible using BannerAds

**Comment by cagdasmer** [comment]
@BeshoyAdelHemaya Sure thing, keep following us 👍
