### ISSUE TITLE
[huawei_health: ^6.3.0+302] Android 12

### ISSUE THREAD

**Issue by secretmoo35** [HMS-Core/hms-flutter-plugin#222]
**Description**
I'm have project use flutter version 3 and huawei_health: ^6.3.0+302 and set target android version to 32 but there is a build problem.

**Expected behavior**
Can be used with android target version 32 / android version 12

**Logs**
android:exported needs to be explicitly specified for element <service#com.huawei.hms.flutter.health.modules.autorecorder.service.AutoRecorderBackgroundService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Environment**
 - Platform: Flutter
 - Kit: Health
 - Kit: 6.4.0.300
 - OS Version: Android 12

**Comment by asadamatic** [comment]
Experience the same issue.

**Comment by asadamatic** [comment]
I have created a pull request with the solution. Until the developer merges the pull request, you can use from my forked repository like this,

```yaml
huawei_health:
    git:
      url: https://github.com/asadamatic/hms-flutter-plugin
      path: flutter-hms-health

**Comment by secretmoo35** [comment]
> ```yaml
> huawei_health:
>     git:
>       url: https://github.com/asadamatic/hms-flutter-plugin
>       path: flutter-hms-health
>       
> ```

Thanks for help. it worked for me.
