### ISSUE TITLE
How can i publish my app to Huawei App Gallery for Devices that only have HMS ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [HMS-Core/hms-flutter-plugin#226]
i have integrated `[Account Kit , Push Kit ]` with my exist app and ,it work fine for all Hauwei devices .
but when publish in Huawei App Gallery ,it's not available for  Devices that only have HMS .

i get that Review comments form AppGallery Connect : 
`Your App has been approved. ­Notes: Since your App has not been integrated with HMS yet, It cannot be used or displayed on the HMS. If integration of HMS is needed .`

i have been trying for months , and also try `HMS ToolKit` , but it not go well .
any help please ?

**Comment by Xuejiao-Shi** [comment]
Could you please leave your appId? Let me check the info to see the problem.

**Comment by Joseph-Nathan** [comment]
please check it ,
App ID: 104898859
if you can error message or where should i focus that will be great ,

**Comment by Xuejiao-Shi** [comment]
The review team reports that your app cannot be logged in to on the HMS device. You are advised to use the HMS device to test the app. You could send the login failure log or your APK to hmscore@huawei.com for us to check.

**Comment by Xuejiao-Shi** [comment]
hi Joseph-Nathan, We have received your email and contacted the review team confirm that your latest APK submission is all right. Now it is available on the HMS device.

Meanwhile, when we try to test your app, we find that after log in successfully, a game message is displayed on the top of the app. ![image](https://user-images.githubusercontent.com/99166105/188099068-e5fe985b-995a-4aed-b19b-ef4b7abf86ef.png)

If you do not integrate the [game service](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/introduction-0000001050121216) into the app, you are advised to disable the game service API on the AGC console. That way, the pop-up will not be displayed.
![image](https://user-images.githubusercontent.com/99166105/188101033-5f4e8d1b-0bd4-47a7-9088-7ce284ea69ae.png)
