### ISSUE TITLE
HMS Core update failed

### ISSUE THREAD

**Issue by mericgerceker** [HMS-Core/hms-flutter-plugin#236]
**Description**
Hello, I am using Huawei services to get location and show map. I'm doing developer test with HMS Cloud Debugging. After upgrading to Flutter 3.0, my map screen stopped working. Initially it says HMS Core needs to be updated. After that, it cannot perform the update process. The map screen doesn't come up either.

**Expected behavior**
Opening the map screen.

**Current behavior**
The map screen does not open and does not get location.

**Screenshots**
![image](https://user-images.githubusercontent.com/32486067/190421617-3b05ec94-740d-4879-a64f-1d8f76b7b659.png)

**Logs**
-

**Environment**
 - Platform: Flutter
 - Kit: Map, Location
 - Kit Version -
 - OS Version Android 10
 - Android Studio version (if applicable) 4.2
 - Platform version (if applicable) 3.3.1

- huawei_map: ^6.5.0+301
- huawei_location: ^6.0.0+303

**Comment by Xuejiao-Shi** [comment]
Could you please share the log obtained when the issues occurred ?

**Comment by mericgerceker** [comment]
> Could you please share the log obtained when the issues occurred ?

`I/HMSSDK_HiAnalyticsUtils(10846): Enable Log
I/FormalHASDK(10846): 
I/FormalHASDK(10846): ======================================= 
I/FormalHASDK(10846): FormalHASDK_2.2.0.313
I/FormalHASDK(10846): =======================================
I/HMSSDK_HMSBIInitializer(10846): Builder->biInitFlag :false
D/HMSLogger(10846): HMS Plugin Dotting is Enabled!
D/HMSLogger(10846): singleEventMap -> {apiName=[MapUtil]initializeMap, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=3, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311501958}
V/FA      (10846): Logging event: origin=app,name=IstasyonBul_Ekran,params=Bundle[{ga_event_origin(_o)=app, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=2192728400968607566}]
D/FA      (10846): Unable to get advertising id: com.google.android.gms.common.GooglePlayServicesNotAvailableException: com.google.android.gms.measurement.internal.zzka.zza(com.google.android.gms:play-services-measurement@@21.1.0:10)
D/HMSLogger(10846): singleEventMap -> {apiName=hasLocationPermission, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.0.0.303, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Location, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511343}
D/HMSLogger(10846): singleEventMap -> {apiName=setCompassEnabled, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511496}
D/HMSLogger(10846): singleEventMap -> {apiName=setMapToolbarEnabled, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511497}
D/HMSLogger(10846): singleEventMap -> {apiName=setMapType, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511498}
D/HMSLogger(10846): singleEventMap -> {apiName=setMinZoomPreference, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511498}
D/HMSLogger(10846): singleEventMap -> {apiName=setMaxZoomPreference, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511499}
D/HMSLogger(10846): singleEventMap -> {apiName=setZoomControlsEnabled, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511503}
D/HMSLogger(10846): singleEventMap -> {apiName=setLiteMode, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511504}
D/HMSLogger(10846): singleEventMap -> {apiName=setScrollGesturesEnabled, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511505}
D/HMSLogger(10846): singleEventMap -> {apiName=setTiltGesturesEnabled, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511505}
D/HMSLogger(10846): singleEventMap -> {apiName=setZoomGesturesEnabled, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511505}
D/HMSLogger(10846): singleEventMap -> {apiName=setInitialCameraPosition, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.5.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Map, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311511507}
W/HmsMapKit_MapsAdvUtil_48(10846): The class:com.huawei.hms.maps.provider.inhuawei.MapViewDelegate not found.
W/HmsMapKit_MapsAdvUtil_48(10846): The class:com.huawei.hms.maps.provider.inhuawei.MapViewDelegate not found.
I/MapController init(10846): HmsMap.Resumed
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
I/dynamic-api_DynamicModule(10846): 10846-10846|null|com.huawei.hms.feature.dynamic.DynamicModule|queryHMSModuleBundle|114|bundle info: errorCode:2, moduleVersion:0, modulePath:null, loader_version:0, loaderPath:null, armeabiType:0
W/dynamic-api_DynamicModule(10846): 10846-10846|null|com.huawei.hms.feature.dynamic.DynamicModule|queryHMSModuleBundle|145|Failed to get huawei_module_maps bundle info, errcode:2
I/HmsMapKit_HmsUtil_69(10846): get hms apk version  : 0 fallbackVersion : 0
I/HmsMapKit_HmsUtil_21(10846): current api_level is 29
I/HmsMapKit_HmsUtil_177(10846): hmsVersionStr 5.0.1.300
I/HmsMapKit_HmsUtil_205(10846): baseVersion 50001300
I/HMSSDK_HMSPackageManager(10846): enter checkHmsIsSpoof
I/HMSSDK_HMSPackageManager(10846): quit checkHmsIsSpoof cached state: SUCCESS
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HmsMapKit_AvailableAdapter_31(10846): current versionCode:90909999, minimum version requirements: 50001300
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HmsMapKit_HmsUtil_234(10846): Hms is :0
I/HmsMapKit_HmsUtil_243(10846): Hms is avaiable
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
E/HmsMapKit_MapView_119(10846): createDelegate: creator == null
I/HmsMapKit_AbsDeferredLifecycleHelper_28(10846): getCreator: createdFlag = false
I/HmsMapKit_AbsDeferredLifecycleHelper_103(10846): getCreator: execute
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
E/HmsMapKit_MapView_119(10846): createDelegate: creator == null
I/HmsMapKit_MapCreator_16(10846): Making Creator dynamically
I/HmsMapKit_AbsDeferredLifecycleHelper_28(10846): getCreator: createdFlag = true
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
E/HmsMapKit_MapView_119(10846): createDelegate: creator == null
I/HmsMapKit_DynamicUtil_31(10846): isFlyingSkyDevice extChannel: UNKNOWN
I/HmsMapKit_AbsDeferredLifecycleHelper_28(10846): getCreator: createdFlag = true
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
I/HmsMapKit_DynamicUtil_121(10846): isHuaweiPhone : true
E/HmsMapKit_MapView_119(10846): createDelegate: creator == null
I/HmsMapKit_DynamicUtil_105(10846): emuiVersionCodeValue: 21
I/HmsMapKit_AbsDeferredLifecycleHelper_28(10846): getCreator: createdFlag = true
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
E/HmsMapKit_MapView_119(10846): createDelegate: creator == null
I/HmsMapKit_AbsDeferredLifecycleHelper_28(10846): getCreator: createdFlag = true
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
E/HmsMapKit_MapView_119(10846): createDelegate: creator == null
I/HmsMapKit_AbsDeferredLifecycleHelper_28(10846): getCreator: createdFlag = true
I/HmsMapKit_MapView_23(10846): getMapAsync: getDelegate = null
I/HmsMapKit_MapView_60(10846): getMapAsync: mapReadyCallbacks.size = 1
I/PlatformViewsController(10846): Using hybrid composition for platform view: 0
I/dynamic-api_DynamicModule(10846): 10846-21597|null|com.huawei.hms.feature.dynamic.DynamicModule|queryHMSModuleBundle|114|bundle info: errorCode:2, moduleVersion:0, modulePath:null, loader_version:0, loaderPath:null, armeabiType:0
W/dynamic-api_DynamicModule(10846): 10846-21597|null|com.huawei.hms.feature.dynamic.DynamicModule|queryHMSModuleBundle|145|Failed to get huawei_module_dynamicloader bundle info, errcode:2
W/dynamic-api_DynamicModule(10846): 10846-21597|null|com.huawei.hms.feature.dynamic.DynamicModule|a|89|Get loader in HMS failed:Query huawei_module_dynamicloader unavailable, errorCode:2
W/dynamic-api_AssetLoadManager(10846): 10846-21597|null|com.huawei.hms.feature.dynamic.AssetLoadManager|b|170|No module apk in asset path.
W/dynamic-api_DynamicModule(10846): 10846-21597|null|com.huawei.hms.feature.dynamic.DynamicModule|a|146|No available dynamic loader in HMS and asset.
E/HmsMapKit_MapCreator_60(10846): Loading mapRoute dynamically failed, exception is Query huawei_module_dynamicloader unavailable, errorCode:2
E/HmsMapKit_MapCreator_100(10846): getRemoteContext: LoadingException: errcode = 2
E/HmsMapKit_MapCreator_121(10846): get intent successfully.
E/HmsMapKit_MapCreator_141(10846): startUpdateActivity Success.
E/HmsMapKit_MapCreator_30(10846): getRemoteMapContext failed
E/ResMng NATIVE_MSG_FILTER(10846): endActivityTransaction: margin state not match
I/AGConnectInstance(10846): AGConnectInstance#initialize
W/AGConnectInstance(10846): Repeated invoking initialize
E/HmsMapKit_MapView_119(10846): createDelegate: creator == null
I/HmsMapKit_AbsDeferredLifecycleHelper_28(10846): getCreator: createdFlag = true
E/ResMng NATIVE_MSG_FILTER(10846): endActivityTransaction: margin state not match
E/HmsMapKit_AbsDeferredLifecycleHelper_37(10846): getCreator: creator == null, createdFlag = false
V/FA      (10846): Using local app measurement service
V/FA      (10846): Local AppMeasurementService is starting up
V/FA      (10846): Bound to IMeasurementService interface
V/FA      (10846): Connection attempt already in progress
V/FA      (10846): Activity paused, time: 78405003
V/FA      (10846): Connected to service
V/FA      (10846): Processing queued up service tasks: 2
V/FA      (10846): Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=29566, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=2192728400968607566}]
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageNameForMultiService
I/HMSSDK_HuaweiMobileServicesUtil(10846): hmsPackageName is com.huawei.hwid
I/HMSSDK_HMSPackageManager(10846): enter checkHmsIsSpoof
I/HMSSDK_HMSPackageManager(10846): quit checkHmsIsSpoof cached state: SUCCESS
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageNameForMultiService
I/HMSSDK_HuaweiMobileServicesUtil(10846): connect versionCode:90909999
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): current versionCode:90909999, minimum version requirements: 30000100
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): MinApkVersion is disabled.
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageNameForMultiService
I/HMSSDK_HuaweiMobileServicesUtil(10846): hmsPackageName is com.huawei.hwid
I/HMSSDK_HMSPackageManager(10846): enter checkHmsIsSpoof
I/HMSSDK_HMSPackageManager(10846): quit checkHmsIsSpoof cached state: SUCCESS
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageNameForMultiService
I/HMSSDK_HuaweiMobileServicesUtil(10846): connect versionCode:90909999
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): current versionCode:90909999, minimum version requirements: 30000100
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): MinApkVersion is disabled.
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageNameForMultiService
I/HMSSDK_HuaweiMobileServicesUtil(10846): hmsPackageName is com.huawei.hwid
I/HMSSDK_HMSPackageManager(10846): enter checkHmsIsSpoof
I/HMSSDK_HMSPackageManager(10846): quit checkHmsIsSpoof cached state: SUCCESS
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageNameForMultiService
I/HMSSDK_HuaweiMobileServicesUtil(10846): connect versionCode:90909999
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): current versionCode:90909999, minimum version requirements: 30000100
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageName
I/HMSSDK_HMSPackageManager(10846): MinApkVersion is disabled.
I/HMSSDK_HwLocation_LocationClientImpl(10846): |0891ed47-1f89-46c3-af92-a46f2fb68566|checkLocationSettings
I/LiteSDKProxy(10846): [2022-09-16 08:58:41.163 I/LITE_SDK-LiteSDKProxy] is system app
I/HMSSDK_LiteSDKProxy(10846): isHMSEnable:true
I/HMSSDK_HMSPackageManager(10846): Enter getHMSPackageNameForMultiService
I/HMSSDK_HuaweiApi(10846): No setInnerHms, hms pkg name is com.huawei.hwid
I/HMSSDK_HuaweiApi(10846): sendRequest
I/HMSSDK_HuaweiApi(10846): isConnected:true.
I/HMSSDK_BaseHmsClient(10846): getAdapter:isInner:false, mInnerBinderAdapter:null, mOuterBinderAdapter:com.huawei.hms.adapter.BinderAdapter@cd47ab1
I/HMSSDK_RequestManager(10846): addToConnectedReqMap
I/HMSSDK_HmsClient(10846): post msg api_name:location.checkLocationSettings, app_id:105237681|, pkg_name:com.pharos.aytemiz, sdk_version:60400303, session_id:*, transaction_id:105237681ttings20220916085841174903193, kitSdkVersion:60400300, apiLevel:1
I/HMSSDK_BaseAdapter(10846): In constructor, activityWeakReference is java.lang.ref.WeakReference@9859155, activity is com.pharos.aytemiz.MainActivity@3cad273
I/HMSSDK_BaseAdapter(10846): in baseRequest + uri is :location.checkLocationSettings, transactionId is : 105237681ttings20220916085841174903193
I/HMSSDK_PendingResultImpl(10846): init uri:location.checkLocationSettings
I/HMSSDK_PendingResultImpl(10846): setResultCallback
W/libEGL  (10846): EGLNativeWindowType 0x7b58dbd010 disconnect failed
D/mali_winsys(10846): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/libEGL  (10846): call to OpenGL ES API with no current context (logged once per thread)
I/HMSSDK_PendingResultImpl(10846): setResult:0
W/Gralloc3(10846): allocator 3.x is not supported
D/mali_winsys(10846): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/HwViewRootImpl(10846): removeInvalidNode all the node in jank list is out of time
I/HMSSDK_BaseAdapter(10846): api is: location.checkLocationSettings, resolution: null, status_code: 0
I/HMSSDK_BaseAdapter(10846): baseCallBack.onComplete
I/HMSSDK_HmsClient(10846): receive msg status_code:0, error_code:0, api_name:location.checkLocationSettings, app_id:105237681|, pkg_name:com.pharos.aytemiz, session_id:*, transaction_id:105237681ttings20220916085841174903193, resolution:null
I/HMSSDK_TaskApiCall(10846): doExecute, uri:location.checkLocationSettings, errorCode:0, transactionId:null
I/HMSSDK_HwLocation_CheckLocationSettingsTaskApiCall(10846): |0891ed47-1f89-46c3-af92-a46f2fb68566|doExecute
I/HMSSDK_ServiceErrorCodeAdaptor(10846): set task by error code:0,reason:SUCCESS
I/HMSSDK_RequestManager(10846): removeReqByTransId
D/HMSLogger(10846): singleEventMap -> {apiName=checkLocationSettings, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.0.0.303, platform=Flutter, result=0, costTime=182, service=Cross-Platform, kit=Location, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311521336}
D/HMSLogger(10846): singleEventMap -> {apiName=FusedLocationStreamHandler.onListen, package=com.pharos.aytemiz, cpAppVersion=6.2.1, version=6.0.0.303, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Location, appid=105237681, model=HWLIO, networkType=WIFI, callTime=1663311521352}`

**Comment by Xuejiao-Shi** [comment]
Thank you for providing the information regarding this issue. 

This problem occurs because the HMS Core version on Cloud Debugging is 9.9.9.9999,  which cause the HMS Core update failed. You are advised to use a real Huawei device for debugging. If you do not have a real device, you can uninstall the HMS Core APK from the  Cloud Debugging and download the HMS Core APK from Huawei AppGallery . After completing the above steps, you can retest, the problem should be solved.

**Comment by mericgerceker** [comment]
> Thank you for providing the information regarding this issue.
> 
> This problem occurs because the HMS Core version on Cloud Debugging is 9.9.9.9999, which cause the HMS Core update failed. You are advised to use a real Huawei device for debugging. If you do not have a real device, you can uninstall the HMS Core APK from the Cloud Debugging and download the HMS Core APK from Huawei AppGallery . After completing the above steps, you can retest, the problem should be solved.

Thank you very much for your reply. Unfortunately, I can't test from the live device at the moment.

As you said, I removed the updates of the HMS Core app and updated it from the market. When I got to the map screen, it asked me to update it again. While performing this operation, I got the first error I got.

**Comment by Xuejiao-Shi** [comment]
Thank you for your feedback. Can you provide a detailed log of the failure to update the HMS Core APK after it is uninstalled and reinstall?

**Comment by mericgerceker** [comment]
> Thank you for your feedback. Can you provide a detailed log of the failure to update the HMS Core APK after it is uninstalled and reinstall?

Hello,

With the method you suggested above, I was able to run my application without any problems. Thank you very much for your support.
