### ISSUE TITLE
扫码 部分设备 图像出现上下倒置

### ISSUE THREAD

**Issue by fengxinsen** [HMS-Core/hms-flutter-plugin#237]
**Description**
Description of what the issue is about

**Expected behavior**
What you expected to happen？

**Current behavior**
What actually happened？

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: [e.g. React-Native/Cordova/Flutter/Xamarin]
 - Kit: [e.g. Push/Map/Ads/Account/IAP]
 - Kit Version [e.g. 5.0.3]
 - OS Version [e.g. Android 11]
 - Android Studio version (if applicable) [e.g. 4.1]
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) 

**Other**
Add any other context about the problem here

**Comment by Xuejiao-Shi** [comment]
您好，麻烦提供集成的SDK版本号、设备型号、复现问题的步骤或者截图，以及详细的日志信息，以便我们可以更快定位问题。

**Comment by fengxinsen** [comment]
implementation 'com.huawei.hms:scanplus:2.7.0.302'
设备（STONEOIM WE380）预览图像上下倒置
设备（MatePad 10.4）正常
步骤按照文档来的。
猜测是否是Camera Rotation的问题

**Comment by Xuejiao-Shi** [comment]
您好，请提供以下信息：1.出现问题的手机设置截图 2.录屏 3.日志。可以发送至hmscore@huawei.com邮箱，附上issue链接，谢谢！

**Comment by ozkulbeng** [comment]
Hello @fengxinsen 
According to your statement, you are having a trouble while using `com.huawei.hms:scanplus` which is not a dependency published as a Flutter plugin. 
For your Native Scan Kit related issues, please check this [repository](https://github.com/HMS-Core/hms-scan-demo/issues).
