### ISSUE TITLE
LocalNotification empty DATA attribute

### ISSUE THREAD

**Issue by p3pp8** [HMS-Core/hms-flutter-plugin#239]
Message coming by tapping on a local notification has always an empty data object even when the local notification is built with a value defined in DATA attribute (HMSLocalNotificationAttr.DATA).

**Comment by xuxiapu** [comment]
Thank you for your question. Did you send the notification through Huawei Push kit? If yes, pls provide the message body of the push request.

**Comment by p3pp8** [comment]
Yes i use push kit and it’s a local notification built in app filling DATA attribute. When i tap on the notification i aspect to find what i’ve put inside DATA but i only find the notification body inside an object named extras with an empty data object. I’ll try to post some more details…

**Comment by huseyinerenguler** [comment]
Hi @p3pp8 

When I use our demo I see that everything is working properly. I send a local notification with data and tap the notification then I see my data correctly. If the problem persists, you can share a small project where we can reproduce the issue.

![Screenshot](https://user-images.githubusercontent.com/26097484/213430505-d8d198ad-af4b-425b-9451-a9098c9a1529.png)
