### ISSUE TITLE
backgroundMessageHandler  not registered and crash my app when i receive notification in background

### ISSUE THREAD

**Issue by rochelryu** [HMS-Core/hms-flutter-plugin#240]
**Description**
I'm using version 2 of flutterEmbedding, I've done the necessary configuration to receive the notification in foreground and it works, I've implemented the logic to receive the message in background but it still doesn't work. and when I receive a notification while my application is in background, the application crashes and disconnects from the simulation.
I use :
huawei_push: ^6.5.0+300
Flutter (Channel stable, 3.3.1)
 

**Expected behavior**
I would like to receive notifications when my application is in the background

**Current behavior**
if the application is in the background, it crashes as soon as I receive a notification.

**Screenshots**
<img width="871" alt="Capture d’écran 2022-10-03 à 14 24 49" src="https://user-images.githubusercontent.com/38214577/193607244-12706dc9-24f4-4457-b9f0-a12cff61ed6f.png">
<img width="802" alt="Capture d’écran 2022-10-03 à 14 25 22" src="https://user-images.githubusercontent.com/38214577/193607265-ef53f936-d813-4998-a097-a9378804c005.png">
<img width="802" alt="Capture d’écran 2022-10-03 à 14 25 41" src="https://user-images.githubusercontent.com/38214577/193607273-98b075a6-ba2f-4717-99dc-4c5df619870c.png">
<img width="893" alt="Capture d’écran 2022-10-03 à 14 26 25" src="https://user-images.githubusercontent.com/38214577/193607278-d185c655-1212-414b-8d02-62c6299c800b.png">
<img width="1270" alt="Capture d’écran 2022-10-03 à 14 38 15" src="https://user-images.githubusercontent.com/38214577/193607285-9345608b-fb49-408c-a59a-15863a427d67.png">

in my logic code Main.dart
`huawei.Push.onMessageReceivedStream.listen(_onHmsMessageReceived, onError: _onHmsMessageReceiveError);

            bool backgroundMessageHandler = await huawei.Push.registerBackgroundMessageHandler(_onHmsMessageReceived);
            print("backgroundMessageHandler registered: $backgroundMessageHandler");`

`void _onHmsMessageReceived(huawei.RemoteMessage remoteMessage) async {
    // Called when a data message is received
    final data = remoteMessage.data ?? "";
    print("data");
    print("notification");
    print(jsonDecode(data));
  }`

**Logs**
I/FlutterBackgroundRunner(19330): #startBgIsolate
I/BackgroundMessagingService(19330): Background Service has not started yet, datas will be queued.
W/FlutterJNI(19330): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(19330): FlutterJNI.prefetchDefaultFontManager called more than once
I/ResourceExtractor(19330): Found extracted resources res_timestamp-5-1664807735886
W/FlutterJNI(19330): FlutterJNI.init called more than once
I/FlutterBackgroundRunner(19330): Starting Background Runner
W/MediaSessionCompat(19330): Couldn't find a unique registered media button receiver in the given context.
D/Android: [Awesome Notifications](19330): Awesome Notifications plugin attached to Android 29 (AwesomeNotificationsPlugin:125)
D/Android: [Awesome Notifications](19330): Awesome Notifications attached to engine for Android 29 (AwesomeNotificationsPlugin:105)
I/BlockMonitor(19330): dispatchingThrewException In MainThread
D/AndroidRuntime(19330): Shutting down VM
I/QarthLog(19330): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(19330): [PatchStore] create disable file for com.shouz.app uid is 10342
E/AndroidRuntime(19330): FATAL EXCEPTION: main
E/AndroidRuntime(19330): Process: com.shouz.app, PID: 19330
E/AndroidRuntime(19330): java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(19330): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:421)
E/AndroidRuntime(19330): 	at java.lang.String.valueOf(String.java:2924)
E/AndroidRuntime(19330): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(19330): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:175)
E/AndroidRuntime(19330): 	at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner.lambda$startBgIsolate$0$FlutterBackgroundRunner(FlutterBackgroundRunner.java:130)
E/AndroidRuntime(19330): 	at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/AndroidRuntime(19330): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(19330): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(19330): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(19330): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(19330): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19330): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(19330): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
I/Process (19330): Sending signal. PID: 19330 SIG: 9
Lost connection to device.

**Environment**
 - huawei_push: ^6.5.0+300
 - Flutter (Channel stable, 3.3.1)
 - macOS 12.6

**Comment by xuxiapu** [comment]
![image](https://user-images.githubusercontent.com/114389983/194686258-be4e8a9e-47fe-4ea9-88f0-94a42e0dfa93.png)
From the log, it is a null pointer exception. Please refer to the [link](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/receiving-data-messages-at-killed-state-0000001058199547) for background message processing solutions.

**Comment by rochelryu** [comment]
j'ai finis par régler, l'ecoute du background doit se faire uniquement après que le token soit rendu disponible dans l'application. Donc il faut faire attention à initialiser l'écoute du background après avoir reçu le token.

**Comment by bkleineibst** [comment]
I am also seeing this issue. I have tried to register for background messages only after the token is received, but this doesn't seem to have made any difference. I don't see this issue when testing on Cloud Debugging, only in production.

After receiving the token I do the following:
![image](https://github.com/HMS-Core/hms-flutter-plugin/assets/45809970/fd92fe95-1f27-40ba-9b9b-9fc389b25490)

@rochelryu Is this what you did to get it to work?
