### ISSUE TITLE
Push.onNotificationOpenedApp not calling

### ISSUE THREAD

**Issue by Ruhasi** [HMS-Core/hms-flutter-plugin#243]
I have implemented huawei_push: ^6.5.0+300. when I am getting the notification for the foreground, onMessageReceivedStream method calls as expected. but the app is in the background and when I click on the notification that was received in the system tray app is opening but the onNotificationOpenedApp function not calling. 

![image](https://user-images.githubusercontent.com/27941774/194791294-cdb2b3ab-5d9d-405f-b0fe-d8cc42a312d0.png)

**Comment by xuxiapu** [comment]
Maybe this is not the official website demo. You can refer to this [document](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/listen-notif-message-0000001057481400) and try it through the [official website demo](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/flutter-sdk-download-0000001050186157-V1).

**Comment by xuxiapu** [comment]
@Ruhasi Maybe this is not the official website demo. You can refer to this [document](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/listen-notif-message-0000001057481400) and try it through the [official website demo](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/flutter-sdk-download-0000001050186157-V1).
