### ISSUE TITLE
handle background notifications

### ISSUE THREAD

**Issue by BryanYin** [HMS-Core/hms-flutter-plugin#249]
**Description**
Hi,

I'm developing an app integrates [HuanXin](https://www.easemob.com). Now I'm getting stuck dealing with background(App killed) notifications.

According to the docs, `Push#registerBackgroundMessageHandler` only works for **Data Messages**, but I have consulted with HuanXin, their system can only send **Notification Messages** when app is in BG or killed.

**Expected behavior**
I want to understand,
1. HuanXin can only send **Notification Messages**  when app is in BG or killed, is this true?
2. if 1 is true, then how to handle **Notification Messages** when app is in BG or killed?

I'm new to Flutter, thank you for your help in advance!

**Environment**
 - Platform: see below output from flutter doctor.
 - Kit: Push
 - Kit Version: 6.5.0+300
 - OS Version: HMS
 - Your Location/Region: China

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5 21G72 darwin-arm, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by xuxiapu** [comment]
@BryanYin Thank you for your feedback. When integrating Huanxin, whether the application is in the foreground or background, or the process is killed, it can be pushed. You can view the [document](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/android-basic-receivemsg-0000001087370610) to learn more.

**Comment by BryanYin** [comment]
Hi @xuxiapu , thank you for your reply! But i"m developing Flutter App, and referring to the documentation [here](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/receiving-data-messages-at-killed-state-0000001058199547), in which said that [onMessageReceivedStream](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/push-class-0000001050274604-V1#section103011319363) won't work when App is in BG or get killed.

Am I miss something?

BTW, I just tested `onMessageReceivedStream` with following code:
```
    Push.onMessageReceivedStream.listen((rmtMsg) {
      TcxLog.info("BBBBBB" + rmtMsg.toMap().toString());
    }, onError: (error) {
      TcxLog.error("onMessageReceivedStream Error: " + (error.message ?? ""));
    });
```

The logs doesn't print even if my App is active in foreground...pls suggest...

**Comment by xuxiapu** [comment]
@BryanYin Thank you for your feedback. You can put forward relevant demands to Huanxin and support it through Huanxin.

**Comment by BryanYin** [comment]
Hi @xuxiapu , I have resolved this issue by using `Push.onNotificationOpenedApp` and `Push#getInitialNotification`, thanks for your attention!
