### ISSUE TITLE
Huawei Map always showed in top of stack widget

### ISSUE THREAD

**Issue by dayron9110** [HMS-Core/hms-flutter-plugin#253]
#206 

Please reopen that issue because still in the last version of package:

I upload a video of the error:

https://user-images.githubusercontent.com/32872254/198695314-1e157adc-e3fe-498c-895a-ac33ce329b07.mp4

![image](https://user-images.githubusercontent.com/32872254/198696289-6eff4b56-5e83-4fbe-98c1-084ab266d829.png)

I am using the latest version of the Huawei Maps library:  6.5.0+301

**Comment by xuxiapu** [comment]
@dayron9110 Hi，How are the icons on the left side of the map displayed? Is the UI control added in the XML layout file? Can you provide the relevant documents? It is better to have a simple Demo.
![20221107-145158(WeLinkPC)](https://user-images.githubusercontent.com/114389983/200252744-0ecb5a3e-390c-4eb5-8966-25dde9de0a8c.png)

**Comment by dayron9110** [comment]
@xuxiapu thanks for replying, please watch the video I uploaded, my implementation is easier.

![image](https://user-images.githubusercontent.com/32872254/200691891-67c2e872-8d8a-4ae7-bd44-ae570df8143e.png)

**Comment by xuxiapu** [comment]
@dayron9110 Dear developer, please answer the following questions:

1. Your question is why the UI controls on the left cannot be displayed?

2. Is the UI control on the left the Marker mark of the map?

3. Would you please provide a simple Demo? I still don't understand your problem and what the error is.

**Comment by dayron9110** [comment]
@xuxiapu Thanks for answering but I'll clarify something, my first problem is with the controls on the right of the map:
These controls are specific to the map and are not added by me manually. 

When opening the map for the first time these controls are not displayed, I have to exit and re-enter the map for it to display correctly.

![image](https://user-images.githubusercontent.com/32872254/200935794-7b4bcd78-0d59-4c7c-8761-358e18d38f95.png)

Also, the questions you are asking are from another related issue from another developer.

Please check the video that I uploaded.

I'll be uploading a demo with the problems I'm having with the map component later

**Comment by dayron9110** [comment]
@xuxiapu  here the demo project:
https://github.com/dayron9110/huawei_map_demo

I also have another problem opening the map and trying to go to another page:


https://user-images.githubusercontent.com/32872254/201193249-26d05bc5-8eaf-4942-8890-54f82ed7a1ef.mp4

**Comment by dayron9110** [comment]
@xuxiapu could you see something?

**Comment by dayron9110** [comment]
News?

**Comment by dayron9110** [comment]
@xuxiapu news?

**Comment by dayron9110** [comment]
This workaround worked for me:

```
    override fun onCreate(savedInstanceState: Bundle?) {
        intent.putExtra("background_mode", "transparent");//TODO Huawei fix map
        super.onCreate(savedInstanceState);
        MapsInitializer.initialize(applicationContext, Renderer.LATEST, this)
    }

    //TODO Huawei fix map
    override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
        // We do not actually need a transparent TextureView.
        flutterTextureView.isOpaque = true;
        super.onFlutterTextureViewCreated(flutterTextureView);
    }
```
Thanks to @ppiatkowski-here

**Comment by armangz** [comment]
@dayron9110  Do you have apk demo where we can reply the issue?

**Comment by dayron9110** [comment]
Yes, the problem is still be done, I shared a workaround in my last comment

**Comment by armangz** [comment]
But can you share with us an apk with this problem to check what is happening with the library?

**Comment by dayron9110** [comment]
@armangz here the apk:
[Link](https://drive.google.com/file/d/1ez5GpWaT7pM4R_kF9Z2CJ3nlS7nbao6T/view?usp=share_link)

**Comment by armangz** [comment]
Thank we know check in our side

**Comment by dayron9110** [comment]
News?

**Comment by peura-toni** [comment]
This issue has been resolved with the latest version. Try [6.9.0+300](https://pub.dev/packages/huawei_map/versions/6.9.0+300).
