### ISSUE TITLE
HMS Scan Customized view is not a widget

### ISSUE THREAD

**Issue by sparkmobi** [HMS-Core/hms-flutter-plugin#254]
**Description**
the HMS CustomizedView is not widget, it is just calling a ready made HMS customized view by HMS
so nobody can add any customized to it as animation or change its style 

**Expected behavior**
the customized view should be something like this 
```
Container(
  width: 250, // custom wrap size
  height: 250,
  child: ScanView(
    controller: controller,
// custom scan area, if set to 1.0, will scan full area
    scanAreaScale: .7,
    scanLineColor: Colors.green.shade400,
    onCapture: (data) {
      // do something
    },
  ),
),
```

**Current behavior**
it is just a bridge method call which doesnt make any difference, it is just same as the default huawei scan view

```
 HmsCustomizedView.startCustomizedView(CustomizedViewRequest(
      scanType: HmsScanTypes.AllScanType,
      continuouslyScan: false,
      isFlashAvailable: true,
      flashOnLightChange: false,
      enableReturnBitmap: false,
      customizedCameraListener: (ScanResponse response) {
        pause();
        setState(() {
          responseList.add(response);
        });
        resume();
      },
```

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: Flutter
 - Kit: Scan
 - Kit Version 2.1.0+300
 - OS Version Android 12 & ios 16

**Other**
Add any other context about the problem here

**Comment by sinemsevilmis** [comment]
Hi @sparkmobi,

The customizations you can make in the Customized View are limited, for example, you can change the height or width of the scanning area. Please check this [link](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/customized-view-0000001054199931) for detailed information about `Customized View`.

To use huawei_scan as a widget, or as an inline camera, you may implement your own camera, or use a 3rd party plugin that offers camera as a widget, and process the camera output using `decodeWithBitmap`, `decodeMultiSync`, or `decodeMultiAsync` methods of the Huawei Scan Flutter Plugin. Please check this [link](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/hms-scan-utils-0000001054150792-V1#EN-US_TOPIC_0000001054150792__section18317616142618) for detailed information about `decodeWithBitmap` API.
