### ISSUE TITLE
UPDATE flutter-hms-push 6.7.0+300

### ISSUE THREAD

**Issue by hellohejinyu** [HMS-Core/hms-flutter-plugin#255]
Please UPDATE flutter-hms-push 6.7.0+300.

https://developer.huawei.com/consumer/cn/forum/topic/0204950963785910294?fid=18

Because Xiaomi will reject the app application.

**Comment by xuxiapu** [comment]
Dear developer，
Please check whether the first method is used for automatic initialization. If it is,the second method is recommended, call it after the user agrees to the privacy agreement.
Document link:
https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/android-client-dev-0000001050042041#section13546121751811

**Comment by hellohejinyu** [comment]
> Dear developer， Please check whether the first method is used for automatic initialization. If it is,the second method is recommended, call it after the user agrees to the privacy agreement. Document link: https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/android-client-dev-0000001050042041#section13546121751811

I use the flutter version, I did not find any scenarios for manual initialization

**Comment by lee3219237** [comment]
Please UPDATE flutter-hms-push 6.7.0+300.

**Comment by huseyinerenguler** [comment]
Hi @hellohejinyu 

Huawei Push Kit 6.7.0+300 has been released. Please check [pub.dev](https://pub.dev/packages/huawei_push).
