### ISSUE TITLE
huawei_scan app crashed on code scan

### ISSUE THREAD

**Issue by BombeyR** [HMS-Core/hms-flutter-plugin#26]
Using the huawei_scan flutter plugin causes the entire app to crash after scanning is complete or on back button pressed.
here is the log

E/HaLogProvider(31415): forbiddenHiLog openHa = false
E/HaLogProvider(31415): forbiddenHiLog.getVenderCountry=meafnaf
E/HaLogProvider(31415): forbiddenHiLog openHa = false
D/ScanSize(31415): top:499scanSizeHeight783height:1920
I/ScankitDecode(31415): sdk version 1.2.2.300APK
I/ScankitDecode(31415): ScanCode successful
I/CaptureHandler(31415): scan successful
I/c       (31415): result onResult
I/c       (31415): result callback end: pauseStatusfalse
I/OnResultCallbackDelegat(31415): result callback sdk continueScanfalse
I/OnResultCallbackDelegat(31415): result callback sdk continueScanfalse
D/HMSLogger(31415): singleEventMap -> {result=0, apiName=CustomizedViewActivity.customizedView, package=kawi.healthpal.huawei, costTime=96659, service=FlutterScan, appid=102998471, model=HWJKM-H, cpAppVersion=1.0.0, networkType=4G, version=1.2.2.300, callTime=1601912706174}
D/CameraManager(31415): CameraManager::requestPreviewFrame PREVIEW_ONE_SHOT
D/HMSLogger(31415): singleEventMap -> {result=0, apiName=remoteView.onPause, package=kawi.healthpal.huawei, costTime=10, service=FlutterScan, appid=102998471, model=HWJKM-H, cpAppVersion=1.0.0, networkType=4G, version=1.2.2.300, callTime=1601912706246}
D/ZrHung.AppEyeUiProbe(31415): stop checker.
E/HaLogProvider(31415): forbiddenHiLog openHa = false
E/HaLogProvider(31415): forbiddenHiLog.getVenderCountry=meafnaf
E/HaLogProvider(31415): forbiddenHiLog openHa = false
D/ScanSize(31415): top:499scanSizeHeight783height:1920
I/ScankitDecode(31415): sdk version 1.2.2.300APK
W/ealthpal.huawe(31415): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
I/MethodHandler(31415): No request code found
D/AndroidRuntime(31415): Shutting down VM
W/ealthpal.huawe(31415): Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
E/ealthpal.huawe(31415): [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime(31415): FATAL EXCEPTION: main
E/AndroidRuntime(31415): Process: kawi.healthpal.huawei, PID: 31415
E/AndroidRuntime(31415): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=14, result=-1, data=Intent { (has extras) }} to activity {kawi.healthpal.huawei/kawi.healthpal.huawei.MainActivity}: java.lang.NullPointerException
E/AndroidRuntime(31415): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
E/AndroidRuntime(31415): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
E/AndroidRuntime(31415): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(31415): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(31415): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(31415): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
E/AndroidRuntime(31415): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime(31415): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(31415): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(31415): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31415): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(31415): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AndroidRuntime(31415): Caused by: java.lang.NullPointerException
E/AndroidRuntime(31415): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/AndroidRuntime(31415): 	at com.huawei.hms.flutter.iap.MethodCallHandlerImpl.onActivityResult(MethodCallHandlerImpl.java:234)
E/AndroidRuntime(31415): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(31415): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(31415): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(31415): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:584)
E/AndroidRuntime(31415): 	at android.app.Activity.dispatchActivityResult(Activity.java:7797)
E/AndroidRuntime(31415): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
E/AndroidRuntime(31415): 	... 11 more
I/Process (31415): Sending signal. PID: 31415 SIG: 9

mycode:

```
FlatButton(
                      onPressed: () async {
                        List<ScanResponse> results = [];

                        CustomizedViewRequest request = new CustomizedViewRequest(
                            scanType: HmsScanTypes.QRCode,
                            continuouslyScan: false,
                            isFlashAvailable: true,
                            flashOnLightChange: false,
                            customizedLifeCycleListener: (CustomizedViewEvent event){

                            },
                            customizedCameraListener: (ScanResponse response){
                              //Printing the result of each scan to debug console.
                              debugPrint(response.showResult);
                              //Collecting ScanRespone objects to a list.
                              setState(() {
                                results.add(response);
                              });
                            }
                        );
                        try {
                          results.add(await HmsCustomizedView.startCustomizedView(request));
                        } on Exception catch (e) {
                          // TODO
                          print("here is the problem $e");
                        }
                      },
                      child: new Text('Scan QR'),
                    `),`
```

**Comment by SerdarCanDev** [comment]
Hi @BombeyR , the crash happens while Flutter evaluates the result and request codes. Since Flutter plugins share a single Activity, all plugins that implement the `onActivityResult` callback will trigger its own method when an activity result code is created.  

According to your logs, the actual reason behind your crash is `onActivityResult` method of Huawei IAP Flutter Plugin. As mentioned above, when a result code is created from an activity, all `onActivityResult` methods try to find its own request and result code, yet fails while processing the IAP Plugin's  `onActivityResult`. 

As a workaround, you may change the following lines which located at `MethodCallHandlerImpl.java` of Huawei IAP Flutter Plugin (`com.huawei.hms.flutter.iap.MethodCallHandlerImpl.onActivityResult`)
```java
@Override
 public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        final Result result = Objects.requireNonNull(mResultsForRequests.get(requestCode)).first;
        final int requestType = Objects.requireNonNull(mResultsForRequests.get(requestCode)).second;
...
```
To
```java
@Override
 public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        // Use the following code instead
        Pair<Result, Integer> pair = mResultsForRequests.get(requestCode);
        if (pair == null) {
            return false;
        }
        
        final Result result = pair.first;
        final int requestType = pair.second;
```

**Comment by BombeyR** [comment]
IAP is mot the only plugin which depends on intent. Do i have to do that for all plugins?

**Comment by SerdarCanDev** [comment]
Changing only Huawei IAP Flutter Plugin's `onActivityResult` will resolve the issue.

**Comment by BombeyR** [comment]
Issue resolved. thanks.
