### ISSUE TITLE
[huawei_ar] Loading 3D object from url

### ISSUE THREAD

**Issue by medyas** [HMS-Core/hms-flutter-plugin#261]
**Description**
I am trying to use the AR Kit to load a 3D object from Url but could any mention on how can this be done on the docs.
The Scene Kit has a mention on how to load Models using the resource builder https://developer.huawei.com/consumer/en/doc/development/graphics-Guides/fine-grained-loadres-0000001064639484 but this is not available in the huawei_ar plugin.

**Expected behavior**
The possibility to load models from urls  using a resource builder 

**Current behavior**
No possible

Are there any plans to add support for the Scene Kit in the AR plugin ?

**Comment by ozkulbeng** [comment]
Hi @medyas 
The url that you sent is the documentation of the Scene Kit. Unfortunately, Scene Kit is not one of the packages that was developed for Flutter. You can find all Flutter packages in [pub.dev](https://pub.dev/publishers/developer.huawei.com/packages) and the official documentations [here](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/flutter-intro-0000001054787256).
