### ISSUE TITLE
onLocationData don't listen location

### ISSUE THREAD

**Issue by guvanch07** [HMS-Core/hms-flutter-plugin#268]
**Description**
I want to listen location changes of use and now I am testing but location is null

added to manifest

   <uses-permission android:name="android.permission.ACCESS_COARES_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

also aded to build.gradle and to app/build.gradle

apply plugin: 'com.huawei.agconnect'
classpath 'com.huawei.agconnect:agcp:1.6.5.300'
maven { url 'https://developer.huawei.com/repo/' }
implementation 'com.huawei.hms:location:6.7.0.300'

  I am calling to see just log

   final _hms = HMSLocationService();

 @override
  void initState() {
     _hms.init();
     super.initState();
  }

//location service
class HMSLocationService {
  late final FusedLocationProviderClient _hmsLocationService;

  late final LocationSettingsRequest _locationSettingsRequest;
  late final LocationRequest _locationRequest;
  late final List<LocationRequest> _locationRequestList;

 class HMSLocationService {
  late final FusedLocationProviderClient _hmsLocationService;
  late final LocationSettingsRequest _locationSettingsRequest;
  late final LocationRequest _locationRequest;
  late final List<LocationRequest> _locationRequestList;

  HMSLocationService() {
    _hmsLocationService = FusedLocationProviderClient();
    _locationRequest = LocationRequest();
    _locationRequest.interval = 5000;
    _locationRequestList = <LocationRequest>[_locationRequest];
    _locationSettingsRequest = LocationSettingsRequest(
      requests: _locationRequestList,
      needBle: true,
      alwaysShow: true,
    );
    _hmsLocationService.checkLocationSettings(_locationSettingsRequest);
  }

  StreamSubscription<Location>? streamSubscription;

  Future<void> init() async {
    streamSubscription = _hmsLocationService.onLocationData?.listen((position) {
       log('⚙️ \x1B[35m -------> hms init');
       log('${position.latitude}');
       log('${position.longitude}');
    });
  }

  Future<bool> hasPermissionEnabled() async {
    try {
       bool status = await Permission.location.serviceStatus.isEnabled;
       return status;
    } catch (e) {
       log(e.toString());
       return false;
    }
  }

  Future<bool> hasPermissionGranted() async {
    try {
       final status = await Permission.location.status;
       if (status.isGranted) {
         return true;
       } else {
         return false;
       }
     } catch (e) {
      log(e.toString());
      return false;
    }
  }
}

**Logs**
Restarted application in 1 050ms.
I/HMSSDK_HwLocation_LocationClientImpl(10952): |75dee52e-bad7-405a-bfd9-cf8f19b271f8|checkLocationSettings
I/LiteSDKProxy(10952): [2023-01-24 08:38:03.723 I/LITE_SDK-LiteSDKProxy] is system app
I/HMSSDK_LiteSDKProxy(10952): isHMSEnable:true
I/HMSSDK_HMSPackageManager(10952): Enter getHMSPackageNameForMultiService
D/HMSLogger(10952): singleEventMap -> {apiName=FusedLocationStreamHandler.onCancel, package=com.example.hms_test, cpAppVersion=1.0.0, version=6.4.0.300, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Location, appid=null, model=HWJNY, networkType=WIFI, callTime=1674538683728}
I/HMSSDK_HuaweiApi(10952): No setInnerHms, hms pkg name is com.huawei.hwid
I/HMSSDK_HuaweiApi(10952): sendRequest
I/HMSSDK_HuaweiApi(10952): isConnected:true.
I/HMSSDK_BaseHmsClient(10952): getAdapter:isInner:false, mInnerBinderAdapter:null, mOuterBinderAdapter:com.huawei.hms.adapter.OuterBinderAdapter@b8d7d3e
D/HMSLogger(10952): singleEventMap -> {apiName=FusedLocationStreamHandler.onListen, package=com.example.hms_test, cpAppVersion=1.0.0, version=6.4.0.300, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Location, appid=null, model=HWJNY, networkType=WIFI, callTime=1674538683730}
I/HMSSDK_RequestManager(10952): addToConnectedReqMap
I/HMSSDK_HmsClient(10952): post msg api_name:location.checkLocationSettings, app_id:|, pkg_name:com.example.hms_test, sdk_version:60500300, session_id:*, transaction_id:000000000ttings20230124083803732199285, kitSdkVersion:60700300, apiLevel:1
I/HMSSDK_BaseAdapter(10952): In constructor, activityWeakReference is java.lang.ref.WeakReference@3742850, activity is com.example.hms_test.MainActivity@b77c0ec
I/HMSSDK_BaseAdapter(10952): in baseRequest + uri is :location.checkLocationSettings, transactionId is : 000000000ttings20230124083803732199285
I/HMSSDK_PendingResultImpl(10952): init uri:location.checkLocationSettings
I/HMSSDK_PendingResultImpl(10952): setResultCallback
I/HMSSDK_PendingResultImpl(10952): setResult:0
I/HMSSDK_BaseAdapter(10952): api is: location.checkLocationSettings, resolution: null, status_code: 0
I/HMSSDK_BaseAdapter(10952): baseCallBack.onComplete
I/HMSSDK_HmsClient(10952): receive msg status_code:0, error_code:0, api_name:location.checkLocationSettings, app_id:|, pkg_name:com.example.hms_test, session_id:*, transaction_id:000000000ttings20230124083803732199285, resolution:null
I/HMSSDK_TaskApiCall(10952): doExecute, uri:location.checkLocationSettings, errorCode:0, transactionId:null
I/HMSSDK_HwLocation_CheckLocationSettingsTaskApiCall(10952): |75dee52e-bad7-405a-bfd9-cf8f19b271f8|doExecute
I/HMSSDK_ServiceErrorCodeAdaptor(10952): set task by error code:0,reason:SUCCESS
I/HMSSDK_RequestManager(10952): removeReqByTransId
D/HMSLogger(10952): singleEventMap -> {apiName=checkLocationSettings, package=com.example.hms_test, cpAppVersion=1.0.0, version=6.4.0.300, platform=Flutter, result=0, costTime=56, service=Cross-Platform, kit=Location, appid=null, model=HWJNY, networkType=WIFI, callTime=1674538683776}

**Environment**
  Flutter
  huawei_location: ^6.4.0+300
  permission_handler: ^10.2.0

 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.3.1 21E258 darwin-x64, locale ru-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by guvanch07** [comment]
[log] LocationSettingsStates(blePresent: true, bleUsable: false, gpsPresent: true, gpsUsable: true, locationPresent: true, locationUsable: true, networkLocationPresent: true, networkLocationUsable: true, hmsLocationPresent: true, hmsLocationUsable: true, gnssPresent: true, gnssUsable: true)

**Comment by sinemsevilmis** [comment]
Hi @guvanch07,

**onLocationData** listens for location updates that come from the `requestLocationUpdates` method. Please make sure you call the `requestLocationUpdates` method.

![location_1](https://user-images.githubusercontent.com/74876610/214550792-e86cffb6-a5ae-4108-b5b4-a1028f067cc8.PNG)

![location_2](https://user-images.githubusercontent.com/74876610/214550853-183bc3c9-0a6b-4b66-a8c1-31c7a93cd8cd.PNG)

**Comment by guvanch07** [comment]
thank you @sinemsevilmis
