### ISSUE TITLE
hianalytics has been updated to 6.9.0.302, please update the flutter plugin

### ISSUE THREAD

**Issue by zhangruiyu** [HMS-Core/hms-flutter-plugin#271]
Description
hianalytics has been updated to 6.9.0.302, please update the flutter plugin

https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/version-change-history-0000001050705116

**Comment by sinemsevilmis** [comment]
Hi @zhangruiyu,

Huawei Analytics Kit 6.9.0+302 has been released. Please check [pub.dev](https://pub.dev/packages/huawei_analytics).

Thank you for your interest.
