### ISSUE TITLE
How to size windows scan embbed in 1/2 page flutter.

### ISSUE THREAD

**Issue by nguyenthao1988** [HMS-Core/hms-flutter-plugin#273]
How to size windows scan embbed in 1/2 page flutter.

Like image below:
[https://laptrinhvb.net/screen_qr.png](url)

Thanks all.

**Comment by ozkulbeng** [comment]
Hello @nguyenthao1988 
Please check #88 . If you think it won't solve your problem entirely, you can reopen this issue.
