### ISSUE TITLE
how about make the huawei_ml support null safe ?

### ISSUE THREAD

**Issue by badboy-tian** [HMS-Core/hms-flutter-plugin#278]
```
huawei_ml: ^2.0.5+301
```
```
The library 'package:huawei_ml/huawei_ml.dart' is legacy, and shouldn't be imported into a null safe library
```

**Comment by huseyinerenguler** [comment]
Hi @badboy-tian 

[huawei_ml](https://pub.dev/packages/huawei_ml) package will no longer be updated. We divided huawei_ml into 4 seperate packages with null safety support. You can use each package seperately according to the needs of your application.

[huawei_ml_text](https://pub.dev/packages/huawei_ml_text)
[huawei_ml_body](https://pub.dev/packages/huawei_ml_body)
[huawei_ml_image](https://pub.dev/packages/huawei_ml_image)
[huawei_ml_language](https://pub.dev/packages/huawei_ml_language)

Thank you for your interest.
