### ISSUE TITLE
Map Kit: Build fails when map kit is added

### ISSUE THREAD

**Issue by BombeyR** [HMS-Core/hms-flutter-plugin#28]
My app no longer build when I integrate the map kit

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type com.huawei.secure.android.common.ssl.R is defined multiple times: C:\Users\Roney\.gradle\caches\transforms-2\files-2.1\942fea77eaf410d431e51b208b43a803\jetified-maps-base-4.0.1.300-runtime.jar:com/huawei/secure/android/common/ssl/R.class, C:\Users\Roney\AndroidStudioProjects\health_pal\build\app\intermediates\compile_and_runtime_not_namespaced_r_class_jar\debug\R.jar:com/huawei/secure/android/common/ssl/R.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 27s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by SerdarCanDev** [comment]
Hi @BombeyR , thank you for reporting the issue.

`com/huawei/secure/android/common/ssl/R.class` is a class that included in Huawei dependencies. Can you please share your `build.gradle` files located in the **project-root/android** and **project-root/android/app** folders alongside with Huawei plugins that you used in your project, which you may find in **pubspec.yaml** file of your project? Providing a minimal, reproducible project can also be helpful. 

We will investigate the issue and suggest a workaround as soon as possible. Meanwhile, you may try running `flutter clean` and `flutter run` commands, and also, from **Android Studio** you may try to **invalidate caches and restart** and clean the project using **Build > Clean Project**.

**Comment by SerdarCanDev** [comment]
Hi @BombeyR ,

As mentioned earlier `com/huawei/secure/android/common/ssl/R.class` is a class that included in HMS dependencies, and may conflict with each other in certain circumstances. As a workaround, you may bump the version of HMS Map Kit SDK's version (4.0.1.300) to **4.0.1.301**.

The update steps are as follows:
- Locate the huawei_map folder of your project.
    - You may find plugin folders using Android Studio's **External Libraries > Flutter Plugins** section.
    - Or you may find plugin folders from `.../flutter/.pub-cache/hosted/pub.dartlang.org/huawei_map-4.0.4+300` directory.
- Locate Huawei Map Flutter Plugin's **android/build.gradle** file. 
- Update the version of HMS Map SDK's version to **4.0.1.301**.
   ``` java
  ...

  dependencies {
    implementation 'com.huawei.hms:maps:4.0.1.300' //Change this version to 4.0.1.301 
  }
  ```

After changing the plugin file, please do not forget to **Invalidate Caches and Restart** the project using Android Studio.

The mentioned issue is in our update scope, we will provide a permanent solution with our next major release.

Additionally, the followings may cause issues in later development:
- `apply plugin: 'com.huawei.agconnect'` line should below other apply entries.
- The HMS dependencies in your **project-root/android/app/build.gradle** are not needed if you didn't implement platform-specific code in your project using HMS dependencies. HMS Flutter Plugins includes their own. 
- Keeping the minSdkVersion at 19 might cause issues while using multidex. You may want to increase the version to 21. For information about the issue and its solution please refer to this [StackOverflow issue](https://stackoverflow.com/questions/60745249/flutter-the-shrinker-may-have-failed-to-optimize-the-java-bytecode).
