### ISSUE TITLE
isEnvReady function stuck.

### ISSUE THREAD

**Issue by ninhngadev** [HMS-Core/hms-flutter-plugin#284]
When I go to AppGallery to logout, then my app calls `isEnvReady` function, app opens login window, if I successfully login `isEnvReady` function never finish running. But if I fail to login it works properly. This error is reproducible in the `example` code.

**Comment by simonakad** [comment]
Hi @ninhngadev ,

As far as I know the latest version of `huawei_iap` (6.4.0.302) solves this issue, but there is a bug that was recently solved. Until a new version release, please also check #293 to apply the required changes. 😊
