### ISSUE TITLE
HMS Location vs Flutter geolocator?

### ISSUE THREAD

**Issue by giorgio79** [HMS-Core/hms-flutter-plugin#285]
I have been using https://pub.dev/packages/geolocator in my app.

When would I use Huawei Location plugin? Would geolocator be enough? Or it doesnt work in Huawei app store?

**Comment by sunnykinger** [comment]
same question

**Comment by peura-toni** [comment]
Geolocator plugin offers various location-related features such as determining the current device location, monitoring device location changes, and calculating distances between two locations. It uses the native location services provided by the platform to obtain location information.

On the other hand, Huawei Location Kit is a location service provided by Huawei, specifically for Huawei devices. It offers similar features to Geolocator plugin, such as obtaining the device's current location, geofencing, and activity recognition. Huawei Location Kit uses various sensors, including GPS, Wi-Fi, and cell towers, to obtain location information. Additionally, Huawei Location Kit provides some advanced features such as indoor positioning, which is not available in Geolocator plugin.

If you're developing a Flutter application for both Android and iOS platforms, Geolocator plugin would be your choice. However, if you're developing an application specifically for Huawei devices, you might consider using Huawei Location Kit to take advantage of its advanced features.
