### ISSUE TITLE
How to achieve higher accuracy on Skeleton Detection?

### ISSUE THREAD

**Issue by headbig947** [HMS-Core/hms-flutter-plugin#286]
I try to use the skeleton detection service detects and locates key points of the human body,but it's a problem about accuracy.I need to determine if the person is tall or low shoulder.

**Comment by ozkulbeng** [comment]
Hello @headbig947 
The issue you mentioned is about SDK capability itself. Flutter plugins are only wrappers for native SDKs.
For issues related to native SDKs, you can [submit a ticket online](https://developer.huawei.com/consumer/en/support/feedback/#/).
