### ISSUE TITLE
huawei_scan and permission request

### ISSUE THREAD

**Issue by vkormin** [HMS-Core/hms-flutter-plugin#288]
Hello, we are trying to migrate our app from huawei_scan ver.2.1.0+300 to 2.8.0+300. In package version history I see following: "__Breaking Change__: With this release, PermissionMethodCallHandler has been removed. You are expected to handle required permissions on your own. You can learn more about the required permissions from our [official documentations](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/dev-process-0000001057213093?ha_source=hms1)"

How to perform permission request? In 2.1.0+300 there was plugin method channel which performs native calls, but in 2.8.0+300 where is no such method. We have tried "permission_handler" from pub.dev but it works only on GMS based devices. 

If i skip permission check, i've got NO CAMERA PERMISSIONS error.

Please advice, thank you.

**Comment by ilsafarber** [comment]
I am also using huawei_scan with the permission_handler, and it works fine on my Huawei P40 Pro (without GMS). 

![withoutgms](https://user-images.githubusercontent.com/126053105/230014711-c14d9cac-bec2-4c3b-8a25-29825c3a5fe9.png) 
![granted](https://user-images.githubusercontent.com/126053105/230014744-868b98ea-2df4-4728-9d82-955deb7b09cb.png)
As you see, I also tried in a little app to check. 
I recommend you to open an issue to permission_handler. Maybe your device is not compatible or have a conflict with the versions.
