### ISSUE TITLE
requestLocationUpdatesCb 时间间隔设置

### ISSUE THREAD

**Issue by rainyear** [HMS-Core/hms-flutter-plugin#29]
```dart
final LocationRequest _locationRequest = LocationRequest()..interval = 500;
...
final int requestCode = await _locationService.requestLocationUpdatesCb(_locationRequest, _locationCallkback);
```

设置时间间隔 `interval = 500` ms，但实际运行的位置更新信息时间戳（`time`）间隔都在`40000ms`左右，`elapsedRealtimeNanos` 的时间差在 10s 左右，是什么原因？

**Comment by rahmicanisin** [comment]
Hi @rainyear ,
Interval determines the minimum value.
requestLocationUpdatesCb method is an asynchronous method.
Response time may vary due to environmental factors. Therefore the time value may vary.
