### ISSUE TITLE
[huawei_push] can i send massage from the app to all users which install the app ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [HMS-Core/hms-flutter-plugin#292]
can i send massage from the app to all users which install the app ?

**Comment by ilsafarber** [comment]
Hello @Joseph-Nathan 

Yes, you can send messages to your app's users using Huawei Push Kit. Huawei Push Kit provides push notification services that allow you to send messages and notifications to users who have installed your app on Huawei devices.

It's important to refer to the official documentation and guidelines provided by Huawei for detailed instructions and code samples. The documentation will provide you necessary information to implement the code on the client-side to receive and process the messages sent by Huawei Push Kit.

Please follow the official documentation for [development guides](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001050176002) and [api references](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/push-overview-0000001193655312).
