### ISSUE TITLE
Huawei location flutter plugin can't used on Android 12

### ISSUE THREAD

**Issue by grapewheel** [HMS-Core/hms-flutter-plugin#304]
**Description**
Following to the [develop guide](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/prepare-dev-env-0000001050433505) settings, and then `flutter run`, everything is fine except invoked the `requestLocationUpdates`, it occurs the error below:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(10806, 10806: NOT_YET_SUPPORTED, null, null)`

**Expected behavior**
Get the location info, Fused location

**Current behavior**
10806 Error

**Environment**
 - Platform: Flutter 3.7.6
 - Phone: Samsung
 - Kit: huawei_location
 - Kit Version 6.4.0+300
 - OS Version Android 12
 - Android Studio version Flamingo 2022.2.1 Patch 2
 - Platform version Linux

**Other**

- The app targetSdkVersion 30 (Try 31, but occur the [issue](https://github.com/HMS-Core/hms-flutter-plugin/issues/174))

- It should be support Non-huawei phone:

![FireShot Capture 173 - About the Service-Location Kit - HUAWEI Developers - developer huawei com](https://github.com/HMS-Core/hms-flutter-plugin/assets/490426/d234b464-80cd-4b36-bb5e-5ebdd949c67a)

**Comment by ilsafarber** [comment]
Hello @bkleineibst 
I had the same issue with my Samsung phone and when I looked up the documents, it says that normal functions are not affected in spite of some errors occur. For reference: [link](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/faq-0000001050986161#section1127613714227).
Do your other functions work properly? Or are you having just some logs say that not supported?
