### ISSUE TITLE
Type com.huawei.secure.android.common.ssl.R is defined multiple times

### ISSUE THREAD

**Issue by alfred-risb** [HMS-Core/hms-flutter-plugin#31]
I get the error as title when compile release apk, need to manually update the "huawei_map" gradle from "com.huawei.hms:maps:4.0.1.300" to "com.huawei.hms:maps:4.0.1.301" only fix the issue

**Comment by aktug** [comment]
Hello @alfred-risb ,
We follow the release plan for our plugins, if you don't want to wait, you can do it manually until the new version released 👍
Thanks for your understanding and patience @alfred-risb
