### ISSUE TITLE
hms huawei exception

### ISSUE THREAD

**Issue by ahmedNagar123** [HMS-Core/hms-flutter-plugin#310]
I/NetworkKit_d( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.g.d|b|204|convert expireTime{86620000}
I/NetworkKit_d( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.g.d|a|24|success get Etag from server
I/NetworkKit_d( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.g.d|p|21|GRSSDK get httpcode{304} not any changed.
I/NetworkKit_c( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.g.c|a|83|GRS server open 304 Not Modified.
I/NetworkKit_LocalManagerProxy( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.f.b|a|14|appGrs is not null and clear services.
I/NetworkKit_c( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.g.c|a|181|future cancel
I/NetworkKit_c( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.g.c|a|181|future cancel
I/NetworkKit_c( 5650): NetworkKit_GRS_RequestController-Task_0 -->NetworkKit_GRS_RequestController-Task_1|null|com.huawei.hms.framework.network.grs.g.c|a|140|{requestServer} the computation was cancelled
I/NetworkKit_c( 5650): NetworkKit_GRS_RequestController-Task_0 -->NetworkKit_GRS_RequestController-Task_1|null|com.huawei.hms.framework.network.grs.g.c|b|106|{checkResponse} when check result, find CancellationException, check others
W/NetworkKit_c( 5650): NetworkKit_GRS_RequestController-Task_0 -->NetworkKit_GRS_RequestController-Task_1|null|com.huawei.hms.framework.network.grs.g.c|b|97|{checkResponse} when check result, find ExecutionException, check others
W/NetworkKit_c( 5650): java.util.concurrent.ExecutionException: j*v*.*a*g*N*l*P*i*t*r*x*e*t*o*:*A*t*m*t*t* *n*o*e*v*r*u*l*m*t*o* *a*d*o*d*c*n*e*t*C*n*e*t*a*d*o*d*c*n*e*t*C*n*e*t*c*e*t*D*v*c*P*o*e*t*d*t*r*g*C*n*e*t*)* *n*a*n*l* *b*e*t*r*f*r*n*e
W/NetworkKit_c( 5650): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
W/NetworkKit_c( 5650): 	at java.util.concurrent.FutureTask.get(FutureTask.java:207)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.c.b(Unknown Source:47)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.c.a(Unknown Source:161)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.c.b(Unknown Source:6)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.c.a(Unknown Source:0)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.c$a.call(Unknown Source:8)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.c$a.call(Unknown Source:0)
W/NetworkKit_c( 5650): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.common.RunnableEnhance.run(RunnableEnhance.java:30)
W/NetworkKit_c( 5650): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/NetworkKit_c( 5650): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/NetworkKit_c( 5650): 	at java.lang.Thread.run(Thread.java:920)
W/NetworkKit_c( 5650): Caused by: java.lang.NullPointerException: A*t*m*t*t* *n*o*e*v*r*u*l*m*t*o* *a*d*o*d*c*n*e*t*C*n*e*t*a*d*o*d*c*n*e*t*C*n*e*t*c*e*t*D*v*c*P*o*e*t*d*t*r*g*C*n*e*t*)* *n*a*n*l* *b*e*t*r*f*r*n*e
W/NetworkKit_c( 5650): 	at com.huawei.secure.android.common.ssl.util.h.b(SourceFile:3)
W/NetworkKit_c( 5650): 	at com.huawei.secure.android.common.ssl.util.h.a(SourceFile:1)
W/NetworkKit_c( 5650): 	at com.huawei.secure.android.common.ssl.util.d.b(SourceFile:5)
W/NetworkKit_c( 5650): 	at com.huawei.secure.android.common.ssl.util.d.a(SourceFile:1)
W/NetworkKit_c( 5650): 	at com.huawei.secure.android.common.ssl.hostname.StrictHostnameVerifier.verify(SourceFile:7)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:200)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
W/NetworkKit_c( 5650): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.g.call(Unknown Source:117)
W/NetworkKit_c( 5650): 	at com.huawei.hms.framework.network.grs.g.g.call(Unknown Source:0)
W/NetworkKit_c( 5650): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
I/SecurityComp10200303: SecureSSLSocketFactoryNew( 5650): createSocket s host port autoClose
I/SecurityComp10200303: SecureSSLSocketFactoryNew( 5650): set default protocols
I/SecurityComp10200303: SecureSSLSocketFactoryNew( 5650): set default cipher suites
I/NetworkKit_HianalyticsHelper( 5650): NetworkKit_GRS_RequestController-Task_0 -->NetworkKit_GRS_RequestController-Task_1|HianalyticsHelper.java|com.huawei.hms.framework.common.hianalytics.HianalyticsHelper|<init>|73|Hianalytics sdk not found
I/NetworkKit_HianalyticsHelper( 5650): NetworkKit_GRS_RequestController-Task_0 -->NetworkKit_GRS_RequestController-Task_1|HianalyticsHelper.java|com.huawei.hms.framework.common.hianalytics.HianalyticsHelper|tryHMSBIInit|84|the appContext hasn't init
I/NetworkKit_HianalyticsHelper( 5650): NetworkKit_GRS_RequestController-Task_0 -->NetworkKit_GRS_RequestController-Task_1|HianalyticsHelper.java|com.huawei.hms.framework.common.hianalytics.HianalyticsHelper|isEnableReportNoSeed|161|Hianalytics sdk need to be initialized

**Comment by ahmedNagar123** [comment]
and get it this error 
W/NetworkKit_g( 5650): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_0|null|com.huawei.hms.framework.network.grs.g.g|call|230|RequestCallableV2 run task catch IOException
W/NetworkKit_g( 5650): java.io.InterruptedIOException: t*r*a* *n*e*r*p*e*
W/NetworkKit_g( 5650): 	at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
W/NetworkKit_g( 5650): 	at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
W/NetworkKit_g( 5650): 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
W/NetworkKit_g( 5650): 	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
W/NetworkKit_g( 5650): 	at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
W/NetworkKit_g( 5650): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
W/NetworkKit_g( 5650): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
W/NetworkKit_g( 5650): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)

**Comment by ozkulbeng** [comment]
Hello @ahmedNagar123 
Please follow the [template](https://github.com/HMS-Core/hms-flutter-plugin/blob/master/.github/ISSUE_TEMPLATE/issue-with-the-sample-code.md) for us to understand and investigate the issue in detail.
