### ISSUE TITLE
[Location] getLastLocation return null values even after requestLocationUpdates called

### ISSUE THREAD

**Issue by EArminjon** [HMS-Core/hms-flutter-plugin#313]
**Description**
On Huawei Mate 40 pro, i'm not able to get user current Location.
I'm using the Huawei cloud console.

```dart
await FusedLocationProviderClient().requestLocationUpdates(LocationRequest());
final result = await FusedLocationProviderClient().getLastLocation();
print(result);
```

**Expected behavior**
Get current user location

**Current behavior**
The Location object contain only null values.
Can we get user location inside a cloud debugging device from the Huawei cloud console ?

**Screenshots**
print result of `FusedLocationProviderClient().getLastLocation()`
![Capture d’écran 2023-08-31 à 15 44 14](https://github.com/HMS-Core/hms-flutter-plugin/assets/37028599/55dd39ac-5ba6-4494-acb9-bab37c070015)

**Environment**
 - Platform: Flutter
 - Kit: huawei_location
 - Kit Version 6.11.0+301
 - OS Version Android 10

**Comment by ozkulbeng** [comment]
Hello @EArminjon 
Please update [location](https://pub.dev/packages/huawei_location) plugin to the latest version. Clean your cache and try again. 
If the issue persists, do not hesitate to write to us.
