### ISSUE TITLE
[Location] Package named 6.11.0+301 but use sdk 6.4.0.300

### ISSUE THREAD

**Issue by EArminjon** [HMS-Core/hms-flutter-plugin#319]
**Description**

Wrong name which point to a different native sdl

**Expected behavior**
Have the same native sdk as name

**Current behavior**

Incompatibility with Android 12+

**Screenshots**

Pubspec website use : 

![Capture d’écran 2023-09-13 à 11 46 19](https://github.com/HMS-Core/hms-flutter-plugin/assets/37028599/2248d8e8-dd70-42f5-9e91-e0ec43a5b275)

Package source code use 6.4.0.300 : 

![Capture d’écran 2023-09-13 à 11 45 10](https://github.com/HMS-Core/hms-flutter-plugin/assets/37028599/618c9dde-81e7-4663-9e39-8fa5ae0fc71b)

In the source code. :
```
dependencies {
    implementation 'com.huawei.hms:location:6.4.0.300'
}
```

**Environment**
 - Platform: [Flutter]
 - Kit: [Location]

**Comment by ozkulbeng** [comment]
Hello @EArminjon 
The new version 6.11.0+301 of [Location Kit](https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-location) has been published on GitHub. You can also find the latest updates on [Huawei Developers](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library/flutter-sdk-download-0000001050304074-V1) which is the official website for HMS kits.
Thank you for your interest in our plugins.
