### ISSUE TITLE
HmsBorderRect and DriverInfo documentation

### ISSUE THREAD

**Issue by patv2learn** [HMS-Core/hms-flutter-plugin#34]
I am looking into readme details and it describe (https://pub.dev/packages/huawei_scan) about borderrect and driverinfo but not much details. Can you please link to more detailed documentation on this?

I have a requirement to provide capture driving license image of both side and read barcode (pdf417) from the back image in my app.

Something like https://youtu.be/T1iSh_9ZhDA

Thanks in advance.

**Comment by SerdarCanDev** [comment]
Hi @patv2learn , please refer to the following links for details.

[Scan Kit Flutter Plugin Development Guide](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001054309573)

[Scan Kit Flutter API References](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/overview-0000001054390809)

[HmsBorderRect](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/hms-borderrect-0000001057018865)

[DriverInfo](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/driverinfo-0000001054070788)
