### ISSUE TITLE
flutter ios AGConnectCrashPlugin init failed

### ISSUE THREAD

**Issue by sercangoger** [HMS-Core/hms-flutter-plugin#340]
"AGConnectCrashPlugin init failed, exception name: NSGenericException, exception reason: package_name in agconnect services plist does not match with bundle identifier."

I get an error.

<img width="1230" alt="Ekran Resmi 2023-12-09 00 37 42" src="https://github.com/HMS-Core/hms-flutter-plugin/assets/20733337/c4d503be-c550-47c6-8aaf-dc5867e833fc">

**Comment by ozkulbeng** [comment]
Hello @sercangoger 
Unfortunately, this package you use is not one of the packages we have developed. 
Please contact the developers of `google_huawei_availability` package.
