### ISSUE TITLE
Huawei analytics does not work on Flutter

### ISSUE THREAD

**Issue by Taverz** [HMS-Core/hms-flutter-plugin#353]
**Description**

1. Installed HMS Core
2. Latest version platinum
3. Downloaded and pasted into the agconnect-services folder
4. Created and registered the SCA Fingerprint in the account settings
5. Enabled and configured analytics in your account
6. Gradl settings completed: 1- classpath 2- maven {url 3- plugin com.huawei.agconnect 4- buildTypes
7. The manifest settings were completed: 1- add HMSContentProvider 2- install_channel 3- INTERNET
8. Launched at application startup
9. Enabled logs
10. Sent events

PLUGIN ONLY: 
- huawei_analytics: 6.12.0+301 

Result:
Nothing has changed in the Analytics - Overview tab

Expected Result:
Changes in the Analytics - Overview tab

**Screenshots**
<img width="1488" alt="Снимок экрана 2024-02-02 в 17 17 37" src="https://github.com/HMS-Core/hms-flutter-plugin/assets/55701501/0fc8a061-1b41-4fcc-9f33-8ba2b9a6e7d8">

**Logs**
<details close>
<summary>Log 1 device</summary>
<br>

D/HMSLogger( 5170): HMS Plugin Dotting is Enabled!
D/HMSLogger( 5170): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=2, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882313685}
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : setAnalyticsEnabled
D/HMSLogger( 5170): singleEventMap -> {apiName=setAnalyticsEnabled, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882313689}
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : enableLog
I/HiAnalyticsSDK( 5170): =======================================
I/HiAnalyticsSDK( 5170):  HiAnalyticsSDK_6.12.0.300
I/HiAnalyticsSDK( 5170): =======================================
D/HMSLogger( 5170): singleEventMap -> {apiName=enableLog, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882313694}
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : setReportPolicies
I/HiAnalyticsSDK( 5170): PoliceCommander=> save policies : {"onScheduledTime":600}
D/HMSLogger( 5170): singleEventMap -> {apiName=setReportPolicies, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882313696}
I/HiAnalyticsSDK( 5170): AbstractDao=> deleteAll: APIEVENT
D/TrafficStats( 5170): tagSocket(205) with statsTag=0xffffffff, statsUid=-1
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : getInstance
W/HiAnalyticsSDK( 5170): HiAnalyticsCreation=> not find analytics plugin
D/HMSLogger( 5170): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882313797}
D/HiAnalyticsSDK( 5170): OpennessInitTask=> init running
W/HiAnalyticsSDK( 5170): TrieRuleDecider=> JSON Parse error: End of input at character 0 of
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
D/TrafficStats( 5170): tagSocket(205) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(205) with statsTag=0xffffffff, statsUid=-1
[GoRouter] setting initial location /
D/TrafficStats( 5170): tagSocket(206) with statsTag=0xffffffff, statsUid=-1
I/HiAnalyticsSDK( 5170): RecordMission=> record evt size : 2
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : onEvent
D/HMSLogger( 5170): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882438832}
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l( 5170): secretKeyCache not empty.
I/HMSSDK_l( 5170): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager( 5170): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer( 5170): Builder->biInitFlag :false
I/HMSSDK_Util( 5170): available exist: true
I/HMSSDK_AvailableUtil( 5170): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK( 5170): RecordMission=> record evt size : 3
I/ViewRootImpl@7522676[MainActivity]( 5170): onDisplayChanged oldDisplayState=2 newDisplayState=2
D/TrafficStats( 5170): tagSocket(230) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(230) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(230) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(230) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(230) with statsTag=0xffffffff, statsUid=-1
I/ViewRootImpl@7522676[MainActivity]( 5170): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : getInstance
W/HiAnalyticsSDK( 5170): HiAnalyticsCreation=> not find analytics plugin
D/HiAnalyticsSDK( 5170): OpennessInitTask=> init running
W/HiAnalyticsSDK( 5170): TrieRuleDecider=> JSON Parse error: End of input at character 0 of
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
D/HMSLogger( 5170): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882457237}
W/WindowOnBackDispatcher( 5170): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 5170): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
Reloaded 1 of 2505 libraries in 935ms (compile: 152 ms, reload: 298 ms, reassemble: 339 ms).
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : onEvent
D/HMSLogger( 5170): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882457457}
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : onEvent
I/HiAnalyticsSDK( 5170): RecordMission=> record evt size : 4
D/HMSLogger( 5170): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882457483}
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l( 5170): secretKeyCache not empty.
I/HMSSDK_l( 5170): The local secret is already in separate file mode.
D/TrafficStats( 5170): tagSocket(242) with statsTag=0xffffffff, statsUid=-1
I/HMSSDK_HMSPackageManager( 5170): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer( 5170): Builder->biInitFlag :false
I/HMSSDK_Util( 5170): available exist: true
I/HMSSDK_AvailableUtil( 5170): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK( 5170): RecordMission=> record evt size : 5
I/ViewRootImpl@7522676[MainActivity]( 5170): onDisplayChanged oldDisplayState=2 newDisplayState=2
D/TrafficStats( 5170): tagSocket(219) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(219) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(219) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(219) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5170): tagSocket(219) with statsTag=0xffffffff, statsUid=-1
I/ViewRootImpl@7522676[MainActivity]( 5170): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : getInstance
W/HiAnalyticsSDK( 5170): HiAnalyticsCreation=> not find analytics plugin
D/HiAnalyticsSDK( 5170): OpennessInitTask=> init running
W/HiAnalyticsSDK( 5170): TrieRuleDecider=> JSON Parse error: End of input at character 0 of
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
D/HMSLogger( 5170): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=2, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882511742}
W/WindowOnBackDispatcher( 5170): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 5170): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
Reloaded 1 of 2505 libraries in 806ms (compile: 94 ms, reload: 267 ms, reassemble: 364 ms).
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : onEvent
D/HMSLogger( 5170): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882511975}
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l( 5170): secretKeyCache not empty.
I/HMSSDK_l( 5170): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager( 5170): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer( 5170): Builder->biInitFlag :false
I/HiAnalyticsSDK( 5170): RecordMission=> record evt size : 6
I/HMSAnalyticsMethodCallHandler( 5170):  Running method : onEvent
D/HMSLogger( 5170): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=b0s, networkType=3G, callTime=1706882512009}
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK( 5170): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l( 5170): secretKeyCache not empty.
I/HMSSDK_l( 5170): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager( 5170): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer( 5170): Builder->biInitFlag :false
I/HMSSDK_Util( 5170): available exist: true
I/HMSSDK_AvailableUtil( 5170): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK( 5170): RecordMission=> record evt size : 7

</details>

<details close>
<summary>Log 2 device</summary>
<br>
I/cr_LibraryLoader(29317): Successfully loaded native library
I/cr_CachingUmaRecorder(29317): Flushed 7 samples from 7 histograms, 0 samples were dropped.
I/cr_VariationsUtils(29317): Loaded seed with age 17307s
I/cr_CombinedPProvider(29317): #registerProvider() provider:WV.v7@3d252f3 isPolicyCacheEnabled:false policyProvidersSize:0
I/cr_PolicyProvider(29317): #setManagerAndSource() 0
I/cr_CombinedPProvider(29317): #linkNativeInternal() 1
I/cr_AppResProvider(29317): #getApplicationRestrictionsFromUserManager() Bundle[EMPTY_PARCEL]
I/cr_PolicyProvider(29317): #notifySettingsAvailable() 0
I/cr_CombinedPProvider(29317): #onSettingsAvailable() 0
I/cr_CombinedPProvider(29317): #flushPolicies()
E/chromium(29317): [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0//cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
E/chromium(29317): [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
I/SecurityComp10200303: BksUtil(29317): getFilesBksIS
I/SecurityComp10200303: SecureX509SingleInstance(29317): get files bks
Connecting to VM Service at ws://127.0.0.1:50076/lff8xMvAI7k=/ws
I/SecurityComp10200303: SSLFNew(29317): createSocket
I/SecurityComp10200303: SSLFNew(29317): set default protocols
I/SecurityComp10200303: SSLFNew(29317): set default cipher
I/SecurityComp10200303: SX509TM(29317): checkServerTrusted begin,size=2,authType=ECDHE_RSA
I/SecurityComp10200303: SX509TM(29317): check server i=0
I/SecurityComp10200303: SX509TM(29317): client root ca size=31
I/SecurityComp10200303: SX509TM(29317): checkServerTrusted end, CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R3
I/SecurityComp10200303: (29317): verify: certificate is : CN=metrics-apptouch-dre.hispace.dbankcloud.com,O=Huawei Software Technologies Co.\, Ltd.,L=Nanjing,ST=Jiangsu,C=CN
I/SecurityComp10200303: c(29317): checkUpgradeBks, ignore
I/HMSSDK_HiAnalyticsUtils(29317): Enable Log
I/FormalHASDK(29317): =======================================
I/FormalHASDK(29317): FormalHASDK_2.2.0.314
I/FormalHASDK(29317): =======================================
I/HMSSDK_HMSBIInitializer(29317): Builder->biInitFlag :false
D/HMSLogger(29317): HMS Plugin Dotting is Enabled!
D/HMSLogger(29317): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=2, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882780123}
I/HMSAnalyticsMethodCallHandler(29317):  Running method : setAnalyticsEnabled
D/HMSLogger(29317): singleEventMap -> {apiName=setAnalyticsEnabled, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882780125}
I/HMSAnalyticsMethodCallHandler(29317):  Running method : enableLog
I/HiAnalyticsSDK(29317): =======================================
I/HiAnalyticsSDK(29317):  HiAnalyticsSDK_6.12.0.300
I/HiAnalyticsSDK(29317): =======================================
D/HMSLogger(29317): singleEventMap -> {apiName=enableLog, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882780126}
I/HMSAnalyticsMethodCallHandler(29317):  Running method : setReportPolicies
I/HiAnalyticsSDK(29317): PoliceCommander=> save policies : {"onScheduledTime":600}
D/HMSLogger(29317): singleEventMap -> {apiName=setReportPolicies, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882780128}
I/flutter (29317): [🌎 Easy Localization] [DEBUG] Localization initialized
I/HMSAnalyticsMethodCallHandler(29317):  Running method : getInstance
W/HiAnalyticsSDK(29317): HiAnalyticsCreation=> not find analytics plugin
D/HiAnalyticsSDK(29317): OpennessInitTask=> init running
D/HMSLogger(29317): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882780237}
W/HiAnalyticsSDK(29317): TrieRuleDecider=> JSON Parse error: End of input at character 0 of
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSAnalyticsMethodCallHandler(29317):  Running method : onEvent
D/HMSLogger(29317): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882780720}
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l(29317): secretKeyCache not empty.
I/HMSSDK_l(29317): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager(29317): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer(29317): Builder->biInitFlag :false
I/HMSSDK_Util(29317): available exist: true
I/HMSSDK_AvailableUtil(29317): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK(29317): RecordMission=> record evt size : 7
I/HMSAnalyticsMethodCallHandler(29317):  Running method : onEvent
D/HMSLogger(29317): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882780742}
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l(29317): secretKeyCache not empty.
I/HMSSDK_l(29317): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager(29317): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer(29317): Builder->biInitFlag :false
I/HMSSDK_Util(29317): available exist: true
I/HMSSDK_AvailableUtil(29317): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK(29317): RecordMission=> record evt size : 8
I/HMSAnalyticsMethodCallHandler(29317):  Running method : getInstance
W/HiAnalyticsSDK(29317): HiAnalyticsCreation=> not find analytics plugin
D/HiAnalyticsSDK(29317): OpennessInitTask=> init running
W/HiAnalyticsSDK(29317): TrieRuleDecider=> JSON Parse error: End of input at character 0 of
D/HMSLogger(29317): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=2, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882781225}
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSAnalyticsMethodCallHandler(29317):  Running method : onEvent
D/HMSLogger(29317): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=2, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882781263}
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSAnalyticsMethodCallHandler(29317):  Running method : pageStart
D/HiAnalyticsSDK(29317): ActivityStatCommander=> onScreenEnter with time: 1706882781273
D/HMSLogger(29317): singleEventMap -> {apiName=pageStart, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882781272}
D/HiAnalyticsSDK(29317): ActivityStatCommander=> onPageEnterSend
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l(29317): secretKeyCache not empty.
I/HMSSDK_l(29317): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager(29317): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer(29317): Builder->biInitFlag :false
I/HMSSDK_Util(29317): available exist: true
I/HMSSDK_AvailableUtil(29317): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK(29317): RecordMission=> record evt size : 11
I/HMSSDK_l(29317): secretKeyCache not empty.
I/HMSSDK_l(29317): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager(29317): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer(29317): Builder->biInitFlag :false
I/HMSSDK_Util(29317): available exist: true
I/HMSSDK_AvailableUtil(29317): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK(29317): RecordMission=> record evt size : 12
I/[AGC_LOG]HaConnector(29317): Auto onReport
I/HiAnalyticsSDK(29317): InteractionManager=> connectManager onReport
D/HiAnalyticsSDK(29317): ReportMission=> report running, serviceTag: AGC_TAG
I/HiAnalyticsSDK(29317): TokenAssignment=> start get token from agc
D/HiAnalyticsSDK(29317): RequestBas=> no need sync pub key
D/HiAnalyticsSDK(29317): TokenAssignment=> success: 14399
D/HiAnalyticsSDK(29317): ReportAssignment=> AGC_TAG report times: 0
I/HMSAnalyticsMethodCallHandler(29317):  Running method : getInstance
W/HiAnalyticsSDK(29317): HiAnalyticsCreation=> not find analytics plugin
D/HiAnalyticsSDK(29317): OpennessInitTask=> init running
W/HiAnalyticsSDK(29317): TrieRuleDecider=> JSON Parse error: End of input at character 0 of
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
D/HMSLogger(29317): singleEventMap -> {apiName=getInstance, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=2, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882782572}
I/HMSAnalyticsMethodCallHandler(29317):  Running method : onEvent
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
D/HMSLogger(29317): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=1, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882782634}
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSAnalyticsMethodCallHandler(29317):  Running method : onEvent
D/HMSLogger(29317): singleEventMap -> {apiName=onEvent, package=, cpAppVersion=1.1.5, version=6.12.0.301, platform=Flutter, result=0, costTime=0, service=Cross-Platform, kit=Analytics, appid=109548093, model=rk3399_Android12, networkType=WIFI, callTime=1706882782692}
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
W/HiAnalyticsSDK(29317): DeviceToolsKit=> invokeStaticFun() Exception
I/HMSSDK_l(29317): secretKeyCache not empty.
I/HMSSDK_l(29317): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager(29317): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer(29317): Builder->biInitFlag :false
I/HMSSDK_Util(29317): available exist: true
I/HMSSDK_AvailableUtil(29317): asyncCheckHmsUpdateInfo, not need to check
W/Choreographer(29317): Frame time is 0.024715 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
D/ProfileInstaller(29317): Installing profile for 
I/HiAnalyticsSDK(29317): RecordMission=> record evt size : 13
I/HMSSDK_l(29317): secretKeyCache not empty.
I/HMSSDK_l(29317): The local secret is already in separate file mode.
I/HMSSDK_HMSPackageManager(29317): Enter getHMSPackageNameForMultiService
I/HMSSDK_HMSBIInitializer(29317): Builder->biInitFlag :false
I/HMSSDK_Util(29317): available exist: true
I/HMSSDK_AvailableUtil(29317): asyncCheckHmsUpdateInfo, not need to check
I/HiAnalyticsSDK(29317): RecordMission=> record evt size : 14

</details>

**Environment**

Device:
1
Samsung S22 ultra
Android 14
2
Tablet
Android 12

Flutter 3.16.5 • channel stable •
Tools • Dart 3.2.3 • DevTools 2.28.4
-  sdk: '>=3.1.3 <4.0.0'
PLUGIN ONLY: 
- huawei_analytics: 6.12.0+301

**Comment by Taverz** [comment]
solved, it was necessary to update the configuration file

**Comment by RandGor** [comment]
Чувак, а что за файл ты обновил (и как), можешь подробнее?
