### ISSUE TITLE
[huawei_ads] Testing Ads with Cloud Debugging

### ISSUE THREAD

**Issue by dwnu** [HMS-Core/hms-flutter-plugin#36]
Well, I don't have any new Huawei smartphone so I want to use Cloud Debugging to test my ads implementation. The ad is showing but the listener is not called at all. Is this some kind of limitation of Cloud Debugging (I noticed "Initializing new device" message just before and after showing the ad)? 

If yes, then what's a good way to test ads without buying a new device?

**Comment by cagdasmer** [comment]
Hello @dwnu  
Could you please share snippets from your code, where you initialize the ad and also where you specify a listener for it?

**Comment by dwnu** [comment]
Sure, this is how it looks like after simplifying. It may be worth to say that my AdMob implementation looks exactly the same and works: 

```
static Future<void> initInterstitialAd() async {
    interstitialHwAd = hw.InterstitialAd(
      adSlotId: 'testb4znbuh3n2',
      adParam: hw.AdParam(
        options: hw.RequestOptions()// here I pass a few options
      ),
    );
    await interstitialHwAd.loadAd();
  }

  static Future<void> showInterstitialAd({@required Function onAfter}) async {
    interstitialHwAd.setAdListener = (hw.AdEvent event, {int errorCode}) async {
      switch (event) {
        default:
          print("It's never called :(");
          onAfter();
          break;
      }
    };

    await interstitialHwAd.show(); //ad is showing - this function is called 
  }
```

**Comment by furkansarihan** [comment]
Hi @dwnu 

It seems `setAdListener` doesn't work when you use it after `loadAd()`. We are investigating this wrong behavior right now and It will be fixed in next release.

Can you try to set the listener **before** `loadAd()` or in the InterstitialAd **constructor** instead of setAdListener? Like this;

```
interstitialHwAd = hw.InterstitialAd(
  adSlotId: 'testb4znbuh3n2',
  adParam: hw.AdParam(
    options: hw.RequestOptions()// here I pass a few options
  ),
  listener: (hw.AdEvent event, {int errorCode}) async {
    switch (event) {
      default:
        print("Should be called!");
        onAfter();
        break;
    }
  }
);
```

**Comment by dwnu** [comment]
Hi @furkansarihan 
I'm sorry for the late response. Thank you for looking into this issue. 

To be honest, it's not my priority right now, so I'll wait for the fix probably. Is there any ETA?

**Comment by aktug** [comment]
Hello @dwnu 
Thank you for your interest, We're trying to do our best. The next version of Flutter Ads planned to release at the end of December.

**Comment by dwnu** [comment]
That's great to hear. Thank you for the information. I'll check it again after this next update then
