### ISSUE TITLE
Flutter Project Integration Issue with HMS: Plugin 'com.huawei.agconnect' Version Not Found

### ISSUE THREAD

**Issue by yusufkecer** [HMS-Core/hms-flutter-plugin#390]
Hello, I am new to HMS and trying to learn it. However, when I try to integrate my Flutter project by adding the dependency id "com.huawei.agconnect" version "1.9.0.303", I keep getting an error. I would appreciate any help.

_Error: Plugin [id: 'com.huawei.agconnect', version: '1.9.0.303'] was not found in any of the following sources_

**settings.gradle**

```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {url 'https://developer.huawei.com/repo/'} 
    }
}



plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
    id "com.huawei.agconnect" version "1.9.0.303"
}

include ":app"
```
**android gradle**

```
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {url 'https://developer.huawei.com/repo/'} 

    }
}
```
**app gradle**

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id 'com.huawei.agconnect'
}
```

**Comment by Hayolox** [comment]
Hi, how to solved this error ?

**Comment by mr-slonn** [comment]
Share the solution for the youngest novice developers :). The solution that is on stackoverflow is not very clear to me and does not seem logical.

**Comment by arpitVinz68** [comment]
add this to settings.gradle

`pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://developer.huawei.com/repo/' }
    }

    resolutionStrategy {
        eachPlugin {
            if (it.requested.id.getNamespace() == 'com.huawei.agconnect') {
                println ">> ${it.requested.id.id}"
                if (it.requested.id.id == 'com.huawei.agconnect.agcp') {
                    it.useModule('com.huawei.agconnect:agcp:1.9.1.301')
                }
                println ">> ${it.target}"
            } else {
                println ">  ${it.target}"
            }
        }
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version '8.9.1' apply false
    id "org.jetbrains.kotlin.android" version "2.1.20" apply false
    id "com.huawei.agconnect.agcp" version "1.9.1.301" apply false
}

include ":app"`
