### ISSUE TITLE
cannot compile under ios

### ISSUE THREAD

**Issue by yinsee** [HMS-Core/hms-flutter-plugin#4]
Fetching podspec for `huawei_push` from `.symlinks/plugins/huawei_push/ios`
    [!] The `huawei_push` pod failed to validate due to 1 error:
        - ERROR | attributes: Missing required attribute `authors`.
        - WARN  | license: Missing license type.
        - WARN  | description: The description is equal to the summary.
        - WARN  | [iOS] keys: Missing primary key for `source` attribute. The acceptable ones are: `git, hg, http, svn`.

**Comment by aktug** [comment]
Hello @yinsee 
Our plugins don't support iOS for now, in the next version these errors will be fixed 👍

**Comment by anas-iqbal** [comment]
Any idea how to handle this? because same pubsec is used for both android and iOS, it's working fine on android but giving error on iOS. Thanks

**Comment by aktug** [comment]
Dear @yinsee we are currently not supporting IOS, simply error indicates [podspec file](https://github.com/HMS-Core/hms-flutter-plugin/blob/master/flutter-hms-push/ios/huawei_push.podspec) needs to be reconfigured, iOS support will come in future versions.
