### ISSUE TITLE
[huawei_iap] IsEnvReadyResult.returnCode changed to String

### ISSUE THREAD

**Issue by deakjahn** [HMS-Core/hms-flutter-plugin#43]
Was there any specific reason to change `IsEnvReadyResult.returnCode` to `String` instead of `int`? Is this a mistake or do we need to adapt the code from now on?

**Comment by SerdarCanDev** [comment]
Hi @deakjahn , as the Huawei IAP Flutter Plugin grows, we introduce new result codes for better error handling. Now, you may handle both "plugin" and  "IAP Service" related errors. While IAP Service returning `int` return codes, plugin related result codes have `String` values. Hence, to be more consistent, and also gather them in a single error class, `HmsIapResult`, `returnCode` values changed to `String`. You have to adapt the code from now on. 

For detailed information about errors and their possible solutions, please refer to [HmsIapResults](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/hms-iap-results-0000001057877325).

**Comment by deakjahn** [comment]
OK, thanks. This would probably deserve a comment in the source code, though. :-)
