### ISSUE TITLE
How to customize markers??

### ISSUE THREAD

**Issue by momtboy** [HMS-Core/hms-flutter-plugin#5]
I want to customize the marker through the Widget? How should I handle it?

**Comment by aktug** [comment]
Hi @momtboy ;
You can find "Customizing a Marker" article at https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/drawmap-0000001050430819#EN-US_TOPIC_0000001050430819__section9496105015718

API Reference: https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/marker-0000001050296858
