### ISSUE TITLE
[huawei_push] Push.getTokenStream triggered across apps

### ISSUE THREAD

**Issue by darkang3lz92** [HMS-Core/hms-flutter-plugin#51]
**Description**
When calling `Push.getToken()` from AppsA, both AppsA and AppsB will be triggered `Push.getTokenStream` with same token. Risk of getting wrong token for other flutter apps that using `Push.getTokenStream`. 

**Expected behavior**
Push.getTokenStream only triggered for app itself that calling `Push.getToken()`.

**Current behavior**
`Push.getTokenStream` triggered across apps with same token.

**Environment**
 - Platform: Flutter
 - Kit: Push
 - Kit Version 5.0.2+301
 - OS Version Android 9

**Other**
You may reproduce it by creating 2 projects/apps and trigger `Push.getToken()` and print the token value of `Push.getTokenStream` in both projects. Make sure the other app in background is running / not killed.

**Comment by aktug** [comment]
Hi @darkang3lz92 ;
Our plugins have continuous development progress, this issue has been pointed out and fixed. The next version will be published at the next release cycle.
Thank you for your interest 👍👍

**Comment by darkang3lz92** [comment]
@aktug Thanks. Any workaround we can do for this issue until the update is released?

**Comment by darkang3lz92** [comment]
@aktug Just checked that `Push.onNotificationOpenedApp` has similar issue as well.

**Comment by aktug** [comment]
Hello @darkang3lz92 
You can add this line manually until the next release of Push Plugin will be released.

**Utils.java:82**
```java
intent.setPackage(PushPlugin.getContext().getPackageName()); // <-- This line is missing
```
This fix will solve both errors you mentioned. Thank you for understanding 👍

![image](https://user-images.githubusercontent.com/20382405/102902683-5eaf9500-4480-11eb-9537-96afc1eaf393.png)
