### ISSUE TITLE
upload to play store fails if using huawei_ads

### ISSUE THREAD

**Issue by moodstubos** [HMS-Core/hms-flutter-plugin#53]
I am using one code basis for play store as well app gallery. 

If I use huawei_ads as dependency in pubspec.yaml, I am not able to upload the release app bundle to play store.

play store error message: 

> Your App Bundle targets the following unrecognized languages: zz. The list of supported language codes can be found in the IANA registry. Invalid languages caused by third-party libraries can be excluded using the resConfigs Gradle property.

using 
```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.630], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
```

huawei_ads plugin version is 13.4.32

**Comment by furkansarihan** [comment]
Hello @moodstubos,

Can you try to specify your app's supported languages in your app's `build.gradle` as described in [here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/define-multi-language-set-0000001050040049-V5)?

**Comment by moodstubos** [comment]
@furkansarihan 
Thanks! Yes, I use this solution already as workaround and it works. But I think the huawei flutter libs should works as simple as possible and out of the box. I couldn't find the location but it somewhere it uses a not-android-valid language id.

**Comment by furkansarihan** [comment]
@moodstubos Yes, you are right!

We are not specify any language in our flutter plugin. This issue is caused by HMS Core. So, we will add required information to `huawei_ads`'s documentation.

**Comment by moodstubos** [comment]
> This issue is caused by HMS Core.
ah, thank you - I did not know this. 

> So, we will add required information to huawei_ads's documentation.
perfect! keep on you good work.

**Comment by EdgardoSchiffer** [comment]
Hello, I know this issue is closed but I just wanted to inform that this same behaviour occurs on huawei_map plugin.
It might be helpful to this hint into the maps plugin documentation.

**Comment by cagdasmer** [comment]
Hi @EdgardoSchiffer ,
Thank you for informing us. We'all add this information to the map plugin's documentation with the next version.
