### ISSUE TITLE
When there will be Application Initialization API and CheckUpdate API

### ISSUE THREAD

**Issue by KirisakiAria** [HMS-Core/hms-flutter-plugin#56]
Hello!

According to this: [https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-devguide](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-devguide)

If I want to publish my App on the Huawei App Market in China and use IAP，I must also use Application Initialization API and CheckUpdate API.

Could you tell me when there will be Application Initialization API and CheckUpdate API ? Thanks!

**Comment by cagdasmer** [comment]
Hello @KirisakiAria 

The AppGalleryKit and the APIs you mentioned are in the scope of AppGallery Connect plugins, and therefore are outside the scope of HMS plugins. 

Currently, you can ask about the AppGalleryKit in the [AGC Flutter Demo repository](https://github.com/AppGalleryConnect/agc-flutter-plugin). 
Plugin repository for AGC will also be available in the near future.

**Comment by KirisakiAria** [comment]
@cagdasmer 

Thanks for your reply!
