### ISSUE TITLE
HMS ML LivenessDetection on Android10 (Nokia): Failed to build unique file: /storage/emulated/0/Pictures Title image/jpeg

### ISSUE THREAD

**Issue by petodavid** [HMS-Core/hms-flutter-plugin#57]
I use ML liveness detection:
**Storage permission is granted!**
  ```
MLLivenessCapture livenessCapture = new MLLivenessCapture();
        MLLivenessCaptureResult result =
            await livenessCapture.startLivenessDetection(detectMask: true);
```

Error:
E/AndroidRuntime(13853): java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Pictures Title image/jpeg
E/AndroidRuntime(13853): 	at android.os.Parcel.createException(Parcel.java:2079)
E/AndroidRuntime(13853): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(13853): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
E/AndroidRuntime(13853): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/AndroidRuntime(13853): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
E/AndroidRuntime(13853): 	at android.content.ContentResolver.insert(ContentResolver.java:1831)
E/AndroidRuntime(13853): 	at android.provider.MediaStore.createPending(MediaStore.java:616)
E/AndroidRuntime(13853): 	at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:1771)
E/AndroidRuntime(13853): 	at com.huawei.hms.flutter.ml.utils.HmsMlUtils.saveBitmapAndGetPath(HmsMlUtils.java:71)
E/AndroidRuntime(13853): 	at com.huawei.hms.flutter.ml.body.LivenessDetectionMethodHandler.sendLivenessDetectionResult(LivenessDetectionMethodHandler.java:85)
E/AndroidRuntime(13853): 	at com.huawei.hms.flutter.ml.body.LivenessDetectionMethodHandler.access$100(LivenessDetectionMethodHandler.java:35)
E/AndroidRuntime(13853): 	at com.huawei.hms.flutter.ml.body.LivenessDetectionMethodHandler$1.onSuccess(LivenessDetectionMethodHandler.java:69)
E/AndroidRuntime(13853): 	at com.huawei.hms.mlsdk.livenessdetection.MLLivenessCapture.a(MLLivenessCapture.java:3)
E/AndroidRuntime(13853): 	at com.huawei.hms.mlsdk.livenessdetection.y.onCompleted(LivenessDetectActivity.java:1)
E/AndroidRuntime(13853): 	at com.huawei.hms.mlsdk.livenessdetection.g.a(MLLivenessDetectView.java:15)
E/AndroidRuntime(13853): 	at com.huawei.hms.mlsdk.livenessdetection.x.handleMessage(CaptureActivityHandler.java:5)
E/AndroidRuntime(13853): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(13853): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(13853): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/AndroidRuntime(13853): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13853): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(13853): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/Mliveness_Process(13853): Mliveness get the img shape(640,480)
E/Mliveness_Process(13853): Mliveness begin to change the 480*640 to 640*640
E/Mliveness_Process(13853): Mliveness  well memset 1228800 
E/Mliveness_Process(13853): Mliveness begin to check the img
E/Mliveness_Process(13853): Mliveness get the resize img(49,38,37) 
I/Mliveness_Process(13853): Mliveness get the input_data_num 50176

**Comment by sinan-aktepe** [comment]
Hi @petodavid ,
Can you provide information about your device model and android version?

**Comment by petodavid** [comment]
> Hi @petodavid ,
> Can you provide information about your device model and android version?

Model: Nokia 5.3
Android 10

**Comment by sinan-aktepe** [comment]
This problem occurs on some devices with android version **10**. But there may be a way we can consider as a workaround. Here are the steps:

1. In source code, go to the file named **HmsMlUtils.java**.
2. Find the method named **saveBitmapAndGetPath**.
3. Change the "Title" and "Desc" as following:
```java
return MediaStore.Images.Media.insertImage(inContext.getContentResolver(), inImage, "IMG_" + Calendar.getInstance().getTimeInMillis(), null);
```
Test your app again and let us know about it.

**Comment by petodavid** [comment]
> ```java
> "IMG_" + Calendar.getInstance().getTimeInMillis()
> ```

The issue was solved by changing the return value to: 
`            return MediaStore.Images.Media.insertImage(inContext.getContentResolver(), inImage, "IMG_" + Long.toString(Calendar.getInstance().getTimeInMillis()), null);
`
The provided code example was missing the long to string casting.

**Comment by petodavid** [comment]
Issue was fixed
