### ISSUE TITLE
[huawei_push: ^5.0.2+301] accessing other plugins from background message handler

### ISSUE THREAD

**Issue by sarope** [HMS-Core/hms-flutter-plugin#59]
Hi,

I'm trying to implement background message handling in Flutter with the huawei_push: ^5.0.2+301.

So far, I've got it running properly, and the background message handler is receiving background messages.

However, the issue comes in, when I want to use other Flutter plugins to process the received data from within the background message handler. These include sqlflite, path_provider, flutter_local_notifications. Whenever I  try to use these plugins, I get a MissingPluginException like the following:

```
Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (28548): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (28548): <asynchronous suspension>
E/flutter (28548): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (28548): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
```

I can, however, use these plugins from the firebase background handler function, so I imagine there is something not quite right with the HMS implementation.

Please advise.

**Comment by aktug** [comment]
Hello @sarope we'll fix this issue in the next release, thanks for your interest
