### ISSUE TITLE
Unable to get push token - no error code

### ISSUE THREAD

**Issue by KholofeloMoyaba** [HMS-Core/hms-flutter-plugin#6]
Hi

I'm calling `Push.getToken` method from Flutter and I'm not receiving the token (also not seeing a platform level error).

The log I'm seeing is as follows:
```
I/HMSSDK_BaseAdapter(12684): in baseRequest + uri is :push.gettoken, transactionId is : some-long-id
I/HMSSDK_PendingResultImpl(12684): init uri:push.gettoken
I/HMSSDK_PendingResultImpl(12684): setResultCallback
I/HMSSDK_PendingResultImpl(12684): setResult:0
I/HMSSDK_BaseAdapter(12684): baseCallBack.onComplete
I/HMSSDK_HmsClient(12684): receive msg status_code:0, error_code0, api_name:push.gettoken, app_id:my-id|, pkg_name:my-package, session_id:*, transaction_id:some-long-id, resolution:null
```

I have followed the AG connect steps to ensure that push is enabled and I've added the SHA-256 signature. I've also done the gradle setup - in fact maps integration works with the current gradle setup.

At the moment I'm unable to obtain the push to the server so we can send targetted pushes. Please assist.

**Comment by atavci** [comment]
By examining the logs, I can say that you are able to get the token from the server (0 result code means success). Are you listening the EventChannel that emits this token ? The plugin's example project displays a demo on this, the code is shown below:
```dart  
  String _token = '';
  static const EventChannel TokenEventChannel = EventChannel(Channel.TOKEN_CHANNEL);

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    if (!mounted) return;
    TokenEventChannel.receiveBroadcastStream()
        .listen(_onTokenEvent, onError: _onTokenError);
  }

  void _onTokenEvent(Object event) {
    setState(() {
      _token = event;
    });
    showResult("TokenEvent", event);
  }

  void _onTokenError(Object error) {
    setState(() {
      _token = error;
    });
    showResult("TokenEvent", error);
  }
```

If you are unable to obtain the token even after listening the TokenEventChannel, can you provide us with more details ?
- Huawei Push Kit Plugin version on pubspec.yaml
- Output from `flutter doctor` command
- EMUI Version

**Comment by KholofeloMoyaba** [comment]
Hi @atavci 

Thanks for the guidance. Adding the token event channel does work.

However, it still confuses me.

My understanding is that listening to `TokenEventChannel` stream is for listening to any changes on the token channel retrospectively.

What I'm trying to do, however, is request the token on demand. `Push.getToken` has a method signature as follows: `Future<String> getToken()`. So I'm expecting this method to return the token on demand - outside of subscribing to the event channel.

For example, I may need specific hooks where I need to get the token at that point. So I would expect to `Push.getToken` and get a value.

**Comment by KholofeloMoyaba** [comment]
@atavci / @Mike-mei

I looked through the plugin source code and I see the issue. 

The issue is that the android code for handling the getToken method doesn't accept the MethodChannel.Result object to pass the result back to flutter. It does, however, trigger the token event channel. This, in my opinion, is incorrect - or at least inconsistent behaviour.  If the intent isn't for `Push.getToken` to return the token value, then the method should be updated accordingly (e.g. it should return void) and documented properly.

Here is a link to the part of the code that's the culprit.
https://github.com/HMS-Core/hms-flutter-plugin/blob/master/flutter-hms-push/android/src/main/java/com/huawei/hms/flutter/push/hms/FlutterHmsInstanceId.java#L65

I can make a PR to fix this if you would allow that.

**Comment by aktug** [comment]
Hi @KholofeloMoyaba ;
First of all, thank you very much for your concerns,
While we were developing the plugin, we paid special attention to support EMUI 10 and lower versions. Because;

If the EMUI version is 10.0 or later on a Huawei device, a token will be returned through the **getToken** method. If the getToken method fails to be called, Huawei Push Kit automatically caches the token request and calls the method again. A token will then be returned through the **onNewToken** method.
If the EMUI version on a Huawei device is earlier than 10.0 and no token is returned using the **getToken** method, a token will be returned using the **onNewToken** method.

But as you pointed out, that section has escaped from attention. Actually it's okay, we can get token with listening "TOKEN_CHANNEL" as it is, we'll fix the return type in our next version. 

Thanks again @KholofeloMoyaba for your interest ~

**Comment by KholofeloMoyaba** [comment]
Hi again @aktug 

Thanks for your response. Yes, I think the issue which is problematic on my side is just the communication back to flutter via the `MethodChannel.Result`.  I don't have an issue with anything EMUI related.

I've already made and tested a fix which would make it much easier for other Flutter developers. I don't have the rights to make a PR directly against this repo, so I made a fork. Please see below the PR from the forked repo:
https://github.com/HMS-Core/hms-flutter-plugin/pull/7

I have already tested this on a flutter app running on a Huawei device and it works, while still respecting the `TOKEN_CHANNEL`. So nothing is lost.

**Comment by aktug** [comment]
Thank you for PR, we`ll look at your changes but there are different development processes in our team so at this time we can`t merge your PR directly, thank you @KholofeloMoyaba for your contribution 🍻
