### ISSUE TITLE
Add support with huawei_scan on iOS

### ISSUE THREAD

**Issue by yanshouwang** [HMS-Core/hms-flutter-plugin#60]
**Description**
huawei_scan is only support Android now, also can I use huawei_scan to detect camera's yuv stream?

**Expected behavior**
support both Android and iOS.

**Current behavior**
huawei_scan is only support Android now

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: [e.g. React-Native/Cordova/Flutter/Xamarin]
 - Kit: [e.g. Push/Map/Ads/Account/IAP]
 - Kit Version [e.g. 5.0.3]
 - OS Version [e.g. Android 11]
 - Android Studio version (if applicable) [e.g. 4.1]
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) 

**Other**
Add any other context about the problem here

**Comment by SerdarCanDev** [comment]
Hi @yanshouwang , thank you for your interest in our Huawei Scan Flutter Plugin.

Unfortunately, Huawei Scan Flutter Plugin is not supported on iOS for the time being, yet we are constantly updating our packages to provide powerful services and support to multiple platforms. Hence, please keep an eye on [pub.dev](https://pub.dev/publishers/developer.huawei.com/packages) for latest releases.

There are few options to detect and scan the camera's YUV stream in Huawei Scan Flutter Plugin. The options are as follows:

If you want to quickly build powerful barcode scanning capabilities into your app, the options listed below are recommended.
- **startDefaultView**: Brings up Default Scanning UI and returns a response after scanning the barcode using the camera or scanning from the gallery.
- **startCustomizedView**: Brings up Customized View Scanning UI according to your preferences.
- **startMultiProcessorCamera**: Brings up a scanning UI to scan multiple barcodes at the same time, according to your preferences.

In mentioned views, Huawei Scan Flutter Plugin directly controls the camera to maximize capabilities and handles the encoding/decoding operations for you. 

If you want to customize the scanning process and control the camera by yourself, the followings are a good choice.
 - **decodeWithBitmap**: Starts bitmap decoding API.
 - **Decode Modes of Multiprocessors**:  Scans barcodes synchronously/asynchronously in Multiprocessor mode. 

By nature, these modes require a `Uint8List` of an image to perform scanning capabilities. 

For detailed information on the Huawei Scan Flutter Plugin please refer to [Official Documentations](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001054309573). You may also test our plugin using the [demo app](https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-scan/example) provided with the package.
