### ISSUE TITLE
The Splash Ad do not be showed. Error code 499.

### ISSUE THREAD

**Issue by davidzou** [HMS-Core/hms-flutter-plugin#62]
**Description**
The Splash Ad do not be showed.

**Logs**
```
  [+1012 ms] I/HiAdSDK.RealtimeAdMediator( 5144):  doOnShowSloganEnd
  [   +1 ms] I/HiAdSDK.RealtimeAdMediator( 5144):  Ad fails to display or loading timeout, ad dismiss
  [        ] I/HiAdSDK.AdMediator( 5144):  ad failed:499
  [        ] I/HiAdSDK.AdMediator( 5144):  ad is already failed
  [        ] I/HiAdSDK.AdMediator( 5144):  notifyAdDismissed
  [        ] I/HiAdSDK.AdMediator( 5144):  ad already dismissed
```

**Environment**
 - Platform: Flutter
 - Kit: Ads
 - Kit Version : 13.4.35+300
 - OS Version : any
 - Android Studio version (if applicable) [4.1]
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) CN

**Comment by furkansarihan** [comment]
Hello @davidzou,

1. Make sure HMS Core version is 4.0+ in your device.
2. Don't set the country/Region to China if your phone is not ChinaROM.

Also you can test your apk in [cloud debugging](https://developer.huawei.com/consumer/en/console#/openCard/AppService/1045) to make sure there is no issue in your implementation.
