### ISSUE TITLE
something wrong with configuration while upload the release apk to appgallery store

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#64]
**Description**
i follow all the docs from huawei dev. website and from the flutter repo readme , but still i got a rejection for update hms services 
i only used this plugin : huawei_Iap, Huawei_account, Huawei_location
with the following pic that's the reject message :
<img width="848" alt="Screen Shot 2021-02-13 at 3 31 45 PM" src="https://user-images.githubusercontent.com/74349843/107851183-a1eb0c00-6e10-11eb-833b-345cfd0e4aff.png">

**Current behavior**
that's all my configration files : 

*build.gradle*
```
buildscript {
    repositories {
        ..
        maven { url 'https://developer.huawei.com/repo/' }
        ..
    }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
          ...
        classpath 'com.huawei.agconnect:agcp:1.4.2.301'
    }
    allprojects {
    repositories {
        ..
        maven { url 'https://developer.huawei.com/repo/' }
        ..
    }
    }
```

*android build.gradle*
```
...
apply plugin: 'com.huawei.agconnect'
...
    defaultConfig {
            resConfigs "ar", "en"
}
...
dependencies {
    implementation 'com.huawei.agconnect:agconnect-core:1.4.2.301'
    implementation 'com.huawei.hms:base:5.0.5.300'
    implementation 'com.huawei.hms:hwid:5.1.1.300'      
    implementation 'com.huawei.hms:iap:5.1.0.300'  
    implementation 'com.huawei.hms:appservice:5.0.4.302'  
    implementation 'com.huawei.hms:hianalytics:5.1.0.301'  
    implementation 'com.huawei.hms:location:5.1.0.300'  
}
```

*proguard-rules.pro*
```
-ignorewarnings 
-keepattributes *Annotation* 
-keepattributes Exceptions 
-keepattributes InnerClasses 
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable 
-keep class com.huawei.updatesdk.**{*;}
-keep class com.huawei.android.sdk.drm.**{*;}
-keep class com.huawei.agconnect.**{*;}
-keep class com.hianalytics.**{*;} 
-keep class com.hianalytics.android.**{*;}
-keep class com.huawei.hms.**{*;} 
-keep interface com.huawei.hms.analytics.type.HAEventType{*;}
-keep interface com.huawei.hms.analytics.type.HAParamType{*;}
-keep class com.huawei.hms.analytics.HiAnalyticsInstance{*;}
-keep class com.huawei.hms.analytics.HiAnalytics{*;}
-keepattributes EnclosingMethod

#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**
-keep class com.huawei.hms.flutter.** { *; }
-repackageclasses
```

*  I added the `agconnect-services.json` and all build.gradle thats connect `agconnect-services.json` to the app

# i follow all this references 
* https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-preparation#h1-1574846682104
* https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-get-started-flutter
* https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sdk-data-security-0000001050044906

and till now i got the same reject , So i would be appreciate that , if anyone can help to avoid this kind of rejection

**Comment by cagdasmer** [comment]
Hello @mustafa-707 ,

It seems you are trying to utilize the **AppGallery Kit** for your application. **Initialization API**, **CheckUpdate API** and the others are in the scope of AppGallery Connect plugins, and therefore are outside the scope of HMS plugins. 

Currently, you can ask your questions about the AppGallery in the [AGC Flutter Demo repository](https://github.com/AppGalleryConnect/agc-flutter-plugin).

**Comment by mustafa-707** [comment]
thank you very much i will reach them to get a final solution , i solved it by remove my app from china in appgallery
