### ISSUE TITLE
When you add ads_kit launcher icon of the app change to the default android icon.

### ISSUE THREAD

**Issue by fleoparra** [HMS-Core/hms-flutter-plugin#67]
**Description**
My project was created with the default settings of Android Studio. When I have added ads kit, my app icon change to the default android launcher. I found that this plugin has resources like ic_launcher and ic_launcher_background on the library android folder and in some cases, icons or resources from libraries could override app resources. When I branch this project and delete the resources my app icon return.

**Expected behavior**
That do not change the icon

**Current behavior**
the launcher icon change to android default icon

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: Flutter
 - Kit: Ads
 - Kit Version: 13.4.35+300
 - OS Version Android 11
 - Android Studio version (if applicable) 4.1

I have created a branch without this folder:
https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-ads/android/src/main/res/drawable-v24
and without this file:
https://github.com/HMS-Core/hms-flutter-plugin/blob/master/flutter-hms-ads/android/src/main/res/drawable/ic_launcher_background.xml 
and everything works fine. If you can delete those files from the library the problem could be solved.

**Comment by fleoparra** [comment]
Temporary workaround is to add the library like this:
  huawei_ads:
    git:
      url: https://github.com/fleoparra/hms-flutter-plugin.git
      ref: master
      path: flutter-hms-ads

On my branch I have deleted those files.

**Comment by furkansarihan** [comment]
Hi @fleoparra 

Can you describe your exact case with details from your res folder and manifest file? (Which asset paths used for launcher icon? Are they exist in your app's res folder?)

**Comment by fleoparra** [comment]
I am using ads kit on two projects and one time my app where rejected because my launcher icon was Android default icon.

I am android developer and I know that a library resource with the same name of my app resource can override the file. For that reason I started to find where was a launcher icon on a library and I discover the launcher files on ads kit library.

I try to suggest to delete those files from the library making a pull request but my pull request where closed. They told me that the right way is to open an issue.

I use the android assistant to generate android icons (you need two svgs one to background and the other for foreground and the tool generate the icons for you on mipmap folders and drawable folders).

In fact is weird to have the launcher icon on the files of the library.

**Comment by furkansarihan** [comment]
Hi @fleoparra 

We'll fix this issue in the next release. Thank you.

**Comment by fleoparra** [comment]
> 
> 
> Hi @fleoparra
> 
> We'll fix this issue in the next release. Thank you.

You has just release the new versión but there is no fix for this problem. Is better not to close the Issue until you fix them. I do the fix but you did not accept the pull request. It will be necessary to wait until the next release?
