### ISSUE TITLE
huawei_IAP request a feature to deal with some cases

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#68]
**Description**
I just finished from implement the Huawei_iap plugin and it worked perfectly without any problem , but i have a weird behavior with a specific scenario  , Now i have the screen which i show the price with a call-to-action button to buy , but when want to buy and and not the phone not signed in to App Galley it will take the user to sign in with AppGallery by using this : 
```
      IsEnvReadyResult response = await IapClient.isEnvReady();

``` 
now if the user signed in successfully it will bring user to the previous screen which the price is still not active and there's no flag from Huawei_iap that said the user is signed in successfully
also ` await IapClient.isEnvReady();` it fetch the login screen directly without any message which it not follow our app UX 

Many thanks

**Comment by SerdarCanDev** [comment]
Hi @mustafa-707 , thank you for your interest in our plugin. 

`isEnvReady` method checks whether the currently signed-in HUAWEI ID is located in a country or region where HUAWEI IAP is available. Thus, by nature, it is generally used as a control mechanism and convenience before displaying any product or IAP related method to a user. Also, as you mentioned, `isEnvReady` API redirects the user to sign in page, only if the API fails according to sign-in issues, yet the method should not be used as only sign in method in your application. 

To handle the sign in, and obtain the successful sign-in flag, it is advised to use [HUAWEI Account Flutter Plugin](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/introduction-0000001050766441-V1). Then you may call `isEnvReady` method to check users region to before proceeding to in app purchases methods. 

Please let us know about the development process, and don't forget to contact us if you have any questions.

**Comment by BombeyR** [comment]
Hello,
Please I, like to know; I used the AGC auth to sign in users also by email(NOt with Huawei ID). Does the IAP api also support such users?

**Comment by SerdarCanDev** [comment]
Hi @BombeyR , 

Unfortunately Huawei IAP requires Huawei ID in order to initiate and complete a purchase. Even if your user logs in using AGC-Auth plugin you should ensure that the user is also a Huawei ID holder. To check, you may use `isEnvReady` method and direct your user to log in Huawei ID with its credentials. For details please check [official documents](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/client-dev-guide-0000001051001691).

Have a good day!
