### ISSUE TITLE
Notification title and body not visible when onNotificationOpenedApp.

### ISSUE THREAD

**Issue by realvotum** [HMS-Core/hms-flutter-plugin#71]
Hello,

I have and issue with title and body fields when listening to notifications.

When I listen to `onNotificationOpenedApp` stream, I have none of the aforementioned fields available, they are nulls. Code:

```
      Push.onNotificationOpenedApp.listen((dynamic message) {
          print(message);
      });
```
Result:
`{remoteMessage: {data: null, originalUrgency: 2, receiptMode: 0, messageId: null, token: null, notification: {titleLocalizationArgs: null, LightSettings: null, icon: null, isLocalOnly: true, title: null, body: null, ChannelId: null, Importance: null, isAutoCancel: true, isDefaultLight: true, BadgeNumber: null, vibrateConfig: null, visibility: null, titleLocalizationKey: null, Color: null, Ticker: null, bodyLocalizationArgs: null, ImageUrl: null, isDefaultSound: true, Sound: null, bodyLocalizationKey: null, When: null, intentUri: null, ClickAction: null, Tag: null, NotifyId: 0, Link: null, isDefaultVibrate: true}, dataOfMap: {}, messageType: null, urgency: 2, contents: 0, collapseKey: null, sentTime: 0, from: null, to: null, sendMode: 0}, uriPage: null}`

The title and body parameters are nulls as you can see.

On the other hand, when I listen to `onMessageReceivedStream` stream, I have values for those fields available. Code:

```
      Push.onMessageReceivedStream.listen((RemoteMessage message) {
          print(message.toMap());
     );
```
Result:
`{to: , urgency: 2, originalUrgency: 2, messageType: , collapseKey: , data: , dataOfMap: {}, notification: {title: Title, titleLocalizationKey: null, titleLocalizationArgs: null, body: Body, bodyLocalizationKey: null, bodyLocalizationArgs: null, icon: null, Sound: null, Tag: null, Color: null, ChannelId: null, Ticker: null, intentUri: null, NotifyId: 0, BadgeNumber: null, Importance: 0, visibility: null, isDefaultLight: true, isDefaultSound: true, isDefaultVibrate: true, isAutoCancel: true, isLocalOnly: true, ImageUrl: null, Link: null, When: null, LightSettings: null, vibrateConfig: null}, sendMode: 0, receiptMode: 0}`

The title and body parameters are not nulls: title: Title, body: Body.

What is more, I am not sure if `Push.getInitialNotification()` returns the notification title and data accordingly, I have not checked that yet.

Is there anything I can do to get the notification title and body while listening to `onNotificationOpenedApp`?

Thanks

**Comment by atavci** [comment]
Hello @realvotum , 

In order to obtain the notification title and field from the `onNotificationOpenedApp` callback you need to send a local notification instead of a push notification and then you can read the data on the extras of the returned object. Unfortunately the push notifications are handled by the system and their payload can't be obtained from this callback. Furthermore, if you want to send data to your app with a push notification you can add custom key-value pairs or custom intent URI to your notification or you can send a data message instead.

Thank you for your interest on the Flutter Push Plugin.

**Comment by realvotum** [comment]
@atavci Okay, thank you for your clarification.

By the way, am I allowed by any means to color my notification icon somehow using hms push?
This is how I do it in firebase (and it works, it leaves a white icon in status bar, and coloured icon in notification entry under the toolbar):

```
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/icon_notification" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/notification_icon_color" />
```

This is how I do it using huawei messaging (and it does not work, it leaves a white icon in status bar which is good, but it does not colour the icon in notification under the toolbar):

```
        <meta-data
            android:name="com.huawei.messaging.default_notification_icon"
            android:resource="@drawable/icon_notification" />
        <meta-data
            android:name="com.huawei.messaging.default_notification_icon_color"
            android:resource="@color/notification_icon_color" />
```

The **com.huawei.messaging.default_notification_icon_color** is just a wild guess in here cause I'm unable to find any info on how to do that properly. 

Thank you in advance.

**Comment by atavci** [comment]
Hello, you can set the icon color of the notification in a push message request to the API by adding the color property and specifying a hex color string as follows:

```json
{
    "validate_only": false,
    "message": 
    {
        "notification":
        {
            "title": "Hello",
            "body": "This message has a coloured notification!"
        },
        "android":
        {
            "notification":
            {
                "click_action":
                {
                    "type": 3
                },
                "color":"#eba834"
            }
        },
        "token": ["your_push_token"]
    }
}
```

**Comment by realvotum** [comment]
@atavci Okay, thank you very much! :)
