### ISSUE TITLE
 No such file or directory on Flutter 2.0.2

### ISSUE THREAD

**Issue by zubyf09** [HMS-Core/hms-flutter-plugin#72]
**Description**
Huawei Push plugin is not configuring in the project. There is no error in the project but when I run command **flutter build apk.** The terminal gives the following error. 
                     

**Logs**
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:25:8: Error: Error when reading '../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/constants/Channel.dart': No such file or directory
import './constants/Channel.dart' as Channel;                           
       ^                                                                
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:26:8: Error: Error when reading '../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/constants/Method.dart': No such file or directory
import './constants/Method.dart' as Method;                             
       ^                                                                
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:27:8: Error: Error when reading '../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/constants/Code.dart': No such file or directory
import 'constants/Code.dart';                                           
       ^                                                                
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:32:35: Error: Getter not found: 'METHOD_CHANNEL'.
      const MethodChannel(Channel.METHOD_CHANNEL);                      
                                  ^^^^^^^^^^^^^^                        
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:34:28: Error: Getter not found: 'TOKEN_CHANNEL'.
      EventChannel(Channel.TOKEN_CHANNEL);                              
                           ^^^^^^^^^^^^^                                
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:36:28: Error: Getter not found: 'REMOTE_MESSAGE_RECEIVE_CHANNEL'.
      EventChannel(Channel.REMOTE_MESSAGE_RECEIVE_CHANNEL);             
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^               
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:38:28: Error: Getter not found: 'REMOTE_MESSAGE_SEND_STATUS_CHANNEL'.
      EventChannel(Channel.REMOTE_MESSAGE_SEND_STATUS_CHANNEL);         
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^           
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:40:28: Error: Getter not found: 'REMOTE_MESSAGE_NOTIFICATION_INTENT_CHANNEL'.
      EventChannel(Channel.REMOTE_MESSAGE_NOTIFICATION_INTENT_CHANNEL); 
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:42:28: Error: Getter not found: 'NOTIFICATION_OPEN_CHANNEL'.
      EventChannel(Channel.NOTIFICATION_OPEN_CHANNEL);                  
                           ^^^^^^^^^^^^^^^^^^^^^^^^^                    
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:44:28: Error: Getter not found: 'LOCAL_NOTIFICATION_CLICK_CHANNEL'.
      EventChannel(Channel.LOCAL_NOTIFICATION_CLICK_CHANNEL);           
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^             
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:50:67: Error: Getter not found: 'turnOnPush'.
    final String result = await methodChannel.invokeMethod(Method.turnOnPush);
                                                                  ^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:51:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:58:67: Error: Getter not found: 'turnOffPush'.
    final String result = await methodChannel.invokeMethod(Method.turnOffPush);
                                                                  ^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:59:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:69:67: Error: Getter not found: 'getId'.
    final String result = await methodChannel.invokeMethod(Method.getId);
                                                                  ^^^^^ 
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:75:67: Error: Getter not found: 'getAAID'.
    final String result = await methodChannel.invokeMethod(Method.getAAID);
                                                                  ^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:81:67: Error: Getter not found: 'getAppId'.
    final String result = await methodChannel.invokeMethod(Method.getAppId);
                                                                  ^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:87:67: Error: Getter not found: 'getOdid'.
    final String result = await methodChannel.invokeMethod(Method.getOdid);
                                                                  ^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:103:47: Error: Getter not found: 'getToken'.
    methodChannel.invokeMethod<String>(Method.getToken, args);          
                                              ^^^^^^^^                  
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:109:49: Error: Getter not found: 'getCreationTime'.
        await methodChannel.invokeMethod(Method.getCreationTime);       
                                                ^^^^^^^^^^^^^^^         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:115:67: Error: Getter not found: 'deleteAAID'.
    final String result = await methodChannel.invokeMethod(Method.deleteAAID);
                                                                  ^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:116:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:127:39: Error: Getter not found: 'deleteToken'.
    methodChannel.invokeMethod(Method.deleteToken, args);               
                                      ^^^^^^^^^^^                       
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:168:49: Error: Getter not found: 'send'.
        await methodChannel.invokeMethod(Method.send, remoteMsg.toMap());
                                                ^^^^                    
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:169:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:187:49: Error: Getter not found: 'subscribe'.
        await methodChannel.invokeMethod(Method.subscribe, args);       
                                                ^^^^^^^^^               
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:188:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:200:49: Error: Getter not found: 'unsubscribe'.
        await methodChannel.invokeMethod(Method.unsubscribe, args);     
                                                ^^^^^^^^^^^             
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:201:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:223:49: Error: Getter not found: 'setAutoInitEnabled'.
        await methodChannel.invokeMethod(Method.setAutoInitEnabled, args);
                                                ^^^^^^^^^^^^^^^^^^      
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:224:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:230:49: Error: Getter not found: 'isAutoInitEnabled'.
        await methodChannel.invokeMethod(Method.isAutoInitEnabled);     
                                                ^^^^^^^^^^^^^^^^^       
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:237:57: Error: Getter not found: 'getAgConnectValues'.
        await methodChannel.invokeMethod<String>(Method.getAgConnectValues);
                                                        ^^^^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:245:45: Error: Getter not found: 'showToast'.
    await methodChannel.invokeMethod(Method.showToast, args);           
                                            ^^^^^^^^^                   
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:255:49: Error: Getter not found: 'getInitialIntent'.
        await methodChannel.invokeMethod(Method.getInitialIntent);      
                                                ^^^^^^^^^^^^^^^^        
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:273:49: Error: Getter not found: 'getInitialNotification'.
        await methodChannel.invokeMethod(Method.getInitialNotification);
                                                ^^^^^^^^^^^^^^^^^^^^^^  
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:304:16: Error: Getter not found: 'localNotification'.
        Method.localNotification, localNotification);                   
               ^^^^^^^^^^^^^^^^^                                        
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:313:16: Error: Getter not found: 'localNotificationSchedule'.
        Method.localNotificationSchedule, localNotification);           
               ^^^^^^^^^^^^^^^^^^^^^^^^^                                
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:321:49: Error: Getter not found: 'getNotifications'.
        await methodChannel.invokeMethod(Method.getNotifications);      
                                                ^^^^^^^^^^^^^^^^        
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:332:49: Error: Getter not found: 'getScheduledNotifications'.
        await methodChannel.invokeMethod(Method.getScheduledNotifications);
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:342:65: Error: Getter not found: 'getChannels'.
    final List result = await methodChannel.invokeMethod(Method.getChannels);
                                                                ^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:350:49: Error: Getter not found: 'deleteChannel'.
        await methodChannel.invokeMethod(Method.deleteChannel, channelId);
                                                ^^^^^^^^^^^^^           
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:351:12: Error: Getter not found: 'Code'.
    return Code[result];                                                
           ^^^^                                                         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:357:49: Error: Getter not found: 'channelExists'.
        await methodChannel.invokeMethod(Method.channelExists, channelId);
                                                ^^^^^^^^^^^^^           
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:364:49: Error: Getter not found: 'channelBlocked'.
        await methodChannel.invokeMethod(Method.channelBlocked, channelId);
                                                ^^^^^^^^^^^^^^          
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:370:39: Error: Getter not found: 'cancelNotifications'.
    methodChannel.invokeMethod(Method.cancelNotifications);             
                                      ^^^^^^^^^^^^^^^^^^^               
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:376:39: Error: Getter not found: 'cancelAllNotifications'.
    methodChannel.invokeMethod(Method.cancelAllNotifications);          
                                      ^^^^^^^^^^^^^^^^^^^^^^            
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:381:39: Error: Getter not found: 'cancelScheduledNotifications'.
    methodChannel.invokeMethod(Method.cancelScheduledNotifications);    
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^      
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:386:39: Error: Getter not found: 'cancelNotificationsWithTag'.
    methodChannel.invokeMethod(Method.cancelNotificationsWithTag, tag); 
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^        
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:391:39: Error: Getter not found: 'cancelNotificationsWithId'.
    methodChannel.invokeMethod(Method.cancelNotificationsWithId, ids);  
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^         
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:400:39: Error: Getter not found: 'cancelNotificationsWithIdTag'.
    methodChannel.invokeMethod(Method.cancelNotificationsWithIdTag, idTags);
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^      
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:405:39: Error: Getter not found: 'enableLogger'.
    methodChannel.invokeMethod(Method.enableLogger);                    
                                      ^^^^^^^^^^^^                      
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:410:39: Error: Getter not found: 'disableLogger'.
    methodChannel.invokeMethod(Method.disableLogger);                   
                                      ^^^^^^^^^^^^^                     
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303/lib/push.dart:438:29: Error: Getter not found: 'BACKGROUND_MESSAGE_CHANNEL'.
      MethodChannel(Channel.BACKGROUND_MESSAGE_CHANNEL);                
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^                  
**Environment**
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.2 at /home/zubair/snap/flutter/common/flutter
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /opt/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

**Comment by atavci** [comment]
Hello,

From the logs you have shared, it seems that you are using Flutter Web. Unfortunately the HUAWEI Flutter Push Kit Plugin doesn't support the Flutter Web yet, we only support Android platform for the push plugin so please be sure to test it on an Android device with HMS Core (APK).
 
The issue can also be caused by a broken cache on your local pub instance. Can you try to run `flutter pub cache repair `command or delete the push plugin library cache on your `/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+303` folder and then run `flutter packages get` on the project ? 

I would like to also inform that currently we do not officialy support Flutter version over than 2.0.0 on our plugins yet. You can see the supported version range on the pubspec.yaml file of the plugin.

**Comment by zubyf09** [comment]
@atavci I haven't enabled web support in my project yet. Running my project on Android Simulator and Android device only.
I run **flutter pub cache repair** multiple times, deleted cache, etc, but getting the same error.
Even I tried on different laptops too and get the same issue.
When I remove this plugin everything goes to normal. nothing wrong with the project.

**Comment by atavci** [comment]
I have tried the push kit plugin version 5.0.2+303 with Flutter 2.0.2 and my push demo application runs successfuly. This issue can be caused by your local environment or there may be a configuration missing for the Huawei Flutter Push Kit Plugin. For further investigation, could you provide build.gradle files (app and project level) in order us to reproduce the issue. Meanwhile you may try the following:

**Comment by atavci** [comment]
I have tried the Push Kit Plugin version 5.0.2+303 with Flutter 2.0.2 and my demo application runs successfuly. The issue can be caused by your local environment or there may be a configuration missing for the the plugin. For further investigation, could you provide build.gradle files (app and project level) ? Meanwhile you may try the following:

- Make sure that you have completed all the integration process for the Huawei Flutter Push Plugin. For details you may refer to [this official documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrate-plugin-0000001050418527).
- Since Flutter version 2.0.0 and above is not officially supported yet, you may try to downgrade your Flutter version.
- You can try the former version (5.0.2+302) of the Huawei Flutter Push Kit Plugin.

We will also release a newer version of this plugin on the following weeks so you can stay tuned for the [latest version](https://pub.dev/packages/huawei_push).

**Comment by zubyf09** [comment]
Appp Gradle 
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_app"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
`
Project Level
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by zubyf09** [comment]
App Level 
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_app"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
`

**Comment by zubyf09** [comment]
Root Level

`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by atavci** [comment]
Hello again, there seems to be no configuration presented in your build gradle files. Please follow [this documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrate-plugin-0000001050418527) in order to integrate the Push Kit Plugin to your project. You would also need to configure a signing certificate and enable Push Kit on the AppGallery Connect by following [this documentation.](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/config-agc-0000001050178043)

Note: Minimum SDK Version in the build.gradle file should be 17 for integrating the Push Kit.

**Comment by zubyf09** [comment]
@atavci  There was a mistake, I posted the wrong Gradle files. I have updated my comment please check again.

**Comment by atavci** [comment]
I have checked your updated build.gradle files, everything seems ok but we couldn't reproduce your issue even by applying the same configurations. Altough the reproduction of the error is not possible at the moment, I have two suggestions that can solve your problem. First one is to download the push plugin from the [Huawei Developers Website](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/flutter-sdk-download-0000001050186157-V1), extract the plugin and paste it into the `/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_push-5.0.2+302` folder on your local machine. You should also change the push plugin version to `5.0.2+302` on your pubspec.yaml file. The second option is to copy the push kit plugin into your own project and specifying the path on the pubspec.yaml file as follows:

```yaml 
dependencies:    
    huawei_push:
        path: {library path, for example ../huawei_push}
``` 

You can find the details for the second option in [Integrating Flutter Push Plugin Document](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrate-plugin-0000001050418527-V1).

**Comment by atavci** [comment]
I have checked your updated build.gradle files, everything seems ok but we couldn't reproduce your issue even by applying the same configurations. Although the reproduction of this error is not possible at the moment, I have a suggestion that can solve your problem. First download the push plugin from the [Huawei Developers Website](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/flutter-sdk-download-0000001050186157-V1), and copy the push kit plugin into your own project, then specify the path on the pubspec.yaml file as follows:

```yaml 
dependencies:    
    huawei_push:
        path: {library path, for example ../huawei_push}
``` 

You can find the details for this approach in [Integrating Flutter Push Plugin Document](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrate-plugin-0000001050418527-V1).

**Comment by zubyf09** [comment]
@atavci Thanks for your help
I am following modular architecture in the Flutter project. In one of my modules, there was  huawei_push: ^5.0.2+301 and One modules was using huawei_push: ^5.0.2+303. I have changed both modules to huawei_push: ^5.0.2+301 and the project is working fine now. The sad part was Android Studio was not giving any conflict of dependency versions. So it was hard to trace. Again thanks for your help :)

**Comment by atavci** [comment]
You are welcome 👍, we now know that this error can be caused by the version mismatch you mentioned. Have a great day!
