### ISSUE TITLE
After upgrading to flutter 2.0 locationService.getLastLocation() is not working.

### ISSUE THREAD

**Issue by BasitCh** [HMS-Core/hms-flutter-plugin#74]
**Description**
After upgrading to flutter 2.0 locationService.getLastLocation() is not working.

here is my code 

`   // Init PermissionHandler
    PermissionHandler permissionHandler = PermissionHandler();
    // Request location permissions
    try {
      bool status = await permissionHandler.requestLocationPermission();
      // true if permissions are granted; false otherwise
      if (status) {
        FusedLocationProviderClient locationService =
            FusedLocationProviderClient();
        LocationRequest locationRequest = LocationRequest();
        LocationSettingsRequest locationSettingsRequest =
            LocationSettingsRequest(
          requests: <LocationRequest>[locationRequest],
          needBle: true,
          alwaysShow: true,
        );
        LocationSettingsStates states = await locationService
            .checkLocationSettings(locationSettingsRequest);
        if (states.gpsPresent && states.gpsUsable) {
          HuwaeiLocation.Location location =
              await locationService.getLastLocation();
          return Location(
              lat: location.latitude ?? 0.0, lng: location.longitude ?? 0.0);`

**Comment by ozkulbeng** [comment]
Hello,
After reading this issue, I upgraded my Flutter to 2.0.2-stable and ran the location demo app. It worked well for me.
I assume that you are getting **null** when you call getLastLocation() method. The getLastLocation() method obtains the device location from the system cache. If the obtained device location is null, the possible cause is that the system cache has been cleared. In this case, you need to call the **requestLocationUpdates()** method to obtain the device location and update the cache, and then call the getLastLocation() method to obtain the device location.

**Comment by BasitCh** [comment]
ok fixed it now
