### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by deakjahn** [HMS-Core/hms-flutter-plugin#75]
**Description**
Now with Flutter 2, this actually became practically compulsory.

**Expected behavior**
Null safety supported.

**Current behavior**
Null safety not supported.

**Environment**
 - Platform: Flutter

**Comment by SerdarCanDev** [comment]
Hi @deakjahn , thank you for informing us. 

Flutter 2.0 is a new release and we will eventually catch up with it soon, yet in order to keep supporting older Flutter versions, and also test the new features of Flutter on our plugins takes time. Please wait our major releases and keep an eye on [pub.dev](https://pub.dev/publishers/developer.huawei.com/packages).

**Comment by deakjahn** [comment]
That's why Google had about a year of transitional period to migrate to it before it becomes mainstream. :-))) Well, anyway, looking forward to be able to use the plugin again.

**Comment by deakjahn** [comment]
@SerdarCanDev See https://github.com/HMS-Core/hms-flutter-plugin/pull/76.

**Comment by fuatbakkal** [comment]
Thank you for your information. We also notice the new version of the Flutter platform. We will consider your opinion, it may be provided when appropriate. In the meantime, you may configure your project to use unsound null safety which makes your project compatible with plugins that are not using the null-safety feature.

**Comment by deakjahn** [comment]
There's a solution for that, too. All developers of other Flutter modules did the same. We created the null-safe version of our modules and published them on Pub.dev as prerelease, allowing both old and new versions to co-exist. This procedure has been properly documented by Google. Every developer could then choose which version of the plugin to use, whether to stick to the old one or move forward. It's up to you how you want to handle this but you have to be prepared that you will be inundated with complaints in the issue queue because the whole Flutter world around you has moved on.

**Comment by fleoparra** [comment]
Hi @deakjahn. In my case, for some huawei libraries, I downloaded the code and made the necesary changes to have my apps with null safety. As @deakjahn said, you can have a prerelease with null safety and offer two versions. In that case, you do not break support for Flutter 1.x
