### ISSUE TITLE
>Some cases when you add ads_kit launcher icon return to default android icon

### ISSUE THREAD

**Issue by fleoparra** [HMS-Core/hms-flutter-plugin#77]
Maybe it better not to close the bug until the fix is done.

> 
> 
> Hi @fleoparra
> 
> We'll fix this issue in the next release. Thank you.

You has just release the new versión but there is no fix for this problem. Is better not to close the Issue until you fix them. I do the fix but you did not accept the pull request. It will be necessary to wait until the next release?

_Originally posted by @fleoparra in https://github.com/HMS-Core/hms-flutter-plugin/issues/67#issuecomment-812713865_

**Comment by fuatbakkal** [comment]
Fixed with the new version  [huawei_ads 13.4.40+302](https://pub.dev/packages/huawei_ads/versions/13.4.40+302). (b8976408d6801861f6e475053a0e7dd596acfda0)
