### ISSUE TITLE
Unified Scan Code How to remove the picture icon in the upper right corner of the custom page

### ISSUE THREAD

**Issue by mulieli** [HMS-Core/hms-flutter-plugin#79]
Unified Scan Code How to remove the picture icon in the upper right corner of the custom page

**Comment by mulieli** [comment]
@fuatbakkal

**Comment by furkansarihan** [comment]
`isGalleryAvailable` can be used to hide picture icon.

```
CustomizedViewRequest(
    isGalleryAvailable: false, // no picture icon
    ...
```

Take a look at [this development guide](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/customized-view-0000001057136452) for details.

**Comment by mulieli** [comment]
> `isGalleryAvailable` can be used to hide picture icon.
> 
> ```
> CustomizedViewRequest(
>     isGalleryAvailable: false, // no picture icon
>     ...
> ```
> 
> Take a look at [this development guide](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/customized-view-0000001054199931) for details.

thank you
