### ISSUE TITLE
When to support IOS

### ISSUE THREAD

**Issue by mulieli** [HMS-Core/hms-flutter-plugin#80]
When to support IOS

**Comment by sooxt98** [comment]
LOL, they wont; iOS doesn't run huawei OS

**Comment by fuatbakkal** [comment]
Hello @mulieli. iOS support is not currently planned.

**Comment by amanokerim** [comment]
@fuatbakkal 
I can't understand one thing. The official site says:

> Supports Android (with HMS) apps, iOS apps, web apps, and Huawei quick apps.

And here you say no support for iOS. You mean no support for iOS in Flutter. And we can send push notifications to the native iOS app?
Thanks!
