### ISSUE TITLE
requestLocationUpdates throws PlatformException(10100: ARGUMENTS_EMPTY) in release build

### ISSUE THREAD

**Issue by brian-quah** [HMS-Core/hms-flutter-plugin#81]
Following the instructions for installation, pubspec.yaml as follows:
```
...
dependencies:
  huawei_location: ^5.1.0+301
...
```
<details>
<summary>AndroidManifest.xml</summary>

```
...
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
  <uses-permission android:name="com.huawei.hms.permission.ACTIVITY_RECOGNITION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
...
```
</details>

Works fine in debug build but not in release build - when attempting call `requestLocationUpdates`, PlatformException is thrown: 
```
PlatformException(10100, 10100:ARGUMENTS_EMPTY, null, null)
```
I've also tried using the exact same Dart code in the `huawei_location` example, but with the pubspec dependency pointing to pub.dev as described above, and the same issue arises - below are screenshots comparing the results of calling `requestLocationUpdates` in Debug and Release builds respectively.
<details>
<summary>Example Screenshots</summary>
Debug:

![screenshot-debug](https://user-images.githubusercontent.com/59129350/114819028-5abccf80-9def-11eb-906a-0c3ceff543b0.jpg)

Release:
![screenshot](https://user-images.githubusercontent.com/59129350/114817355-6e1a6b80-9dec-11eb-9524-50e893dd082d.jpg)
</details>

**Comment by ozkulbeng** [comment]
Hello @brian-quah!
I ran the example project and could call the `requestLocationUpdates` method in both debug and release modes successfully. 
Have you added the **proguard-rules.pro** file to your project? This exception might be caused by the missing proguard file.
You need to add the **proguard-rules.pro** file to **<_project_name_>/android/app** directory and modify your app level **build.gradle** file. You can find all the steps you need in the [development guide](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrate-plugin-0000001050303168-V1#EN-US_TOPIC_0000001050303168__section115852240420).

If the problem still occurs, please also add your logcat outputs in your next comment.

**Comment by brian-quah** [comment]
@ozkulbeng 
> Have you added the **proguard-rules.pro** file to your project? This exception might be caused by the missing proguard file.

Thanks, this was the issue causing the problem - I wasn't aware there was a separate setup guide apart from the Installation tab on the plugin page on [pub.dev](https://pub.dev/packages/huawei_location) as I found the plugin through it rather than through Huawei's website.

@aktug
Can the instructions pertaining excluding the HMS Core SDK from obfuscation be added to [https://pub.dev/packages/huawei_location/install](https://pub.dev/packages/huawei_location/install)?  The page in its current form has no indication that this step is necessary for release builds, and a [link to the obfuscation script instructions](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrate-plugin-0000001050303168-V1#EN-US_TOPIC_0000001050303168__section115852240420) (or including the section directly) should be sufficient to resolve this issue.

**Comment by fuatbakkal** [comment]
Hello @brian-quah. Firstly, thank you for the feedback. Unfortunately, the `Installing` page on the pub.dev can't be modified. Additional installation steps can be followed from [`Development Process`](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/dev-process-0000001089376648) page.
