### ISSUE TITLE
Remove and set new background to image.

### ISSUE THREAD

**Issue by shrutiramnandan** [HMS-Core/hms-flutter-plugin#82]
I'm trying to remove background from the image and try to set new background to image.
currently able to remove background from the image not bale to set new background from the image.
[check_this_built_in_android](https://medium.com/huawei-developers/build-a-background-eraser-app-with-huawei-ml-kit-image-segmentation-52208a7471ee#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImRlOTU1NmFkNDY4MDMxMmMxMTdhZmFlZjI5MjBmNWY5OWE0Yzc5ZmQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2MTg5ODUyNDYsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwODA2MDc3NTE2NzEyODk3Nzg0NiIsImVtYWlsIjoic2hydXRpcmFtbmFuZGFuc2hhcm1hQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJuYW1lIjoiU2hydXRpIFJhbW5hbmRhbiBzaGFybWEiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2otVjR4V2RkdnVNYVQtY0xyelVWenY1bHdTMlpOWnNKLUd3NkVHdW5JPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IlNocnV0aSIsImZhbWlseV9uYW1lIjoiUmFtbmFuZGFuIHNoYXJtYSIsImlhdCI6MTYxODk4NTU0NiwiZXhwIjoxNjE4OTg5MTQ2LCJqdGkiOiIzOGY0N2U3ZTg0YmU4ZTE5ODhkMTNkZjc1MWJkNzg1NDMxN2I1NTgwIn0.hIbLp_GSXhyPRoyqZMRlpjfFoyCWbqw7_eyBqV-XouTTeDDD7mz4m1WlUPcwQocBonEHQ5ERW2EbhGFcuHiNqLpM4pB1ZXAD8JaL3CQMFxF9JOQ6sOmYrsK_dep4FxVYY5nasIbMyVO_RkApyBww7IOiLWffcHay3jyhcgAvCmMaXAsjDYhGyjGs6VMRFaZiUhZVE3FrvKQu0Obbo93ULC7us-DoZJFReWBqCjKTbM2s-Kx5zadWiF9e_WnDYn3oO-cKOjYWdXVeBKULoL2TUnlCD3oOq6v5lOS82qPJ3Gw56uUG_AXxQbXC5npr8a7BqwwuHWhtIlymcPf9X3WKmA)

CODE:
Widget to pick image from the GALLERY;:

``` 
  Container(
      width: MediaQuery.of(context).size.width,
      child: ElevatedButton(
          style: ElevatedButton.styleFrom(
              primary: Colors.blueAccent,
              textStyle: TextStyle(color: Colors.white)),
          child: Text("PICK FROM GALLERY"),
          onPressed: () async {
            final String path =
                await getImage(ImageSource.gallery);
                  _startRecognition(path, context);
          })),
```

Removing background :
``` 
void _startRecognition(String path, context) async {
    setting.path = path; 
    setting.analyzerType = MLImageSegmentationAnalyzerSetting.BODY_SEG;
    setting.scene = MLImageSegmentationAnalyzerSetting.FOREGROUND_ONLY;
     segmentation = await analyzer.asyncAnalyzeFrame(setting);

     var filePath= await FlutterAbsolutePath.getAbsolutePath(segmentation.foregroundUri); // Here I  got human body_seg with transparent background
    File imageFile = File(filePath); 
    //Shown obtained image  to next screen.
    Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => AddFilterImageScreen(
            imageFile : imageFile
      
          )));
   }
``` 

ADD BACKGROUND:
``` 
  Container(
      width: MediaQuery.of(context).size.width,
      child: ElevatedButton(
          style: ElevatedButton.styleFrom(
              primary: Colors.blueAccent,
              textStyle: TextStyle(color: Colors.white)),
          child: Text("ADD BACKGROUND"),
          onPressed: () async {
            final String selectedBackgroundImagepath =
                await getImage(ImageSource.gallery);
                  
          })),
```

![processed](https://user-images.githubusercontent.com/49190035/115537860-dff52800-a2b8-11eb-99ea-43c962dba277.jpeg)

**Comment by sinan-aktepe** [comment]
Hi @shrutiramnandan , Unfortunately the native ML Kit SDK does not provide such an API like you've mentioned.

**Comment by shrutiramnandan** [comment]
@sinan-aktepe ,  Huawei ML Kit provides , you may check link which I mentioned in the issue. Someone has already implemented it but only in android.

**Comment by sinan-aktepe** [comment]
The implementation for applying background image is not relevant to ML SDK. In this case, SDK only outputs different layers of given image. So the developer had to do his own implementation to apply a background image.
