### ISSUE TITLE
channel appears to users 

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#86]
**Description**
Hello , After applying huawei_push plugin and it works perfect no problems , i was found in my app settings the name of the channel is appears to user like that : 

```
huawei-hms-flutter-push-channel
``` 

i checked the plugin to found it in java > constants > core.java : 

```
    String NOTIFICATION_CHANNEL_NAME = "huawei-hms-flutter-push-channel";

```

there's a way to define it with deferent name or hide it to users , it's not good to make users know the app using flutter and the name of the channel

**Comment by atavci** [comment]
Hello, 

You can specify the channel name by the HMSLocalNotificationAttr.CHANNEL_NAME parameter when sending a local notification as follows:
```dart
Map<String, dynamic> localNotificationParams = {
    HMSLocalNotificationAttr.TITLE: 'Notification Title',
    HMSLocalNotificationAttr.MESSAGE: 'Notification Message',
    HMSLocalNotificationAttr.SHOW_WHEN: true,
    HMSLocalNotificationAttr.CHANNEL_NAME: "My-Channel", // Define a channel name
    HMSLocalNotificationAttr.CHANNEL_ID: "channel1", // Define a channel id.
    HMSLocalNotificationAttr.LARGE_ICON: 'ic_launcher',
    HMSLocalNotificationAttr.SMALL_ICON: 'ic_notification',
    HMSLocalNotificationAttr.BIG_TEXT: 'This is a bigText',
    HMSLocalNotificationAttr.SUB_TEXT: 'This is a subText',
    HMSLocalNotificationAttr.VIBRATE: false,
    HMSLocalNotificationAttr.VIBRATE_DURATION: 1000,
    HMSLocalNotificationAttr.TAG: 'hms_tag',
    HMSLocalNotificationAttr.GROUP_SUMMARY: false,
    HMSLocalNotificationAttr.ONGOING: false,
    HMSLocalNotificationAttr.IMPORTANCE: Importance.MAX,
};

Map<String, dynamic> response =
          await Push.localNotification(notification);
```

Note that each time you want to create a different channel you must specify a unique channel id.  If you don't specify a channel id or a channel name, default values will be used instead.
