### ISSUE TITLE
Way to disable Analytics auto init in iOS

### ISSUE THREAD

**Issue by Jasphere-Appsploration** [HMS-Core/hms-flutter-plugin#87]
We have integrated Firebase Analytics for our app. To expand our app to Huawei devices, we integrated Huawei Analytic, Push and Crash.

However, our aim is to send the analytic data to Huawei Analytics ONLY if the device is a Huawei Device. Hence we do not want to init the Analytic in iOS.

Currently when we try to run our app, we get this error and the app crash instantly:
`Exception: AGConnectCrashPlugin init failed, exception name: NSGenericException, exception reason: agconnect-services.plist Not Found.`

**Comment by rahmicanisin** [comment]
hi @Jasphere-Appsploration,
When you added it to the pubspec.yaml file, you were integrated  the sdk into ios side. Even if you do not use the iOS side, you have to add the agconnect-services.plist file to the flutter-Xcode project as you have implemented the sdk.

**Comment by Jasphere-Appsploration** [comment]
> hi @Jasphere-Appsploration,
> When you added it to the pubspec.yaml file, you were integrated the sdk into ios side. Even if you do not use the iOS side, you have to add the agconnect-services.plist file to the flutter-Xcode project as you have implemented the sdk.

If I understand correctly, if I include the agconnect-services.plist and integrated the service, the analytic will be sent to both Firebase Analytics and Huawei Analytic. This is not something we desired, as we only want analytic data from Huawei device to be sent to Huawei Analytic Service.

**Comment by rahmicanisin** [comment]
I understand your issue, but it would not be appropriate for other users for us to change it so you have to change it yourself. - You should download the plugin and open the Xcode project. (huawei_analytics/example/ios/Runner.xcworkspace)
- Delete the agconnect-services.plist file. 
<img width="380" alt="agconnect-services.plist file" src="https://user-images.githubusercontent.com/45042659/120328679-bd145580-c2f3-11eb-93ac-0ef4a4534319.png">
