### ISSUE TITLE
use scanner as a widget

### ISSUE THREAD

**Issue by mahanabd** [HMS-Core/hms-flutter-plugin#88]
I want to use the huawei_scan as a widget in one of the button navigation view pages.
but I can just call the scanner whit the new page that opened on my app whit this code:

`DefaultViewRequest request = new DefaultViewRequest( scanType: HmsScanTypes.AllScanType ); 
      await HmsScanUtils.startDefaultView(request).then((value) {...`

is any solution to use scanner like widet?

**Comment by SerdarCanDev** [comment]
Hi @mahanabd , 

Unfortunately Huawei Scan Flutter Plugin's default and customized views are designed and implemented as full page camera views. 

To use huawei_scan as a widget, or as an inline camera, you may implement your own camera, or use a 3rd party plugin that offers camera as a widget, and process the camera output using `decodeWithBitmap`, `decodeMultiSync`, or `decodeMultiAsync` methods of the Huawei Scan Flutter Plugin. Please check [this link](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/hms-scan-utils-0000001054150792-V1#EN-US_TOPIC_0000001054150792__section18317616142618) for detailed information about `decodeWithBitmap` API.
