### ISSUE TITLE
Note: Some input files use or override a deprecated API.  

### ISSUE THREAD

**Issue by boonjun-marslab** [HMS-Core/hms-flutter-plugin#89]
**Description**
Note: /Users/user/.pub-cache/hosted/pub.dartlang.org/huawei_analytics-5.1.0+301/android/src/main/java/com/huawei/hms/flutter/analytics/logger/HMSLogger.java uses or overrides a deprecated API.

**Screenshots**
![image](https://user-images.githubusercontent.com/81542667/121458404-ddbb6a00-c9db-11eb-854a-45d1141a63a9.png)

**Environment**
 - Platform: Flutter
 - Flutter: 1.22.6
 - Dart SDK version: 2.10.5

**Comment by devfemibadmus** [comment]
planned now?
