### ISSUE TITLE
Migration to flutter 2.0

### ISSUE THREAD

**Issue by realvotum** [HMS-Core/hms-flutter-plugin#90]
Hello guys,

Are you planning to migrate your plugins to flutter 2.0? Especially flutter-hms-map,  it is restricted to flutter ">=1.12.13+hotfix.6 <2.0.0", thus I cannot upgrade my other dependencies which I need cause maps block me.

Thanks

**Comment by fleoparra** [comment]
I have the same problem.

**Comment by wangrui112211** [comment]
I have the same problem.

**Comment by juanxme** [comment]
Please add support to Null safety

**Comment by wangrui112211** [comment]
Please add support to Null safety

**Comment by jjsebastianfuertes** [comment]
Hi, Is there any intention to migrate to null safety?

**Comment by Mike-mei** [comment]
In the latest released version, Account ed91b62, Ads b897640, IAP ca07ec7 and Analytics e8abb1e plugins have supported null safety.

**Comment by sulthanalihsan** [comment]
when will the update huawei_map & huawei_location for null safety support?

**Comment by EhabSalah** [comment]
What about the null safety support

**Comment by Jan-Stepien** [comment]
Nullsafe, Dart 2.12+ Its essential

**Comment by Cola-Liu** [comment]
Null safety，please！

**Comment by Joseph-Nathan** [comment]
Please add support to Null safety

**Comment by agmaxwellh** [comment]
Please add support to Null safety!

**Comment by d9j** [comment]
i know it will get downvotes from flutter fans but  this of reasons i stick with making native app in serious projects.  no issues with integrating/updating vendors libraries. because they get first class support

**Comment by Mike-mei** [comment]
Account, Ads, Analytics, DTM, IAP, Location, Map, Nearby Service, Push, Scan, Site, 3D Modeling, Availabity and Contact Shield have supported null safety now. The latest version have been published on [Pub.dev](https://pub.dev/publishers/developer.huawei.com/packages). More plugins will supported null safety in the future, please stay turned.

**Comment by ozkulbeng** [comment]
[Awareness](https://pub.dev/packages/huawei_awareness) and [Game Service](https://pub.dev/packages/huawei_gameservice) plugins have also null safety support now. You can also check the documentations to find out more about [Awareness](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001074110480) and [Game Service](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001080980430).

**Comment by ozkulbeng** [comment]
All of HMS Plugins support null safety now. You can access all the packages on [pub.dev](https://pub.dev/publishers/developer.huawei.com/packages).

Thank you for your interest in our plugins.

**Comment by realvotum** [comment]
Great, thank you! :)
