### ISSUE TITLE
E/HmsSiteKit_QuerySuggestionTaskApiCall_65(15538): responseErrorCode errorCode = 6 errorReason = REQUEST_DENIED

### ISSUE THREAD

**Issue by StefanZeuch** [HMS-Core/hms-flutter-plugin#91]
**Description**
Getting the error `E/HmsSiteKit_QuerySuggestionTaskApiCall_65(15538): responseErrorCode errorCode = 6 errorReason = REQUEST_DENIED` when trying to call `querySuggestion` with site kit.

**Expected behavior**
To return the location query results

**Current behavior**
I get the error `E/HmsSiteKit_QuerySuggestionTaskApiCall_65(15538): responseErrorCode errorCode = 6 errorReason = REQUEST_DENIED`

**Logs**
`E/HmsSiteKit_QuerySuggestionTaskApiCall_65(14760): responseErrorCode errorCode = 6 errorReason = REQUEST_DENIED`

**Environment**
 - Platform: Flutter
 - Kit: Site Kit
 - Kit Version: 5.1.0+301
 - OS Version Android 10 (Huawei P40 Lite)

I have cloned the example repo and inserted my API Key and receive the same error

**Comment by ozkulbeng** [comment]
Hello @StefanZeuch 
Thank you for reporting this issue. I reproduced your error and it was caused by not encoding the API Key. 
Please encode your API Key and then use it in your project as shown below.
```
String API_KEY = Uri.encodeComponent('<api_key>');
final SearchService _searchService =
  await SearchService.create(API_KEY);
```

**Comment by StefanZeuch** [comment]
Resolved. Thank you.
