### ISSUE TITLE
NoSuchMethodError: No virtual method getAccount()

### ISSUE THREAD

**Issue by LateinitTN** [HMS-Core/hms-flutter-plugin#94]
**Description**
When trying to login with the Huawei ID app is crash 

**Logs**
E/AndroidRuntime(22985): java.lang.NoSuchMethodError: No virtual method getAccount()Landroid/accounts/Account; in class Lcom/huawei/hms/support/account/result/AuthAccount; or its super
classes (declaration of 'com.huawei.hms.support.account.result.AuthAccount' appears in /data/app/com.test.social.login-7lUZ244vkBFDHsTwHPfh5w==/base.apk)
E/AndroidRuntime(22985):        at com.huawei.hms.flutter.account.util.AccountBuilder.authAccountToMap(AccountBuilder.java:98)
E/AndroidRuntime(22985):        at com.huawei.hms.flutter.account.handlers.AccAuthService.lambda$onActivityResult$8$AccAuthService(AccAuthService.java:157)
E/AndroidRuntime(22985):        at com.huawei.hms.flutter.account.handlers.-$$Lambda$AccAuthService$R99R2YTXN7L3umVp8WUMlpfi8hQ.onSuccess(Unknown Source:6)
E/AndroidRuntime(22985):        at com.huawei.hmf.tasks.a.h$1.run(Unknown Source:27)
E/AndroidRuntime(22985):        at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(22985):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(22985):        at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(22985):        at android.app.ActivityThread.main(ActivityThread.java:8387)

**Environment**
- classpath 'com.huawei.agconnect:agcp:1.4.2.301'
- implementation "com.huawei.hms:hwid:5.3.0.302"
- implementation 'com.huawei.hms:push:5.3.0.301'
- implementation "com.huawei.agconnect:agconnect-auth:1.5.2.300"
- implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
- agconnect_auth: ^1.2.0+300
- huawei_account: ^5.2.0+300

**Other**
about configuration is completed but it still a problem.

**Comment by sinan-aktepe** [comment]
Hi @LateinitTN ,

We tested **huawei_account** and **agconnect_auth** plugins in an example app and couldn't reproduce the issue.

You don't have to add sdk dependencies in your app. Our plugins handle it. Please delete those configurations from your gradle files. You can refer [here](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/config-agc-0000001050767061) for **huawei_account** configurations.

**Comment by LateinitTN** [comment]
@sinan-aktepe I'm already creating and enable the account kit also, but it is still a problem. But let me try to test again. thank you for replying.
![Account Kit](https://user-images.githubusercontent.com/28226115/127088886-b09f4719-29ac-422c-80b5-723555794b0a.PNG)
![Project Config.](https://user-images.githubusercontent.com/28226115/127088700-52a0678b-76e2-484e-8987-a0851c74c699.png)

**Comment by michael-soh** [comment]
Hi @sinan-aktepe , I am experiencing the same error as @LateinitTN. 
I am currently using
- huawei_account: ^5.2.0+300
- classpath 'com.huawei.agconnect:agcp:1.6.0.300' (in gradle)

The authentication screen shows up but when I attempt to login, the app crashes. I have enabled the account kit as well.
![image](https://user-images.githubusercontent.com/82438343/129576240-07193e76-7926-4af6-8bdf-43bb6f1206cb.png)

I noticed in my agconnect-services.json under services, there are only analytics, search, cloudstorage, ml. The account kit is nowhere to be found. Is there something wrong with my agconnect-services.json or you don't need to have an account kit written there.

**Comment by sinan-aktepe** [comment]
Hi @michael-soh,

Can you share;

- The HMS Core version of your test device,
- **android/app/build.gradle** configuration

So we can try to reproduce the issue.

**Comment by michael-soh** [comment]
@sinan-aktepe  yeap here you go

HMS Core version : 6.0.1.306

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.huawei.agconnect'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.xxxx"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {

        debug {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }

        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
    implementation 'com.huawei.hms:hwid:5.3.0.305'

}



```

**Comment by sinan-aktepe** [comment]
@michael-soh Please delete these dependencies from your **build.gradle** file. It's not necessary.
```gradle
implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
implementation 'com.huawei.hms:hwid:5.3.0.305'
```
Version **5.2.0+300** already uses SDK version **5.2.0.300**. Please try it this way and inform us about the progress.

**Comment by michael-soh** [comment]
@sinan-aktepe thanks for the prompt response, it is working now :)
